import { Document, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType, AlignmentType, BorderStyle, HeadingLevel, Header, Footer, PageNumber, NumberFormat } from 'docx';
import { saveAs } from 'file-saver';
import { SnomedItemForVerification } from './LGImageVerificationModal';

export interface AuditEntry {
  item: SnomedItemForVerification;
  decision: 'confirmed' | 'removed' | 'edited' | 'skipped';
  originalTerm?: string;
  originalCode?: string;
  editedTerm?: string;
  editedCode?: string;
  reviewStartTime: string;
  reviewEndTime: string;
  reviewDurationSeconds: number;
}

export interface AuditSession {
  patientId: string;
  patientNhsNumber: string;
  patientName: string;
  auditorName: string;
  auditorEmail: string;
  auditStartTime: string;
  auditEndTime: string;
  totalDurationSeconds: number;
  totalItems: number;
  confirmedCount: number;
  removedCount: number;
  editedCount: number;
  skippedCount: number;
  averageTimePerItemSeconds: number;
  entries: AuditEntry[];
}

const NHS_BLUE = '005EB8';

const formatDateTime = (isoString: string): string => {
  const date = new Date(isoString);
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const month = months[date.getMonth()];
  const year = date.getFullYear();
  return `${hours}:${minutes} on ${day}-${month}-${year}`;
};

const formatDuration = (seconds: number): string => {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  if (mins > 0) {
    return `${mins} minute${mins !== 1 ? 's' : ''} ${secs} second${secs !== 1 ? 's' : ''}`;
  }
  return `${secs} second${secs !== 1 ? 's' : ''}`;
};

const formatTime = (seconds: number): string => {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}`;
};

const formatNhsNumber = (nhs: string | null | undefined): string => {
  if (!nhs) return '';
  const cleaned = nhs.replace(/\s/g, '');
  if (cleaned.length !== 10) return nhs;
  return `${cleaned.slice(0, 3)} ${cleaned.slice(3, 6)} ${cleaned.slice(6)}`;
};

const createBorderedCell = (content: string | Paragraph[], options?: { bold?: boolean; width?: number; shading?: string; alignment?: typeof AlignmentType[keyof typeof AlignmentType] }): TableCell => {
  const paragraphs = Array.isArray(content) ? content : [
    new Paragraph({
      children: [
        new TextRun({
          text: content,
          bold: options?.bold,
          font: 'Fira Sans',
          size: 20,
        }),
      ],
      alignment: options?.alignment || AlignmentType.LEFT,
    }),
  ];

  return new TableCell({
    children: paragraphs,
    width: options?.width ? { size: options.width, type: WidthType.PERCENTAGE } : undefined,
    shading: options?.shading ? { fill: options.shading } : undefined,
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1, color: 'd1d5db' },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: 'd1d5db' },
      left: { style: BorderStyle.SINGLE, size: 1, color: 'd1d5db' },
      right: { style: BorderStyle.SINGLE, size: 1, color: 'd1d5db' },
    },
    margins: {
      top: 80,
      bottom: 80,
      left: 120,
      right: 120,
    },
  });
};

const createHeaderCell = (content: string, width?: number): TableCell => {
  return createBorderedCell(content, { bold: true, width, shading: NHS_BLUE, alignment: AlignmentType.CENTER });
};

export const generateAuditReport = async (session: AuditSession): Promise<void> => {
  const doc = new Document({
    styles: {
      default: {
        document: {
          run: {
            font: 'Fira Sans',
            size: 22,
          },
        },
      },
    },
    sections: [
      {
        properties: {},
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: 'SNOMED Audit Report',
                    bold: true,
                    font: 'Fira Sans',
                    size: 20,
                    color: NHS_BLUE,
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: 'Generated by Notewell AI • ',
                    font: 'Fira Sans',
                    size: 18,
                    color: '666666',
                  }),
                  new TextRun({
                    children: [PageNumber.CURRENT],
                    font: 'Fira Sans',
                    size: 18,
                    color: '666666',
                  }),
                  new TextRun({
                    text: ' of ',
                    font: 'Fira Sans',
                    size: 18,
                    color: '666666',
                  }),
                  new TextRun({
                    children: [PageNumber.TOTAL_PAGES],
                    font: 'Fira Sans',
                    size: 18,
                    color: '666666',
                  }),
                ],
              }),
            ],
          }),
        },
        children: [
          // Title
          new Paragraph({
            children: [
              new TextRun({
                text: 'SNOMED Code Audit Report',
                bold: true,
                font: 'Fira Sans',
                size: 36,
                color: NHS_BLUE,
              }),
            ],
            spacing: { after: 400 },
          }),

          // Patient Details
          new Paragraph({
            text: 'Patient Details',
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 200, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createBorderedCell('Patient Name', { bold: true, width: 30, shading: 'f3f4f6' }),
                  createBorderedCell(session.patientName || 'Not recorded', { width: 70 }),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('NHS Number', { bold: true, width: 30, shading: 'f3f4f6' }),
                  createBorderedCell(formatNhsNumber(session.patientNhsNumber) || 'Not recorded', { width: 70 }),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('Record ID', { bold: true, width: 30, shading: 'f3f4f6' }),
                  createBorderedCell(session.patientId, { width: 70 }),
                ],
              }),
            ],
          }),

          // Audit Summary
          new Paragraph({
            text: 'Audit Summary',
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createBorderedCell('Auditor Name', { bold: true, width: 30, shading: 'f3f4f6' }),
                  createBorderedCell(session.auditorName, { width: 70 }),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('Auditor Email', { bold: true, width: 30, shading: 'f3f4f6' }),
                  createBorderedCell(session.auditorEmail, { width: 70 }),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('Audit Start', { bold: true, width: 30, shading: 'f3f4f6' }),
                  createBorderedCell(formatDateTime(session.auditStartTime), { width: 70 }),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('Audit End', { bold: true, width: 30, shading: 'f3f4f6' }),
                  createBorderedCell(formatDateTime(session.auditEndTime), { width: 70 }),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('Total Duration', { bold: true, width: 30, shading: 'f3f4f6' }),
                  createBorderedCell(formatDuration(session.totalDurationSeconds), { width: 70 }),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('Total Items Reviewed', { bold: true, width: 30, shading: 'f3f4f6' }),
                  createBorderedCell(String(session.totalItems), { width: 70 }),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('Average Time Per Item', { bold: true, width: 30, shading: 'f3f4f6' }),
                  createBorderedCell(formatDuration(Math.round(session.averageTimePerItemSeconds)), { width: 70 }),
                ],
              }),
            ],
          }),

          // Decision Summary
          new Paragraph({
            text: 'Decision Summary',
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createHeaderCell('Decision', 25),
                  createHeaderCell('Count', 25),
                  createHeaderCell('Percentage', 25),
                  createHeaderCell('Total Time', 25),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('Confirmed', { shading: 'dcfce7' }),
                  createBorderedCell(String(session.confirmedCount)),
                  createBorderedCell(`${Math.round((session.confirmedCount / session.totalItems) * 100)}%`),
                  createBorderedCell(formatTime(session.entries.filter(e => e.decision === 'confirmed').reduce((sum, e) => sum + e.reviewDurationSeconds, 0))),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('Edited', { shading: 'dbeafe' }),
                  createBorderedCell(String(session.editedCount)),
                  createBorderedCell(`${Math.round((session.editedCount / session.totalItems) * 100)}%`),
                  createBorderedCell(formatTime(session.entries.filter(e => e.decision === 'edited').reduce((sum, e) => sum + e.reviewDurationSeconds, 0))),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('Removed', { shading: 'fee2e2' }),
                  createBorderedCell(String(session.removedCount)),
                  createBorderedCell(`${Math.round((session.removedCount / session.totalItems) * 100)}%`),
                  createBorderedCell(formatTime(session.entries.filter(e => e.decision === 'removed').reduce((sum, e) => sum + e.reviewDurationSeconds, 0))),
                ],
              }),
              new TableRow({
                children: [
                  createBorderedCell('Skipped', { shading: 'f3f4f6' }),
                  createBorderedCell(String(session.skippedCount)),
                  createBorderedCell(`${Math.round((session.skippedCount / session.totalItems) * 100)}%`),
                  createBorderedCell(formatTime(session.entries.filter(e => e.decision === 'skipped').reduce((sum, e) => sum + e.reviewDurationSeconds, 0))),
                ],
              }),
            ],
          }),

          // Detailed Item Log
          new Paragraph({
            text: 'Detailed Audit Log',
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 400, after: 200 },
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  createHeaderCell('#', 5),
                  createHeaderCell('Domain', 12),
                  createHeaderCell('Term', 25),
                  createHeaderCell('Code', 15),
                  createHeaderCell('Decision', 12),
                  createHeaderCell('Time', 10),
                  createHeaderCell('Notes', 21),
                ],
              }),
              ...session.entries.map((entry, index) => {
                let notes = '';
                if (entry.decision === 'edited') {
                  notes = `Changed from "${entry.originalTerm}" (${entry.originalCode}) to "${entry.editedTerm}" (${entry.editedCode})`;
                }
                
                const decisionColors: Record<string, string> = {
                  confirmed: 'dcfce7',
                  edited: 'dbeafe',
                  removed: 'fee2e2',
                  skipped: 'f3f4f6',
                };

                return new TableRow({
                  children: [
                    createBorderedCell(String(index + 1)),
                    createBorderedCell(entry.item.domain),
                    createBorderedCell(entry.decision === 'edited' ? entry.editedTerm || entry.item.term : entry.item.term),
                    createBorderedCell(entry.decision === 'edited' ? entry.editedCode || entry.item.code : entry.item.code),
                    createBorderedCell(entry.decision.charAt(0).toUpperCase() + entry.decision.slice(1), { shading: decisionColors[entry.decision] }),
                    createBorderedCell(formatTime(entry.reviewDurationSeconds)),
                    createBorderedCell(notes || '—'),
                  ],
                });
              }),
            ],
          }),

          // Footer note
          new Paragraph({
            children: [
              new TextRun({
                text: 'This audit report was generated by Notewell AI and provides a record of SNOMED code verification for quality assurance and compliance purposes.',
                font: 'Fira Sans',
                size: 18,
                italics: true,
                color: '666666',
              }),
            ],
            spacing: { before: 400 },
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  
  // Generate filename
  const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '_');
  const filename = `SNOMED_Audit_${formatNhsNumber(session.patientNhsNumber).replace(/ /g, '_')}_${dateStr}.docx`;
  
  saveAs(blob, filename);
};
