import type { CleanRule } from "./transcriptCleaner";

export const NHS_DEFAULT_RULES: CleanRule[] = [
  { id:"nhs", find:"nhs", replace:"NHS" },
  { id:"cqc", find:"cqc", replace:"CQC" },
  { id:"qof", find:"qof", replace:"QOF" },
  { id:"pcn", find:"pcn", replace:"PCN" },
  { id:"ics", find:"ics", replace:"ICS" },
  { id:"icb", find:"icb", replace:"ICB" },
  { id:"arrs", find:"arrs", replace:"ARRS" },
  { id:"des", find:"des", replace:"DES" },
  { id:"lmc", find:"lmc", replace:"LMC" },
  { id:"emis", find:"emis", replace:"EMIS" },
  { id:"systmone", find:"systmone", replace:"SystmOne" },
  { id:"accurex_regex", find:"accu\\s*rx|accurx|accurex", replace:"Accurx", isRegex:true },
  { id:"nice", find:"nice", replace:"NICE" },
  { id:"bnf", find:"bnf", replace:"BNF" },
  { id:"mhra", find:"mhra", replace:"MHRA" },
  { id:"ukhsa", find:"ukhsa", replace:"UKHSA" },
  { id:"snomed", find:"snomed", replace:"SNOMED" },
  { id:"ckd", find:"ckd", replace:"CKD" },
  { id:"copd", find:"copd", replace:"COPD" },
  { id:"hba1c", find:"hba1c", replace:"HbA1c" },
  { id:"egfr", find:"egfr", replace:"eGFR" },
  { id:"bp", find:"bp", replace:"BP" },
  { id:"hca", find:"hca", replace:"HCA" },
  { id:"marac", find:"marac", replace:"MARAC" },
  { id:"ppg", find:"ppg", replace:"PPG" },
  { id:"pcn_spaced", find:"p c n", replace:"PCN", wordBoundary:false },
  { id:"arrs_spaced", find:"a r r s", replace:"ARRS", wordBoundary:false },
  { id:"des_spaced", find:"d e s", replace:"DES", wordBoundary:false },
  { id:"oaklane", find:"oak lane", replace:"Oak Lane" },
  { id:"metformin", find:"metformin", replace:"Metformin" },
  { id:"amlodipine", find:"amlodipine", replace:"Amlodipine" },
  { id:"sertraline", find:"sertraline", replace:"Sertraline" },
];