// Synthetic NHS meeting transcripts for pipeline testing.
//
// Each transcript is a single-block dialogue (no diarisation) — matching what
// Whisper/AssemblyAI/Deepgram produce after the Best-of-All merge. Content is
// deliberately mundane (workforce, finances, governance) to mirror the real
// production payload shape without any sensitive content.
//
// Sizes calibrated to exercise specific pipeline paths:
//   short  — ~500 words   → single-shot Sonnet, expect <30s
//   medium — ~3,000 words → single-shot Sonnet, expect <60s
//   long   — ~15,000 words → chunked path (>15k char threshold), expect <90s

export type TestSize = 'short' | 'medium' | 'long';

export interface TestFixture {
  size: TestSize;
  title: string;
  agenda: string;
  attendees: string[];
  durationMinutes: number;
  transcript: string;
}

const SHORT_TRANSCRIPT = `Right, shall we start? Thanks everyone for making it across at short notice. Quick stand-up today — three items on the agenda: workforce update, the QOF position, and AOB. We've got about twenty minutes so I'll keep us moving. Workforce first. Sarah, where are we with the receptionist post? Yes, we interviewed two candidates last Thursday. Both were strong, both had relevant experience in primary care reception. We've made an offer to the first candidate at the top of the band, awaiting acceptance. References should be back by Friday and DBS already in train. Good. And the salaried GP post? Still in advert on BMJ Careers and the NHS Jobs portal. We've had four applications so far, two we'd definitely like to interview, one borderline, one not suitable. Aiming for interview week commencing 18th May. I'd like Anita and James to be on the panel with me. Right. QOF position. James, where are we? We're at 78% of points achieved overall. The diabetes register review identified 23 patients overdue their HbA1c check — those have now been booked into the next four weeks of nurse clinics. CVD prevention is on track and we're confident of full points there. The frailty domain is the real concern, we're sitting at 61% which leaves 12% to recover before year-end. I'd like to bring in a paramedic-led home visit clinic for two weeks in June, focused entirely on the frailty cohort, doing comprehensive geriatric assessment, medication review, and falls risk assessment. Cost would be approximately £4,800 for the two weeks of agency cover. Worth it given the QOF income at stake — the recovered points would be worth roughly £18,000. AGREED. Action: James to draft a one-page proposal for the partners by Wednesday, costed and with expected recovery numbers, and once approved we'll book the paramedic agency through the usual framework. Sarah to liaise with the agency on availability for the first two weeks of June. AOB? One quick thing — the DPIA for the new patient messaging system is due back from the ICB information governance team. We're expecting it this week, no action required from this meeting but I'll circulate when received and flag any conditions they've attached. Second AOB — we've had a CQC notification of a routine inspection window between July and October. Not imminent but worth keeping in mind for the standing agenda from next month. Right, anything else? Lorraine? No, all good from me. Mel? Nothing to add. Good. Thanks all, see you next Monday at the same time, same place.`;

const MEDIUM_PARAGRAPHS = [
  `Right, let's get started. Thanks everyone for making it. Apologies received from Lorraine and Mel — they're both at the LMC event this afternoon. We've got a substantial agenda so I'll keep us moving. First item: the ARRS workforce position. As you know the 2026/27 funding allocation has come through and we've had a 3.3% uplift on the headline figure, but we need to factor in the employer NI changes and the pension contribution increase. Net effect for our practice is roughly £18,000 less spending power than last year despite the nominal uplift. James has done the modelling.`,
  `Yes, the headline ARRS allocation for our PCN is £487,000 for the year, which sounds like a lot, but once you net off the 14.38% employer pension and the 15% employer NI, plus the inflationary increase on existing post-holders, we're looking at funding for approximately 11.2 whole-time-equivalent ARRS roles. Last year we ran 12.0 WTE. So we're going to have to make a decision about which post we don't backfill when the current pharmacist's contract ends in August.`,
  `That's helpful, thank you James. The options as I see them are: don't replace the pharmacist when she leaves and accept the loss of capacity; replace her on a part-time basis at 0.6 WTE which is what the new ARRS budget will accommodate; or look at converting the role to a different ARRS-eligible profession where we might get more hours per pound, like a paramedic or social prescriber. Anita, what's your view from Brook Health Centre's perspective?`,
  `From our side, the pharmacist input has been transformative for the structured medication reviews and we've cleared a real backlog of polypharmacy patients who hadn't had a comprehensive review in years. If we lose that capacity, those reviews start sliding again. My preference would be to retain the pharmacist at part-time hours rather than substitute. The clinical risk of stopping SMRs altogether is significant.`,
  `I'd echo that, the SMR work has been valuable and we shouldn't lose it just because the pound stretches less far. But we also need to think about the unmet need — the frailty cohort is growing, our two-week wait referrals to the falls clinic are getting longer because there's no community alternative. A paramedic doing home visits could address that, and they're cheaper per hour than a pharmacist. It's not a like-for-like swap.`,
  `Both are valid. Can I propose we do this — we retain the pharmacist at 0.6 WTE, focused tightly on SMRs and high-risk polypharmacy, and we use the freed-up budget to bring in a paramedic at 0.4 WTE for the frailty home visits. Net effect is we maintain SMR capacity and add new home-visit capacity, even though the total ARRS WTE goes down slightly. James, can the numbers stretch to that?`,
  `Just about, yes. The pharmacist at 0.6 costs us approximately £33,000 inclusive of on-costs, and a paramedic at 0.4 is around £21,000, total £54,000 against an ARRS allocation of £58,000 for that pair of roles. So we have a £4,000 buffer for incidentals. It's tight but it works. I'd want to add a contingency line in the budget for sickness cover or if the paramedic agency rates go up mid-year.`,
  `AGREED. So action one: James to draft the revised ARRS staffing plan with these two roles, share with the partnership board for sign-off by 19th May. Action two: Sarah to give the current pharmacist formal notice of the change to part-time hours — Sarah, do you want to talk to her informally first? Yes, I'll have a conversation with her this week, then issue the variation in writing once the partners have signed off the plan. Good.`,
  `Moving on to QOF. James, where are we? We've got the Q4 position. We're tracking at 89.2% of total available points. The risk areas are the frailty domain at 71%, and the asthma review domain at 76%. Everything else is green or close to it. The frailty issue is largely about the home-visit capacity we just discussed, so that's hopefully addressed by the paramedic. The asthma situation is different — we're failing on annual reviews where the patient is over-12 and on a steroid inhaler. Of 340 eligible patients, 81 still need their review by 31st March.`,
  `Eighty-one is a lot in five weeks. Can we do an asthma clinic blitz? Yes, that's what I was going to propose. We could run two evening clinics — one in the first week of March, one in the second — each with two nurses, batch-recall the patients, do the spirometry where indicated, the inhaler technique check, the action plan review. We've done it before, it's effective. The pharmacist could attend and do an inhaler technique review on each patient — that's part of the structured medication review work anyway.`,
  `What's the cost? Two nurses for two evenings is approximately £600. Pharmacist time is already costed. So £600 to recover potentially £8,000 of QOF points. AGREED. Action three: Anita to organise the asthma clinic blitz, dates to be confirmed but in the first half of March. Recall letters out by 28th February.`,
  `Right, item three: the digital transformation programme. Malcolm has been leading on this — Malcolm, where are we with the Notewell rollout to the wider PCN? Thanks. So Notewell is now in steady use at three of the seven practices — Brook, Brackley, and Towcester. We've had positive feedback on time savings, particularly for partnership meetings and clinical governance meetings. Average time saving reported is around 90 minutes per meeting in note-taking and write-up. The MHRA Class I registration came through in March, which means we've got the regulatory cover to use it for clinical meetings as well.`,
  `For the four practices not yet using it — what's the barrier? Mostly capacity and IG concerns. We've now got a standardised DPIA template that's been ICB-approved, which removes most of the IG friction. Capacity is harder — the practice manager needs an hour or two to set up users and walk people through it. I've offered to do that on-site for any practice that wants it, but I need them to give me a date.`,
  `Can you write to the four practice managers this week with three proposed dates and ask them to pick one? Yes, I can do that. Action four: Malcolm to circulate three on-site setup dates to Springfield, Bugbrooke, Denton, and The Parks practice managers by end of this week. Targeting completion of all rollouts by end of June.`,
  `Item four: the ICB new models pilot. We've been asked whether we'd be interested in joining the ENN pilot — the East Northants Neighbourhood — alongside 3Sixty and PML. The ICB is offering up to £180,000 of pilot funding to test integrated neighbourhood working with social care, mental health and the voluntary sector. The ask of us would be to provide a clinical lead at 0.1 WTE for 18 months, plus engagement at the practice partner level. It's a significant commitment but it positions us well for the post-2027 contract reforms.`,
  `What's the catch? The catch is the governance overhead. There's a programme board, a clinical reference group, a steering group, and quarterly reporting to the ICB. It would absorb a meaningful chunk of the clinical lead's time on top of the 0.1 WTE — probably another half-day a month in meetings. And the funding doesn't cover that overhead. So in practice we'd be subsidising the pilot from our own resources.`,
  `Hmm. Can we say yes in principle but ask for protected time for the governance, not just the clinical lead role? Yes, I think we should — the ICB is asking for partners and they need us, so there's room to negotiate. Let me draft a response that says yes in principle, conditional on the funding being uplifted to cover the governance overhead, and we'll see what comes back.`,
  `AGREED. Action five: Sarah to draft the response to the ICB on the ENN pilot, conditional acceptance with funding uplift requested for governance overhead. Circulate to partners for sign-off before submission. Item five: any other business. Anything? Yes, just one — the patient survey results came back and we're at 88% would-recommend, which is up from 84% last year. The free text comments highlighted reception waiting times and difficulty getting through on the phone. Both of which we know about.`,
  `Worth noting we've still got two receptionist vacancies. The phone line issue is largely the same problem — not enough staff to answer the volume of calls. The new candidate we've offered should help once they start. We should look at whether the cloud-based phone system the ICB's been talking about would actually help us. Action six: Sarah to look into the cloud phone system pilot, report back at next month's meeting. Anything else? No? Right, thanks all. Next meeting same time, Wednesday 11th June.`,
];

const LONG_PARAGRAPHS = [
  // === OPENING (~200 words) ===
  `Right, shall we get started? It's just gone ten past, I think we've got everyone we're going to get. Apologies received from Lorraine — she's at the LMC executive meeting this morning — and from Mel who's covering an extra clinic at Brackley because their salaried GP's off sick. Anita's joining by Teams, can you hear us okay Anita? Yes, fine, hi everyone. Good. Right, the agenda's in your packs, eight items plus AOB, I want to keep this to an hour so I'll be moving us along. First item is the Q4 finance position, then ARRS workforce planning for 2026/27, then the QOF recovery plan, then the digital transformation update, then estates including the boiler decision we deferred from last month, then clinical governance and complaints, then the ICB ENN pilot decision, then the patient survey results, then AOB which I think Marcus has flagged something about the LMC update. Before we start, can I just confirm — Teams recording is on, isn't it Sarah? Yes, recording started at 10:08 and Notewell's running for the minutes. Good. James, take us through finance.`,

  // === FINANCE (~1,200 words) ===
  `Thanks. So the headline position at end of Q3 is that we're approximately £14,000 down on budget across the partnership. The main drivers are locum costs running 22% above forecast — that's the salaried GP sickness we've had over the winter, plus Dr Patel's maternity leave starting earlier than planned by about three weeks, which meant we couldn't recruit the maternity cover lead-in we'd budgeted for. Plus utility costs which are up 18% on last year despite the supposed cap, mostly because we've been running the air handling units harder during the respiratory virus surge from late October through to mid-January.`,

  `Against those negatives we've had three positive variances. The dispensary income is up 11% on forecast, mostly because of the GLP-1 dispensing volume increasing through the autumn — we've gone from about 240 GLP-1 prescriptions a month at start of year to nearly 400 a month now, which is a substantial revenue uplift even at the modest dispensing margin. QOF achievement payments are tracking ahead at 89.2% versus our budgeted 86%, that's worth roughly £6,000 against budget if we hold that level. And the enhanced services income from the cardiology shared-care arrangement is running at about £3,200 per quarter rather than the £2,500 we'd planned, because the volume of patients we're managing on shared-care has grown faster than the contract assumed. So net £14k down, mostly cost-side, partially mitigated by income upside.`,

  `Cash position is fine, we've got just over four months of operating costs in the reserves account, which is exactly where the partnership agreement says we want to be heading into the year-end purchase cycle. The accountant's draft Q3 report is in your packs — I'd particularly draw your attention to page four, the dispensing margin analysis. We're seeing margin compression on the high-volume generics, which is sector-wide and well documented in the Pharmaceutical Journal piece I circulated last month. But our dispensary's adjusted by leaning more heavily into the specials and aseptic compounding work for the care homes, which has higher margins — about 16% gross margin versus 4% on high-volume generics. Long-term that's not a sustainable strategy because the specials volume's capped at what the local care homes need, but for this year it's offsetting roughly half the generic margin loss.`,

  `We need to think about whether we want to invest in the robotic dispensing unit that I mentioned at the September meeting — the BD Rowa Vmax, capital cost approximately £45,000 installed, payback period about 28 months on current volumes through reduced pharmacy technician hours. That's a partnership-level capital decision rather than something for today, but I'd suggest we put it on the May agenda with a proper business case. The reason it's relevant now is that BD have offered an end-of-financial-year discount of £6,000 if we commit by end of May, which would cut the payback to 24 months. Worth thinking about.`,

  `Any questions on finance before we move on? Yes, on the locum costs — are we still using the same agency or have we moved providers? We're still mostly with Bridgewater because the rates are competitive and we've got a good relationship with their consultant for the bookings, but I have brought in two locum sessions through ProDoc this quarter when Bridgewater couldn't fill on short notice. ProDoc's about 12% more expensive but they've never failed to fill, so for the urgent cover I think it's worth the premium. They're also better on the IR35 paperwork which has been a faff with Bridgewater's newer GPs. Right. And on the dispensary margin — when you say sector-wide pressure, is that from the new framework agreement? Partly, and partly the manufacturer-level consolidation, particularly on metformin and atorvastatin where we've gone from four suppliers to two over eighteen months. Less competitive tendering, higher unit prices to us. Okay, thanks.`,

  `One more on finance — the year-end accounts. When are we going to get the preliminary figures from the accountant? She's promised end of April for the draft, with the audit completing by end of May. That would give us the partnership tax meeting in early June, which fits with the partnership agreement timeline. The slight wrinkle is the new partner buy-in calculation for Dr Chen joining in July — the accountant needs the year-end goodwill valuation before she can finalise the buy-in number. So if accounts slip, the buy-in slips, which has implications for Dr Chen's contractual start. I've flagged this with the accountant and she's confident on the timeline. Right, item two, ARRS workforce planning. Sarah?`,

  // === ARRS WORKFORCE (~1,500 words) ===
  `Thanks. So we've had the indicative ARRS allocation for 2026/27 from the ICB — £487,000 against £473,000 last year, headline 3.0% uplift. But the underlying picture's worse than that because of two things: the employer NI increase from April adds 1.2% to all our existing post-holders, and the NHS pension employer contribution went up to 23.7% in the last revision which adds another 1.4%. So in real terms our spending power is actually about £18,000 lower than 2025/26, despite the headline going up. That reduces the number of WTEs we can fund from approximately 12.0 down to 11.2.`,

  `Just to put that in context — the BMA's modelling suggests the average PCN is losing about £20,000 of real ARRS spending power this year, so we're broadly in line with the sector. Some PCNs are reporting larger losses because they're carrying more high-band post-holders where the employer NI bites harder. Our skew towards the lower bands — physician associates, social prescribers, care coordinators — actually helps us slightly here. So we're not in a worse position than peers, but we are in a worse position than we were a year ago and that has to translate into workforce decisions.`,

  `The decision we need to take today is what to do about the pharmacist post when Aisha's contract ends in August. As a reminder, she's been doing structured medication reviews three days a week since June 2024, and she's worked through about 380 high-risk polypharmacy patients in that time. The reviews have generated documented medication changes for 71% of patients reviewed, and we estimate about £14,000 of annual prescribing budget savings from the deprescribing alone. Plus there's the clinical risk reduction which is harder to monetise but obviously real — roughly 40 patients have had QT-prolonging combinations identified and corrected, six patients have come off long-term PPIs that weren't indicated, and we've stopped about a dozen anticholinergic combinations in elderly patients with falls history.`,

  `So the question is, do we replace her at full WTE, do we replace her at part-time, do we substitute for a different ARRS-eligible role, or do we not replace at all. Each of those has implications. Full replacement at 0.6 WTE costs us about £33,000 inclusive of on-costs, given the band 8a benchmark for a clinical pharmacist with three years post-registration experience. We could substitute for a paramedic at 0.4 WTE for £21,000, which would address the home-visit capacity issue we've been talking about for the frailty cohort — current waiting time for a routine GP home visit is averaging eight days which is too long and exposes us if anything happens. Or we could do both at reduced WTE — pharmacist at 0.4 plus paramedic at 0.4 — for combined £42,000. That keeps both capacities going but at thinner cover than we'd ideally want.`,

  `My recommendation, and I've sense-checked this with Aisha who's amenable to the change, is option two — pharmacist at 0.6 WTE focused entirely on SMRs, plus paramedic at 0.4 WTE for frailty home visits. Total £54,000 against £58,000 of available ARRS allocation for these two roles, leaving £4,000 contingency for sickness cover or agency rate increases. That's tight but workable. Anita's view on the paramedic — you've worked with the Cambridgeshire model, do you think 0.4 WTE is enough to make a difference on the home-visit waiting times?`,

  `From the Cambridgeshire data, a 0.4 WTE paramedic doing two days a week of home visits handles roughly 35-40 patient contacts a fortnight at the level we'd want — full assessment plus medication review plus social referral where indicated. Our current home-visit demand is about 60 patient contacts a fortnight across all GPs combined, so a 0.4 WTE paramedic doing the routine frailty visits frees up GP time for the genuinely complex stuff. I think it's the right level. Above 0.4 you start hitting the law of diminishing returns because the case mix shifts toward stuff that needs GP input anyway. The other thing worth flagging is that the paramedic role qualifies under the ARRS prescribing extension, so once they've done their independent prescriber qualification they can issue scripts directly which is another efficiency win.`,

  `Question from Roger — what's the contractual structure? Are we employing directly or going through an agency framework? The proposal is direct employment, fixed-term 12-month contract initially with the option to convert to permanent at year-end based on performance and continued ARRS funding. That mirrors how we've structured the pharmacist post. Agency models for paramedics are available but cost about 35% more all-in once you account for the agency margin. Direct employment also gets us better engagement and continuity. Risk is if they leave we have to recruit again, but recruitment for paramedics has been getting easier because of the workforce growth in the College of Paramedics — there are more qualified paramedics out there looking for primary care roles than there were three years ago.`,

  `Right, are we agreed on option two then? Yes from me. Yes. Yes. Yes from Anita on Teams. AGREED — pharmacist 0.6 WTE for SMRs, paramedic 0.4 WTE for frailty home visits, total £54k against £58k allocation, action James to draft the revised ARRS staffing plan for partnership board sign-off by 19th May, and Sarah to draft the paramedic job description and start informal advertising via the College of Paramedics network with a target start date of October to allow handover with Aisha. Sarah, you'll also need to have the conversation with Aisha about the change to part-time — can you do that this week? Yes, I've got her booked in for Wednesday afternoon. Good.`,

  // === QOF RECOVERY (~1,300 words) ===
  `Item three, QOF position. We're at 89.2% of available points end of Q3 which is broadly where we expected to be. The two amber domains are frailty at 71% and asthma reviews at 76%, every other domain is green or close to it. Frailty I think is sorted by what we've just agreed on the paramedic — the routine home visits are exactly the workflow that picks up the falls assessments and the comprehensive geriatric assessments that are missing from our QOF achievement. So I'm confident we'll be back to green on frailty by end of Q4 once the paramedic's running, even with a late October start, because the high-impact reviews can be front-loaded.`,

  `The asthma issue is different and more time-pressured. We've got 81 patients aged over 12 on a steroid inhaler who haven't had their annual review yet, against a denominator of 340. To recover those points by 31st March we need to see them all in the next five weeks, which is about 16 reviews a week on top of normal nurse capacity. Two options I've been considering — extend nurse hours through evening clinics for the next four weeks, or run a Saturday clinic blitz in early March. Cost-wise the evening clinics are about £600 in nurse overtime for two evenings a week over four weeks at the OOH rate. The Saturday clinic is about £450 for one Saturday of nurse time, but you have to pay the receptionist and the cleaner overtime too so it's closer to £550 in real terms.`,

  `My preference would be the evening clinics because we know from the receptionist we just recruited that demand for evening appointments is high and we'd genuinely fill the slots. Saturday's a gamble — patients say they want it but DNA rates on Saturday clinics historically run at about 25% which kills the cost case. With evening clinics our DNA rate's typically 11-13% which is much better. Anita, the pharmacist could do the inhaler technique reviews in tandem couldn't she? Yes, that would be ideal. We could pair each nurse appointment with a 10-minute pharmacist slot for the technique review, which both gets us the QOF points and improves outcomes. The pharmacist time is already costed in her existing hours so no incremental spend, and she can do the technique reviews remotely via video for the patients who'd prefer that, which actually works well for inhaler technique because you can see exactly how they're using the device.`,

  `One question — what about the patients who don't engage? In a typical recall round we get about 70% engagement on first invitation, 85% by second invitation. So out of 81 patients we might end up with 12-15 who don't show even after two recalls. The QOF rules let us code those as exception-reported if we've made three documented attempts to engage them, so we wouldn't lose the points on those — it's the patients who do engage but we can't fit in within the deadline that we'd lose. With 16 reviews a week and four weeks plus a buffer week, we should be able to see 70-80 patients which gets us most of the way there.`,

  `Two specific patient cohorts I want to flag. Cohort one is the housebound patients on inhalers — there are about eight of those. The paramedic could pick those up as part of the home visits once she's started, but if we're doing the asthma blitz before the paramedic starts we'd need a different solution. I think the right answer is to phone-review those eight patients in the meantime and code as appropriate, then do the in-person review at next home visit. Cohort two is the four patients who've been historically difficult to engage — repeated DNAs, declined recalls. I'm going to ask the safeguarding nurse to review those before we do anything else, because two of them have learning disability flags and one has mental health complexity, so a different approach may be needed.`,

  `Right, AGREED on the asthma plan — evening clinics for four weeks from late February, with pharmacist providing inhaler technique reviews in parallel, recall letters out by Friday 28th February, target completion by end of March. Action Anita to draft the recall list and arrange staffing, action Aisha to coordinate the technique review slots with the nurse rota. Anything else on QOF? One thing — I've had a query from the LIS team about whether we want to engage with the new respiratory enhanced service that's been advertised. It's worth about £4,500 to a practice our size if we hit the activity targets, which are similar to QOF asthma but with some additional spirometry quality measures. Worth taking up?`,

  `Let me look at the spec and bring it back to next month's meeting. Initial sense is yes if the activity overlaps with what we're already doing for QOF, but I want to check the data sharing requirements before we commit because the last enhanced service we signed up to had some onerous data extract conditions. Right, action James to review the respiratory enhanced service spec and bring a recommendation to the June meeting. Move on.`,

  // === DIGITAL TRANSFORMATION (~1,000 words) ===
  `Item four, digital. Malcolm, where are we with the practice manager rollout. Thanks. So Notewell's now in steady state at three of the seven NRES practices — Brook Health Centre, Brackley, and Towcester. Average reported time saving from the practice managers is 90 minutes per meeting in note-taking and write-up, which over a typical month works out at about 8-10 hours per practice manager. Feedback's been positive on the user experience, the main grumbles are around the Word document formatting which we've improved twice and is still not perfect, and the email rendering on long meetings which has a known bug we're working on this week.`,

  `MHRA Class I registration came through in March, so we're now formally regulated as a medical device which means we can use Notewell for clinical governance meetings, complaints reviews, and significant event analyses where previously we were using it under a quality-improvement-only caveat. That removes a real constraint and the four practices that were holding back on clinical use can now move forward. The MHRA registration was a nine-month project end-to-end and it's been validated against the IEC 62304 software lifecycle standard, which is the same standard the larger NHS digital products are validated against. That's worth knowing because some of the more risk-averse practice managers have asked for evidence of regulatory rigour and we can now point to the MHRA certificate plus the IEC 62304 validation.`,

  `The four practices that aren't yet live — Springfield, Bugbrooke, Denton, and The Parks — the barriers are practice manager capacity for the on-site setup session and information governance concerns about the data flow. The IG concerns I think we've now resolved with the standardised DPIA template that the ICB approved last month. That template covers the data flow from practice through Supabase storage to the various AI providers, the retention periods, the deletion rights, the data subject access response, and the breach notification process. It's been signed off as acceptable by the ICB IG team for use across all NRES practices, so individual practices don't need to repeat the assessment work.`,

  `Capacity is the bigger issue. Each on-site setup session is about two hours where I work directly with the practice manager and one nurse champion, so it's not a huge time ask, but four practice managers all already running flat out can struggle to find two hours. My proposal is that I offer each of the four practices three potential dates over the next six weeks for an on-site setup session, and they pick whichever works. End of June 2026 is realistic for full PCN coverage if everyone takes me up on dates. If anyone slips, we can run an additional cohort in July.`,

  `On the wider digital agenda — three other things to flag briefly. First, the new patient messaging system DPIA is back from the ICB IG team with two minor conditions which we can comply with. Conditions are around the audit log retention period — they want six years rather than three — and around the role-based access controls for the messaging archive. Both fine, we can implement before go-live. Targeting first patient messages by end of May. Second, the EMIS upgrade scheduled for May bank holiday weekend will require us to be on-call across the partnership for any post-upgrade issues — I've worked with the EMIS team to schedule this for the long weekend so we have minimum patient impact. Third, the cyber-security audit from the ICB came back with three medium-priority findings which are all addressable through training and process changes — I'll bring the action plan to the June meeting.`,

  `Question from James — what's the cumulative cost of the digital programme this year? Notewell itself is delivered free as far as the partnership's concerned because Malcolm runs it as a not-for-profit at PCN Services Ltd. The patient messaging system is £2,400 per practice annual licence which we've budgeted. The EMIS costs are unchanged year on year. So the incremental digital cost across all of this is mostly just licensing, maybe £18,000 across the seven practices. The bigger cost is internal time which doesn't show up in the cash budget but is real — Malcolm probably spends 40% of his working week on Notewell-related matters across all the practices, which is unfunded from a partnership cash standpoint but creating significant value through the time savings.`,

  `Right, Action Malcolm to write to the four remaining practice managers this week with proposed setup dates, target full PCN rollout by end of June. Move on. Item five, estates.`,

  // === ESTATES (~900 words) ===
  `So the roof leak we identified in November above the second-floor consulting rooms — the contractor's been back for the third time and I think we've finally fixed it, no leakage during the heavy rain last week which is the first time since November we can say that. Cost has come in at £4,200 against the £3,500 quoted, which is annoying but within tolerance. The reason for the cost overrun was that on the second visit they discovered the leak was actually coming from the flashing around the AHU mounting plate rather than the roof membrane itself, which required additional work that wasn't in the original scope. I've negotiated with the contractor to absorb the extra labour but we've paid for the materials.`,

  `The bigger estates issue is the boiler. The current boiler is 19 years old, well past its expected life, and we've had three breakdowns in the last 12 months. Most recent breakdown was during the cold snap in early February which meant we ran without heating for two days before the engineer could get out — patient feedback was understandably negative. The estates surveyor's view is we should replace this year rather than next because the failure risk is increasing and a mid-winter failure is genuinely dangerous for patient and staff welfare.`,

  `Replacement cost is approximately £18,000 for a like-for-like replacement, or £24,000 for a heat pump system that would qualify for the public sector decarbonisation scheme grant of up to 50%. So heat pump net cost might be £12,000-£14,000 depending on the grant outcome, which would be cheaper than like-for-like as well as having lower running costs going forward. The heat pump option also future-proofs us for the eventual end of natural gas heating in healthcare premises, which the NHS Net Zero programme is targeting for 2035 at the latest.`,

  `The decision point is that the heat pump option needs us to commit by end of June for the grant application window. Otherwise we're stuck with replacing like-for-like later in the year when the boiler eventually fails. There's also a survey and design cost of about £2,000 for the heat pump option that's not refundable if we don't proceed — that covers the heat-loss calculation and the system design which we'd need anyway for the grant application. My recommendation is we apply for the heat pump grant — even if it's not approved we can still go like-for-like as a fallback. Risk is just the £2,000 of survey and design work that's not refundable if we don't proceed.`,

  `Question from Roger — what's the capacity uplift, do we need a bigger boiler? The heat-loss calculation will tell us properly but the surveyor's preliminary view is that current heating capacity is more than we actually need — the building's been running with 30% spare boiler capacity for years because the original spec was conservative. So we'd actually be installing a smaller heat pump, which is part of why the grant calculation works. The hot water side is separate — we've got a small electric heater for the staff kitchen and the patient toilets which is already electric, so no change needed there.`,

  `Question from Marcus — how disruptive is the installation? Heat pump installation is roughly five working days with the heating off, so we'd schedule it for August when we can run reduced clinics anyway and the weather's mild enough for the hot water to be the only real issue. Like-for-like boiler is more like two days. So it's longer but plannable. Anyone object to applying for the heat pump? No. AGREED — apply for the heat pump replacement under the decarbonisation scheme, target decision by end of June. Action James to instruct the surveyor and submit the application by end of May.`,

  `One more estates item — the pharmacy storage room temperature monitoring. We've had two excursions this quarter where the room temperature went above 25°C, both during the heatwave week in late June. Neither caused stock loss because we caught it within the action time, but it's a flag for the inspectors and we should address it. I've got a quote for a small split-unit air conditioning system specifically for the pharmacy storage at £2,800 installed. Worth doing? Yes I think so, the risk of a stock-loss event is real and the cost of replacing dispensary stock if we have to dispose of it would be much higher than £2,800. AGREED — install pharmacy storage AC, action James to instruct.`,

  // === CLINICAL GOVERNANCE (~1,000 words) ===
  `Item six, clinical governance and complaints. Two complaints to report this quarter, both already responded to within the 25-working-day standard. Complaint A was about a delayed referral to dermatology — the patient had been waiting six weeks before being told the referral hadn't actually been sent due to a processing error. The error was that the referral letter was generated but not transmitted because the e-Referral system had timed out and the receptionist who was processing it didn't realise. We've apologised, expedited the referral, and updated our referral tracking process to flag any referral that hasn't been acknowledged by the receiving service within 14 days. The patient's accepted the response and isn't pursuing further. The process change has been written up as a system learning event and shared with the wider team.`,

  `Complaint B was about communication around the death of a family member — the family felt they hadn't been kept informed during the patient's terminal admission. This is more difficult because the substantive care happened in hospital, not with us, but we did have a role in the discharge planning and there were some gaps in our documentation. Specifically, the gold-standards-framework conversation we'd had with the patient before admission wasn't reflected in the hospital handover, and the family were left feeling that no advance care planning had taken place when in fact substantial planning had happened. We've responded acknowledging the gaps, offered a meeting with the family which they've accepted for next week, and the partners are doing a structured significant event analysis on the documentation issues. I'll bring the SEA outcomes to the next meeting along with any process changes.`,

  `One significant event to report from this quarter — a near-miss on a high-dose methotrexate prescription where the dosing was correct but the directions said weekly when the patient interpreted them as daily. The patient came in for the first dispensing and queried "should I really be taking these every day?" with the pharmacy assistant who escalated to the pharmacist who caught the issue. Caught by the pharmacy on dispensing, no harm came to the patient. We've added a hard-stop in the EMIS prompt for methotrexate scripts requiring explicit confirmation of weekly dosing, and we've added it as a standing item in the next clinical meeting for discussion with the wider team. Worth flagging that this is exactly the kind of issue the structured medication review process catches before it becomes a near-miss — it's an argument for keeping the pharmacist capacity which we've just AGREED on item two.`,

  `Three audits completed since the last meeting. First, the antibiotic prescribing audit against the local antimicrobial stewardship guidelines. We're at 84% concordance versus a target of 90% — main areas for improvement are the duration of urinary tract infection courses, where we're prescribing 7-day courses for some patients who should be on 3-day courses per the latest guidelines, and the choice of antibiotic for community-acquired pneumonia where we've been slow to switch from amoxicillin to doxycycline as first-line per the December guideline update. Action plan is a clinical meeting in May to walk through the updated guidelines and a re-audit in September.`,

  `Second audit, controlled drug prescribing. We're 100% compliant with the legal requirements which is the bare minimum, and 94% compliant with the local good practice guidelines around frequency of patient review. The 6% gap is mostly long-term opioid patients who haven't had a structured medication review in the last six months — we've addressed this by adding a recall flag for any patient on long-term opioids who hasn't had a review in nine months, which is the threshold the GMC suggests. Third audit, the diabetes annual review process. We're at 91% completion which is fine, but the quality of the foot examinations is patchy — some clinicians are documenting full neuro-vascular examination, others are documenting "feet checked" only. Action plan is a teaching session for nurses and GPs on what a full diabetic foot examination should include and how to document it.`,

  `Anything else on clinical governance? Yes one thing — the new safeguarding lead handover. Dr Chen will be taking over as safeguarding lead from Dr Williams when she retires in September. We need to make sure the handover is robust because there are six current cases that need continuity. Dr Williams has agreed to do a structured handover meeting with Dr Chen in August and to be available for advice for three months after her retirement. The named-doctor for safeguarding role will move to Dr Chen formally on 1st October. Note that this needs reflecting in the safeguarding policy update which is due for review anyway. Action Sarah to update the safeguarding policy with the new role assignments and circulate for partner sign-off by end of September.`,

  // === ENN PILOT (~1,000 words) ===
  `Item seven, the ENN pilot. So the ICB has now formally invited us to join the East Northants Neighbourhood pilot alongside 3Sixty and PML, with up to £180,000 of funding over 18 months. The pilot's testing integrated neighbourhood working — primary care, social care, mental health, voluntary sector — with the explicit aim of informing the post-2027 contract reforms. The strategic case for joining is strong: we'd be one of two innovator sites in the region, we'd have direct ICB engagement on shaping the operating model, and we'd be positioned for whatever funding mechanisms come out of the contract reform.`,

  `The pilot has four workstreams. Workstream one is the integrated frailty pathway — a single referral route for any patient over 75 with two or more long-term conditions, leading to a multi-disciplinary review combining primary care, community nursing, social care, and where indicated mental health. Workstream two is the social prescribing expansion, integrating the existing PCN social prescribers with the council's connected communities team and the voluntary sector providers. Workstream three is the mental health integration, putting a CMHT practitioner into primary care for one day a week per practice. Workstream four is the data and evaluation strand, which is where we'd be doing structured outcome measurement against a defined set of metrics agreed with the ICB.`,

  `The ask of us is significant though. A clinical lead at 0.1 WTE for the 18-month duration — that's about £14,000 of GP session time which is covered by the funding. Plus partner-level engagement at the strategic governance meetings, which the funding does cover at the protected-time rate of £180 per session. What the funding doesn't cover is the practice-manager-level operational engagement — the programme board, the clinical reference group, the steering group, the quarterly ICB reporting, the workstream-level coordination calls. We've estimated that's an extra half-day a month of practice manager time across Sarah and the other practice managers, so for the partnership it's probably a £4,000-£5,000 unfunded subsidy over the 18 months.`,

  `The other consideration is that the data and evaluation strand will require us to share performance data with the ICB at a level of granularity we haven't done before. Specifically, anonymous patient-level outcome data linked across primary care, social care, and mental health touchpoints. The IG framework for that hasn't been finalised yet and there's some concern from the BMA centrally that pilots like this are being used to establish data-sharing patterns that will then be normalised across the contract reform. So we'd want clear contractual protection on the data use, including a sunset clause on data sharing if we withdraw from the pilot.`,

  `Two views in the partners' WhatsApp from earlier this week. Marcus and Liz are keen to accept on the strategic case — they make the point that the post-2027 contract is going to reshape primary care fundamentally and being inside the tent influencing it is better than being outside it being shaped by it. Roger and I are more cautious about the unfunded element and the data sharing — not because the absolute number's huge, but because the ICB has form for asking for more once you're in, and the data sharing precedent matters.`,

  `My suggestion is we accept in principle but condition the acceptance on the ICB uplifting the funding to cover the governance overhead, AND on the data sharing IG framework being finalised and acceptable to us before we sign the participation agreement. That gives them a chance to respond on both points, and if they don't move on either we can either accept on their original terms or withdraw with our reasoning documented. Anyone object to that approach? No. AGREED — conditional acceptance subject to ICB funding uplift for governance overhead AND finalisation of data sharing IG framework. Action Sarah to draft the response, circulate to partners for sign-off before submission, and crucially to copy in the LMC for their information because this might set a precedent for other PCNs.`,

  // === PATIENT SURVEY + AOB (~700 words) ===
  `Item eight, patient survey. The annual GP patient survey results came back last week. Headline is 88% would-recommend, up from 84% last year, which is the best score we've had since 2019. National median is 72% so we're well above average. Local PCN average is 79% so we're best-in-PCN as well. The free-text comments are the more useful bit — three themes coming through. First, telephone access is the main negative — patients say it's hard to get through, especially Monday mornings. Second, reception waiting times — patients waiting 8-10 minutes to be checked in is too long. Third, continuity of care — some longstanding patients note that they don't see the same GP twice running, which is partly the salaried GP turnover we've had this year.`,

  `On telephone access, the cloud-based phone system pilot the ICB's been running might help — it's got intelligent call routing and call-back functionality that could reduce the Monday morning queue. The system the ICB's piloting is the Babblevoice-Plus product which has a NHS-specific module. I'd suggest Sarah finds out the current pilot status and whether we could join. On reception waiting times, the receptionist we've recruited starting next month should help materially because we'll be running with three on the desk on Mondays rather than two. We've also re-engineered the check-in flow so that any patient who's used the self-service kiosk doesn't need to engage with reception at all unless they have an issue. On continuity, that's harder — we can put in soft prompts in the booking system to encourage continuity, but ultimately if patients want a GP available next-day they're going to take whoever's on. We should monitor and re-survey but I don't think there's a quick fix.`,

  `One specific positive in the survey worth noting — the 'felt heard and respected' question scored 94% strongly agree, which is up from 89% last year and well above the national average of 76%. That's a credit to the whole clinical team and reflects the consultation training that we did in 2024. Patients clearly notice the difference when clinicians are properly trained in active listening and shared decision making. Worth congratulating the team on at the next clinical meeting. Action Sarah to investigate the cloud phone system pilot status and report back in June.`,

  `Right, AOB. Marcus, you flagged something about the LMC? Yes, two things. First, the LMC AGM is on the 15th of June and they're looking for nominations for the executive committee — a partner from one of the seven NRES practices would be welcome. Worth thinking about whether anyone wants to put themselves forward. Second, the LMC has just published their template for the new partnership agreement which incorporates the changes required by the 2026/27 GP contract. Worth us reviewing our partnership agreement against the template — there are some changes around partnership exit and goodwill valuation that have changed materially. I'll circulate the template by email this week. Anything else? One quick thing, the CQC inspection window is now formally July to October. Worth us doing a self-assessment in May. I'll bring a draft self-assessment template to the next meeting.`,

  `Anything else? No? Right, thanks everyone. Next meeting Wednesday 11th June, same time, same place. Travel safely. Anita, you can hop off Teams whenever. Thanks all.`,
];

const SHORT_FIXTURE: TestFixture = {
  size: 'short',
  title: 'Pipeline Test (Short) — Weekly Stand-up',
  agenda: 'Workforce update; QOF position; AOB',
  attendees: ['Sarah Manager', 'James Finance', 'Anita Practice'],
  durationMinutes: 8,
  transcript: SHORT_TRANSCRIPT,
};

const MEDIUM_FIXTURE: TestFixture = {
  size: 'medium',
  title: 'Pipeline Test (Medium) — Monthly Partnership Meeting',
  agenda: 'ARRS workforce 2026/27; QOF Q4 position; Notewell rollout; ENN pilot; Patient survey',
  attendees: ['Sarah Manager', 'James Finance', 'Anita Practice', 'Malcolm Digital'],
  durationMinutes: 45,
  transcript: MEDIUM_PARAGRAPHS.join('\n\n'),
};

const LONG_FIXTURE: TestFixture = {
  size: 'long',
  title: 'Pipeline Test (Long) — PCN Partnership Meeting',
  agenda: 'Q4 finance position; ARRS workforce 2026/27; QOF recovery (frailty + asthma); Notewell rollout; estates incl. boiler decision; clinical governance & complaints; ENN pilot decision; patient survey; AOB',
  attendees: [
    'Sarah (Practice Manager)',
    'James (Finance/Modelling)',
    'Anita (Brook Health Centre, joining via Teams)',
    'Malcolm (Digital Transformation Lead)',
    'Marcus (Partner)',
    'Roger (Partner)',
    'Lorraine (Apologies — at LMC executive)',
    'Mel (Apologies — covering Brackley clinic)',
  ],
  durationMinutes: 41,
  transcript: LONG_PARAGRAPHS.join('\n\n'),
};

export const TEST_FIXTURES: Record<TestSize, TestFixture> = {
  short: SHORT_FIXTURE,
  medium: MEDIUM_FIXTURE,
  long: LONG_FIXTURE,
};

export function getFixture(size: TestSize): TestFixture {
  return TEST_FIXTURES[size];
}
