// Synthetic NHS meeting transcripts for pipeline testing.
//
// Each transcript is a single-block dialogue (no diarisation) — matching what
// Whisper/AssemblyAI/Deepgram produce after the Best-of-All merge. Content is
// deliberately mundane (workforce, finances, governance) to mirror the real
// production payload shape without any sensitive content.
//
// Sizes calibrated to exercise specific pipeline paths:
//   short  — ~500 words   → single-shot Sonnet, expect <30s
//   medium — ~3,000 words → single-shot Sonnet, expect <60s
//   long   — ~15,000 words → chunked path (>15k char threshold), expect <90s

export type TestSize = 'short' | 'medium' | 'long';

export interface TestFixture {
  size: TestSize;
  title: string;
  agenda: string;
  attendees: string[];
  durationMinutes: number;
  transcript: string;
}

const SHORT_TRANSCRIPT = `Right, shall we start? Thanks everyone for making it across at short notice. Quick stand-up today — three items on the agenda: workforce update, the QOF position, and AOB. We've got about twenty minutes so I'll keep us moving. Workforce first. Sarah, where are we with the receptionist post? Yes, we interviewed two candidates last Thursday. Both were strong, both had relevant experience in primary care reception. We've made an offer to the first candidate at the top of the band, awaiting acceptance. References should be back by Friday and DBS already in train. Good. And the salaried GP post? Still in advert on BMJ Careers and the NHS Jobs portal. We've had four applications so far, two we'd definitely like to interview, one borderline, one not suitable. Aiming for interview week commencing 18th May. I'd like Anita and James to be on the panel with me. Right. QOF position. James, where are we? We're at 78% of points achieved overall. The diabetes register review identified 23 patients overdue their HbA1c check — those have now been booked into the next four weeks of nurse clinics. CVD prevention is on track and we're confident of full points there. The frailty domain is the real concern, we're sitting at 61% which leaves 12% to recover before year-end. I'd like to bring in a paramedic-led home visit clinic for two weeks in June, focused entirely on the frailty cohort, doing comprehensive geriatric assessment, medication review, and falls risk assessment. Cost would be approximately £4,800 for the two weeks of agency cover. Worth it given the QOF income at stake — the recovered points would be worth roughly £18,000. AGREED. Action: James to draft a one-page proposal for the partners by Wednesday, costed and with expected recovery numbers, and once approved we'll book the paramedic agency through the usual framework. Sarah to liaise with the agency on availability for the first two weeks of June. AOB? One quick thing — the DPIA for the new patient messaging system is due back from the ICB information governance team. We're expecting it this week, no action required from this meeting but I'll circulate when received and flag any conditions they've attached. Second AOB — we've had a CQC notification of a routine inspection window between July and October. Not imminent but worth keeping in mind for the standing agenda from next month. Right, anything else? Lorraine? No, all good from me. Mel? Nothing to add. Good. Thanks all, see you next Monday at the same time, same place.`;

const MEDIUM_PARAGRAPHS = [
  `Right, let's get started. Thanks everyone for making it. Apologies received from Lorraine and Mel — they're both at the LMC event this afternoon. We've got a substantial agenda so I'll keep us moving. First item: the ARRS workforce position. As you know the 2026/27 funding allocation has come through and we've had a 3.3% uplift on the headline figure, but we need to factor in the employer NI changes and the pension contribution increase. Net effect for our practice is roughly £18,000 less spending power than last year despite the nominal uplift. James has done the modelling.`,
  `Yes, the headline ARRS allocation for our PCN is £487,000 for the year, which sounds like a lot, but once you net off the 14.38% employer pension and the 15% employer NI, plus the inflationary increase on existing post-holders, we're looking at funding for approximately 11.2 whole-time-equivalent ARRS roles. Last year we ran 12.0 WTE. So we're going to have to make a decision about which post we don't backfill when the current pharmacist's contract ends in August.`,
  `That's helpful, thank you James. The options as I see them are: don't replace the pharmacist when she leaves and accept the loss of capacity; replace her on a part-time basis at 0.6 WTE which is what the new ARRS budget will accommodate; or look at converting the role to a different ARRS-eligible profession where we might get more hours per pound, like a paramedic or social prescriber. Anita, what's your view from Brook Health Centre's perspective?`,
  `From our side, the pharmacist input has been transformative for the structured medication reviews and we've cleared a real backlog of polypharmacy patients who hadn't had a comprehensive review in years. If we lose that capacity, those reviews start sliding again. My preference would be to retain the pharmacist at part-time hours rather than substitute. The clinical risk of stopping SMRs altogether is significant.`,
  `I'd echo that, the SMR work has been valuable and we shouldn't lose it just because the pound stretches less far. But we also need to think about the unmet need — the frailty cohort is growing, our two-week wait referrals to the falls clinic are getting longer because there's no community alternative. A paramedic doing home visits could address that, and they're cheaper per hour than a pharmacist. It's not a like-for-like swap.`,
  `Both are valid. Can I propose we do this — we retain the pharmacist at 0.6 WTE, focused tightly on SMRs and high-risk polypharmacy, and we use the freed-up budget to bring in a paramedic at 0.4 WTE for the frailty home visits. Net effect is we maintain SMR capacity and add new home-visit capacity, even though the total ARRS WTE goes down slightly. James, can the numbers stretch to that?`,
  `Just about, yes. The pharmacist at 0.6 costs us approximately £33,000 inclusive of on-costs, and a paramedic at 0.4 is around £21,000, total £54,000 against an ARRS allocation of £58,000 for that pair of roles. So we have a £4,000 buffer for incidentals. It's tight but it works. I'd want to add a contingency line in the budget for sickness cover or if the paramedic agency rates go up mid-year.`,
  `AGREED. So action one: James to draft the revised ARRS staffing plan with these two roles, share with the partnership board for sign-off by 19th May. Action two: Sarah to give the current pharmacist formal notice of the change to part-time hours — Sarah, do you want to talk to her informally first? Yes, I'll have a conversation with her this week, then issue the variation in writing once the partners have signed off the plan. Good.`,
  `Moving on to QOF. James, where are we? We've got the Q4 position. We're tracking at 89.2% of total available points. The risk areas are the frailty domain at 71%, and the asthma review domain at 76%. Everything else is green or close to it. The frailty issue is largely about the home-visit capacity we just discussed, so that's hopefully addressed by the paramedic. The asthma situation is different — we're failing on annual reviews where the patient is over-12 and on a steroid inhaler. Of 340 eligible patients, 81 still need their review by 31st March.`,
  `Eighty-one is a lot in five weeks. Can we do an asthma clinic blitz? Yes, that's what I was going to propose. We could run two evening clinics — one in the first week of March, one in the second — each with two nurses, batch-recall the patients, do the spirometry where indicated, the inhaler technique check, the action plan review. We've done it before, it's effective. The pharmacist could attend and do an inhaler technique review on each patient — that's part of the structured medication review work anyway.`,
  `What's the cost? Two nurses for two evenings is approximately £600. Pharmacist time is already costed. So £600 to recover potentially £8,000 of QOF points. AGREED. Action three: Anita to organise the asthma clinic blitz, dates to be confirmed but in the first half of March. Recall letters out by 28th February.`,
  `Right, item three: the digital transformation programme. Malcolm has been leading on this — Malcolm, where are we with the Notewell rollout to the wider PCN? Thanks. So Notewell is now in steady use at three of the seven practices — Brook, Brackley, and Towcester. We've had positive feedback on time savings, particularly for partnership meetings and clinical governance meetings. Average time saving reported is around 90 minutes per meeting in note-taking and write-up. The MHRA Class I registration came through in March, which means we've got the regulatory cover to use it for clinical meetings as well.`,
  `For the four practices not yet using it — what's the barrier? Mostly capacity and IG concerns. We've now got a standardised DPIA template that's been ICB-approved, which removes most of the IG friction. Capacity is harder — the practice manager needs an hour or two to set up users and walk people through it. I've offered to do that on-site for any practice that wants it, but I need them to give me a date.`,
  `Can you write to the four practice managers this week with three proposed dates and ask them to pick one? Yes, I can do that. Action four: Malcolm to circulate three on-site setup dates to Springfield, Bugbrooke, Denton, and The Parks practice managers by end of this week. Targeting completion of all rollouts by end of June.`,
  `Item four: the ICB new models pilot. We've been asked whether we'd be interested in joining the ENN pilot — the East Northants Neighbourhood — alongside 3Sixty and PML. The ICB is offering up to £180,000 of pilot funding to test integrated neighbourhood working with social care, mental health and the voluntary sector. The ask of us would be to provide a clinical lead at 0.1 WTE for 18 months, plus engagement at the practice partner level. It's a significant commitment but it positions us well for the post-2027 contract reforms.`,
  `What's the catch? The catch is the governance overhead. There's a programme board, a clinical reference group, a steering group, and quarterly reporting to the ICB. It would absorb a meaningful chunk of the clinical lead's time on top of the 0.1 WTE — probably another half-day a month in meetings. And the funding doesn't cover that overhead. So in practice we'd be subsidising the pilot from our own resources.`,
  `Hmm. Can we say yes in principle but ask for protected time for the governance, not just the clinical lead role? Yes, I think we should — the ICB is asking for partners and they need us, so there's room to negotiate. Let me draft a response that says yes in principle, conditional on the funding being uplifted to cover the governance overhead, and we'll see what comes back.`,
  `AGREED. Action five: Sarah to draft the response to the ICB on the ENN pilot, conditional acceptance with funding uplift requested for governance overhead. Circulate to partners for sign-off before submission. Item five: any other business. Anything? Yes, just one — the patient survey results came back and we're at 88% would-recommend, which is up from 84% last year. The free text comments highlighted reception waiting times and difficulty getting through on the phone. Both of which we know about.`,
  `Worth noting we've still got two receptionist vacancies. The phone line issue is largely the same problem — not enough staff to answer the volume of calls. The new candidate we've offered should help once they start. We should look at whether the cloud-based phone system the ICB's been talking about would actually help us. Action six: Sarah to look into the cloud phone system pilot, report back at next month's meeting. Anything else? No? Right, thanks all. Next meeting same time, Wednesday 11th June.`,
];

const LONG_PARAGRAPHS = [
  `Welcome everyone, thanks for making it across to Wootton Community Centre. Apologies have been received from Tracey Dempster, Michael Chapman, and Lucy Hibberd — all three are at the regional ICB workshop today. We've got Mark Gray here from PML, Andrew Moore also from PML representing finance, and Carolyn Abbisogni hopefully joining by Teams in about half an hour. From the practice side we've got representatives from all seven NRES practices: Anita from Brook, Mel from Brackley, Alexander from The Parks, Hayley from Springfield, Chloe from Towcester, Lorraine from Bugbrooke, and Nicola from Denton. Right, the agenda is in front of you, item one is the MOU position, item two is the buyback claims framework, item three is the budget allocation for 2026/27, item four is the digital transformation update, item five is governance and standing orders, item six is the operating model review, item seven is workforce and ARRS, and item eight is AOB. We've got two and a half hours, that's twenty minutes per item plus AOB, so I'll keep us moving.`,
  `Item one, the MOU. As you know we're now on version 5.1 of the MOU between the seven practices, PML as the SNO, and the ICB. Version 5.0 was circulated three weeks ago, we received twelve sets of comments back from practices, and Sarah has consolidated those into version 5.1 which is in your packs. The key changes from v5 to v5.1 are: the governance schedule has been clarified to make explicit that any decision affecting practice income above £10,000 requires unanimous practice consent rather than majority; the data sharing schedule has been tightened so that PML cannot access individual patient-level data without explicit per-purpose consent from the relevant practice; and the dispute resolution clause has been amended to add a mediation step before formal arbitration. Anita, you raised the patient-level data point — does the v5.1 wording address your concern?`,
  `Yes, mostly. The wording is now clear that PML cannot access patient-level data without per-purpose consent, but I'm still concerned about the wording around aggregated data. Aggregated data with small denominators can be re-identifying, particularly in our smaller practices. I'd want a clause that says aggregated data with a denominator below thirty cannot be released without explicit consent. Otherwise we're saying PML can have aggregated data freely and the small-numbers risk isn't addressed. Can we add that? Mark, what's your view from PML's perspective? Yes, I think that's reasonable. We're not asking for anything that would require denominators below thirty for the use cases we have in mind, so adding that constraint doesn't actually limit anything we want to do. Happy to accept that amendment. Right, AGREED — Sarah to add a denominator-thirty clause to the data sharing schedule for v5.2.`,
  `On the dispute resolution mediation step — Mel, you raised this. Yes, the previous version had us going straight from internal escalation to formal arbitration which would be expensive and adversarial. The mediation step gives us a chance to resolve things without lawyers getting involved. I'd want to know who the mediator would be — we shouldn't be picking someone post-hoc, we should agree the mediator framework upfront. The LMC has a panel of accredited mediators we could use, that would be my preference. Andrew, from PML's finance perspective is that workable? Yes, the LMC mediator panel is fine with us. The cost is shared 50-50 between the parties to the dispute, which is the standard arrangement. AGREED — v5.2 to specify LMC mediator panel.`,
  `Any other points on the MOU? Hayley, you raised something about the indemnity clause. Yes, the indemnity clause as currently drafted has the practice indemnifying PML for any losses arising from the practice's performance under the MOU. That's potentially a very wide liability and our individual indemnity policies might not cover us for that level of exposure. I'd want to see it capped at the value of the contract, not unlimited. Mark? We can accept a cap, yes. The standard NHS contracting position is a cap at £1 million or 1.5 times the annual contract value, whichever is lower. I'd be comfortable with that. Lorraine, anything from your side? Yes, the change to the unanimous-consent threshold from £25,000 in v4 to £10,000 in v5 is a big change. I want to make sure that's deliberate and not an oversight. Some smaller commitments will now require all seven practices to sign off, which could slow things down significantly. Sarah, what's the rationale?`,
  `The rationale was that £25,000 was felt to be too high a threshold given that some practices' total annual ARRS income through the PCN is only around £80,000. A £25,000 commitment is therefore over a quarter of their ARRS funding and they should have a veto on something that significant. £10,000 was felt to be a more appropriate threshold — it's still meaningful enough that practices will care about it, but it's not so frequent that it'll require constant consensus-building. We could go to £15,000 as a compromise. Lorraine? £15,000 works for me, that's still meaningful but not so frequent. Anyone object to £15,000? No? AGREED — v5.2 to set the unanimous-consent threshold at £15,000.`,
  `Right, that gives us a clear set of changes for v5.2. Sarah, when can you turn that around? I can have v5.2 out by end of next week, with a one-week consultation period for practices to verify the changes match what we agreed today. Then a further week for any final wording refinement, then ready for signature. So we're looking at a signed MOU by 31st May. AGREED. Action: Sarah to issue v5.2 by 9th May, consultation to 16th May, final version to 23rd May, target signature by 31st May. Right, that's item one done. Item two, the buyback claims framework.`,
  `Background for those who weren't at the last meeting — the buyback claims framework is the mechanism by which practices can recharge to PML for clinical work that PML has commissioned through us as the SNO but which is delivered by the practices on the ground. Examples include the enhanced access work, the cervical screening uplift, the long-term condition reviews where we're delivering against a PML-commissioned target. Currently there's no consistent process — practices submit claims in different formats, PML processes them at different speeds, and there's been disputes about what's eligible. The proposal is for a standardised five-stage approval pipeline with a four-state finance processing track. Malcolm has built a Notewell-based system to support this — Malcolm, can you walk us through it?`,
  `Thanks. So the system has two main user groups. Practices submit claims via a web form, which captures: the activity description, the date or date range, the volume of activity (number of patients seen, number of reviews completed, et cetera), the unit cost, and any supporting evidence. The form is structured so that the categories match PML's commissioning categories, which removes the ambiguity about what's eligible. Once submitted the claim enters stage one, which is automated validation — we check that mandatory fields are populated, that the unit cost is within the agreed tariff, and that the claim is for activity within the current financial year. If validation passes the claim moves to stage two.`,
  `Stage two is clinical review. A nominated clinical lead at PML — currently Mark — reviews the claim for clinical appropriateness. This is the check that the activity actually happened and was clinically indicated. If the volume seems unusually high there's a query mechanism to ask the practice for additional evidence. Stage three is finance review, which is Andrew's team at PML. They check the cost calculation and confirm budget availability against the relevant commissioning line. Stage four is the formal approval, which is a sign-off from the PML medical director — Mark again, but in his SRO capacity rather than clinical reviewer capacity. Stage five is the payment instruction to the practice, which generates the recharge invoice.`,
  `Once the claim hits stage five it enters the four-state finance processing track. State one is payment scheduled — we know what's being paid and when. State two is payment in progress — the BACS run has been initiated. State three is payment confirmed — the practice's bank has confirmed receipt. State four is payment closed — the audit trail is finalised and the claim is locked. The practice has visibility of state at every point through the same web interface. Andrew, anything to add from the finance side? Yes, the four-state model is what we already use for our other recharge arrangements with the federation, so this fits with our existing finance processes. The only thing I'd flag is that state two to state three can take up to five working days because of the BACS clearing cycle, so practices shouldn't expect same-day visibility there.`,
  `Mel, you had questions about the timeline at the last meeting. Yes, the question was about how long the whole pipeline takes from submission to payment. Andrew, can you commit to a service level? In normal volume conditions we're targeting fifteen working days from a clean submission to state two, then five working days to state three. So three weeks total. If a claim has queries it's longer obviously. We'll aim to flag queries within five working days of submission. AGREED — fifteen working days from submission to BACS initiation, five working days for queries to be raised. Action: Mark and Andrew to confirm the SLA in writing as part of the operating procedure.`,
  `Question from Alexander — what's the position if a claim is rejected? Is there an appeal mechanism? Yes, rejected claims can be appealed within twenty working days. The appeal goes to a panel comprising the PML medical director, a practice representative not from the practice that submitted the claim, and the ICB commissioning manager. The panel decision is binding. We'd expect appeals to be rare — fewer than five percent of claims — but the mechanism is there. AGREED. Item two complete. Sarah, any further actions on the buyback framework?`,
  `Just one — Malcolm to publish the user guides for both practices and PML staff by the time the system goes live. Target go-live is 1st June. Action: Malcolm to publish user guides by 28th May, soft launch with two practices on 1st June, full rollout by 1st July. Right, item three, the budget allocation for 2026/27. Andrew, you've prepared the paper, do you want to take us through it?`,
  `Thanks. So the headline position is that PML's ICB allocation for 2026/27 is £4.7 million across all NRES activities, which is up 4.1% on last year. After taking out PML's central costs — finance, governance, clinical leadership, the digital infrastructure including this system — we have £3.85 million available for distribution to practices. The proposed allocation methodology is the same as last year: 60% on a registered population basis, 25% on a deprivation-adjusted basis using the IMD, and 15% on activity volume from the previous twelve months. The rationale for keeping deprivation in the formula at 25% is that we know the population-only allocation doesn't reflect actual clinical workload — practices in more deprived areas see roughly 20% more patient contacts per registered patient.`,
  `What does that mean in practice for individual practices? Brook gets £620,000, Brackley gets £580,000, The Parks gets £510,000, Springfield gets £490,000, Towcester gets £480,000, Bugbrooke gets £470,000, and Denton gets £700,000 reflecting its higher deprivation weighting and larger list size. Total £3,850,000. The figures are in your pack with the calculation methodology shown step-by-step. Question — is the IMD weighting still the right multiplier? I know there was a debate last year about whether 25% was generous enough given the actual workload differential. Yes, the workload data we collected over the year suggests the actual differential is more like 22-25%, so 25% is in the right range. We could review again in a year if anyone wants to test it.`,
  `Nicola, you wanted to raise something about the activity-volume component. Yes, the activity-volume component is using QOF achievement as the activity proxy, but QOF is a measure of process completion, not actual workload. A practice that does lots of telephone consultations and same-day urgent care isn't getting credit for that in the QOF figure. I'd want us to look at a more direct workload measure for next year — appointments delivered, contacts per registered patient, something like that. For this year I'm not asking to change it, I just want it on the record that we should review the methodology. Noted. Action: Andrew and Sarah to bring a paper on alternative activity-volume measures to the September meeting. Anyone object to the proposed allocation as set out? No? AGREED — allocation as proposed, with the methodology review for next year.`,
  `Item four, digital transformation. Malcolm, where are we? Notewell is now in production at all seven NRES practices as of last month. We've completed approximately 320 meetings through the system to date. The MHRA Class I registration is in place. We've added new functionality this quarter including the AgeWell translation feature for our population that doesn't have English as a first language, the document sign-off service which is now being used for ICB-required attestations, and the DPIA generator which has saved us approximately forty hours of practice manager time during the rollouts to other PCNs. The system handled the recent Programme Board offsite in Wootton without issues despite that being a six-hour meeting with twenty-three attendees.`,
  `On the wider digital agenda — we're now looking at three further pieces of work. First, the patient-facing AgeWell platform which we discussed at the last meeting. We're now in user testing with twelve patients across three of our practices, all of whom have given written consent for the testing. Early feedback is positive — the translation accuracy is rated as good or excellent by all twelve, and the role-play training feature is being used by carers and family members in addition to the patients themselves. We're aiming to extend the user testing to thirty patients by end of June and then make a decision on broader rollout.`,
  `Second, the integration with the ICB's new community services platform — that's the platform replacing the current system for community physio, district nursing, and so on. The ICB has invited us to participate in the design phase for the integration with primary care, and we'll have a seat on the design group. Mel and I will represent NRES at those meetings. Third, the mobile recording capability for the community-facing roles. Currently Notewell only works in browser; we've had requests for native mobile apps from the social prescribers and community pharmacists who do home visits and need to capture meeting notes from the patient's home. We're scoping that work — potentially partnering with a development house given the mobile apps are outside Notewell's current technical stack.`,
  `Question about the mobile app — what's the cost going to be and where does the funding come from? We're scoping that now. Initial estimate is £40,000-£60,000 for a basic Android and iOS app integrating with the existing Notewell backend. Funding options: ICB digital transformation budget which has approximately £150,000 unallocated for 2026/27; PCN Capacity Fund which we've underspent by £35,000 this year; or a phased approach where we fund a minimum viable Android-only build first for around £25,000 and then iterate. The phased approach is my preference — we get something useful in the field within three months and we can prove the business case before committing to the full investment.`,
  `That sounds sensible. Let's go with the phased approach. Action: Malcolm to bring a detailed costed proposal for the Android MVP to the June Programme Board, with target build start of July. Mark, anything from PML on the digital agenda? Yes, just to flag that we've been talking to the ICB about whether the Notewell platform could be used more widely beyond NRES. There's interest from two other PCNs in the county and from the community services side. We don't want to create capacity problems for ourselves but if there's interest in licensing the platform to other organisations that's worth a structured conversation. Let's pick that up offline. Item four done.`,
  `Item five, governance and standing orders. We have version 2.3 of the standing orders in your pack, which has been through legal review. The main changes from v2.2 are: the conflicts of interest declarations have been moved from a once-yearly to a rolling declaration process — any change in interest must be declared within twenty working days; the quorum requirements have been reduced from five practices to four practices to make meetings more achievable when there are sickness or annual leave conflicts; and the chair rotation has been formalised — the chair rotates between the seven practices on an alphabetical basis, six month terms, no practice chairs twice in a row. Anyone want to challenge any of that?`,
  `On the quorum reduction — five to four — I'd want to understand the rationale. Four out of seven is a small majority, decisions taken at quorum-of-four would be binding on the three not present. Is that comfortable? The rationale is that we've had two cancellations this year because of quorum failure and the cost of postponed decisions has been higher than the cost of slightly less inclusive decision-making. We can require that decisions taken at quorum-of-four are circulated within five working days for review by the absent practices, with a five working day window to raise objections. If objections are raised the decision goes back to a full meeting. That gives us the speed without losing the inclusivity. Acceptable? Yes I think so. AGREED — quorum at four, with the post-meeting review window.`,
  `On the chair rotation — alphabetical, six months. Hayley, you've been chair for the last twelve months, you're going to be the first to step down on this rotation. Any view? Yes, I think the rotation is right but I'd want a six-month overlap period where the outgoing chair supports the incoming chair, particularly around the relationship with the ICB and PML. The chair role isn't just chairing meetings, it's representing NRES at external forums, and that takes time to build relationships. Shadow period of three months would be my suggestion. AGREED — three-month shadow period for incoming chairs.`,
  `On the conflicts of interest — moving to rolling declarations. Anita, you've been pushing for this. Yes, the once-yearly system was failing because practice partners' interests change frequently — they take on directorships, they have shareholdings change, family members get jobs. Once a year we'd have all the declarations in but they'd be six months out of date by the time they were used in decision-making. Rolling declarations with a twenty-day window for changes is the right answer. There needs to be an enforcement mechanism though — what happens if a partner doesn't declare within the twenty days? My proposal is that decisions affecting that partner's undeclared interest are voidable at the request of any other partner. That's a strong incentive to declare promptly. AGREED.`,
  `Right, that's standing orders done. Action: Sarah to publish v2.4 with the agreed amendments by 16th May, formal adoption at the June Programme Board. Item six, the operating model review. We commissioned a review of the operating model in January, that's been done by the consultancy, the report is in your pack. The headline conclusions are: the PML-as-SNO model is working but has scalability constraints; the seven-practice configuration is at the upper end of what's manageable through the current governance structures; and there are opportunities to streamline the operational interface between PML and the practices through better digital tooling, particularly around financial and performance reporting.`,
  `The recommendations break into three groups. First, governance simplification — fewer meetings, longer agendas, more delegation to sub-groups. The current pattern of monthly programme board, monthly partners' meeting, fortnightly operations meeting, plus various sub-group meetings, is unsustainable for the practice managers who are spending a day a week in NRES governance on top of running their practices. Second, financial reporting — we should be moving to monthly management accounts with a standard format rather than the current ad-hoc reporting that varies between practices. Third, performance reporting — we should be setting and tracking a small number of meaningful KPIs rather than the current sprawl of metrics that nobody really uses.`,
  `On the governance simplification — what's the proposal? The proposal is to move the operations meeting from fortnightly to monthly, with a sub-group of the practice managers handling operational issues between meetings via a Teams group. The programme board moves from monthly to quarterly, with the partners' meeting taking the strategic decisions monthly. That removes approximately twelve meeting-days from the calendar over a year. Practice managers would still meet operationally as needed, just not in the formal forum. Mel, you've been most affected by the current cadence — does this work? Yes, the operations meeting going to monthly with a Teams group between meetings is the right answer. Most operational issues don't need a formal meeting, they need a quick conversation and a decision. AGREED.`,
  `On financial reporting — Andrew, can you commit to monthly management accounts in a standard format? Yes, we can do that, but I'd need an agreed template — what's the standard format? Let me bring a proposal to the June meeting. The template will include: actual versus budget for the month and year-to-date, by commissioning category; full-time equivalent staffing by role; activity volume against target; and any material variances explained. I can have that ready by 6th June for adoption at the June meeting. AGREED. Action: Andrew to bring the standardised management accounts template to the June meeting.`,
  `On performance reporting — what KPIs do we want to track? The consultancy has recommended five: practice population coverage of QOF, ARRS workforce stability measured as the proportion of post-holders in post throughout the year, financial position measured as actual versus allocation, patient satisfaction as the would-recommend score, and a strategic measure which they suggest should be progress against the long-term plan. I'd like to add a sixth — clinical safety incidents reported, as a measure of the safety culture we're trying to build. Six KPIs is manageable. Anyone want to add or change? No? AGREED.`,
  `Item six done. Item seven, workforce and ARRS. Sarah, the headline position. As discussed at last week's prep call, the 2026/27 ARRS allocation across NRES is £3.4 million which funds approximately 78 WTE across all roles. The current establishment is 81.2 WTE so we have a small over-establishment which we need to address through natural turnover rather than redundancy. Three pharmacists, two paramedics, four social prescribers, and a physiotherapist are due to come up for renewal in the next twelve months — managing those renewals against the reduced FTE will get us back to establishment by April 2027.`,
  `On the recruitment side — we have one open paramedic post which has been advertised twice without success, and an open clinical pharmacist post which we're filling next month. The paramedic difficulty is a national issue, not specific to NRES — I've spoken to colleagues in Cambridgeshire and Bedfordshire and they have similar issues. Options: continue to recruit at the same rate and accept longer time-to-fill; offer a recruitment premium of £2,000 sign-on bonus which is below market for paramedics; or look at growing our own through the Trainee Advanced Paramedic programme. Mark, the trainee programme — can PML support that? Yes, we've actually just secured ICB funding for two trainee paramedic positions across the wider PML footprint. NRES would be eligible to apply for one of those. The trainee programme is a two-year placement at a discounted rate followed by a full-rate substantive post. AGREED — Sarah to apply for one of the trainee paramedic positions through the PML scheme.`,
  `Item eight, AOB. Two items I've got — first, the CQC inspection cycle. We're now eighteen months from our last inspection and the new pattern is twenty-four month cycles, so we're potentially six months from a notification. I'd like us to do a self-assessment in July using the CQC framework, identify any gaps, and remediate before the formal inspection arrives. Anita, can you lead that? Yes, I can lead the self-assessment. I'll need access to the policy framework, the audit results, the patient feedback, and the workforce data. Sarah, can you help with the data side? Yes. AGREED — Anita to lead, Sarah to support, July self-assessment, remediation plan by August.`,
  `Second AOB item — patient engagement. We've had three complaints in the last quarter about the difficulty of getting through on the phone and the wait times for routine appointments. We need to acknowledge that and have a plan. The phone issue is a cloud-based phone system pilot that's been going on at Brook, and the early data is good — 22% improvement in first-call resolution. We could roll that out across all seven practices but the cost is approximately £18,000 per practice so £126,000 total. That's not in any current budget. Andrew, where could we find that? It's a capital investment with a clear revenue benefit. We could borrow against the capital fund, recoup over three years. Let me bring a proposal. AGREED — Andrew to bring a costed proposal for the cloud phone system rollout to the June meeting.`,
  `Anything else for AOB? No? Right, thanks everyone, that's been a productive session. Date of next Programme Board is the 12th of June, same venue, ten o'clock start. Sarah will issue the minutes within five working days. Travel safely back. Meeting closed.`,
];

const SHORT_FIXTURE: TestFixture = {
  size: 'short',
  title: 'Pipeline Test (Short) — Weekly Stand-up',
  agenda: 'Workforce update; QOF position; AOB',
  attendees: ['Sarah Manager', 'James Finance', 'Anita Practice'],
  durationMinutes: 8,
  transcript: SHORT_TRANSCRIPT,
};

const MEDIUM_FIXTURE: TestFixture = {
  size: 'medium',
  title: 'Pipeline Test (Medium) — Monthly Partnership Meeting',
  agenda: 'ARRS workforce 2026/27; QOF Q4 position; Notewell rollout; ENN pilot; Patient survey',
  attendees: ['Sarah Manager', 'James Finance', 'Anita Practice', 'Malcolm Digital'],
  durationMinutes: 45,
  transcript: MEDIUM_PARAGRAPHS.join('\n\n'),
};

const LONG_FIXTURE: TestFixture = {
  size: 'long',
  title: 'Pipeline Test (Long) — NRES Programme Board',
  agenda: 'MOU v5.1 review; Buyback claims framework; 2026/27 budget allocation; Digital transformation; Standing orders v2.3; Operating model review; Workforce & ARRS; CQC; Patient engagement',
  attendees: [
    'Sarah Manager', 'Mark Gray', 'Andrew Moore', 'Carolyn Abbisogni',
    'Anita Carter', 'Mel Thompson', 'Alexander Whitehead',
    'Hayley Willingham', 'Chloe Lamont', 'Lorraine Spicer', 'Nicola Draper',
    'Malcolm Digital',
  ],
  durationMinutes: 150,
  transcript: LONG_PARAGRAPHS.join('\n\n'),
};

export const TEST_FIXTURES: Record<TestSize, TestFixture> = {
  short: SHORT_FIXTURE,
  medium: MEDIUM_FIXTURE,
  long: LONG_FIXTURE,
};

export function getFixture(size: TestSize): TestFixture {
  return TEST_FIXTURES[size];
}
