project_id = "dphcnbricafkbtizkoal"

[functions.assemblyai-transcription]
verify_jwt = false

[functions.generate-meeting-minutes]
verify_jwt = false

[functions.openai-realtime-session]
verify_jwt = true

[functions.realtime-transcription]
verify_jwt = true

[functions.deepgram-realtime]
verify_jwt = false

[functions.echo-proxy]
verify_jwt = false

[functions.audio-transcription]
verify_jwt = false