import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Copy, Download, FileText } from 'lucide-react';
import { toast } from 'sonner';
import { BPReading } from '@/hooks/useBPCalculator';

interface BPAverages {
  systolic: number;
  diastolic: number;
  pulse?: number;
  systolicMin: number;
  systolicMax: number;
  diastolicMin: number;
  diastolicMax: number;
}

interface NHSCategory {
  label: string;
  color: string;
  description: string;
}

interface BPExportOptionsProps {
  readings: BPReading[];
  averages: BPAverages | null;
  category: NHSCategory | null;
}

export const BPExportOptions = ({ readings, averages, category }: BPExportOptionsProps) => {
  const includedReadings = readings.filter(r => r.included);

  const copyToClipboard = async () => {
    if (!averages) return;

    const text = `Average BP: ${averages.systolic}/${averages.diastolic} mmHg (${includedReadings.length} readings)
Range: ${averages.systolicMin}-${averages.systolicMax} / ${averages.diastolicMin}-${averages.diastolicMax}
${averages.pulse ? `Average Pulse: ${averages.pulse} bpm` : ''}
${category ? `Category: ${category.label}` : ''}

Individual Readings:
${includedReadings.map((r, i) => `${i + 1}. ${r.systolic}/${r.diastolic}${r.pulse ? `/${r.pulse}` : ''}${r.date ? ` (${r.date})` : ''}`).join('\n')}`;

    try {
      await navigator.clipboard.writeText(text);
      toast.success('Copied to clipboard');
    } catch (error) {
      toast.error('Failed to copy');
    }
  };

  const downloadCSV = () => {
    const headers = ['Reading #', 'Date', 'Time', 'Systolic', 'Diastolic', 'Pulse', 'Source'];
    const rows = includedReadings.map((r, i) => [
      i + 1,
      r.date || '',
      r.time || '',
      r.systolic,
      r.diastolic,
      r.pulse || '',
      `"${(r.sourceText || '').replace(/"/g, '""')}"`
    ]);

    // Add summary row
    if (averages) {
      rows.push([]);
      rows.push(['AVERAGE', '', '', averages.systolic, averages.diastolic, averages.pulse || '', '']);
      rows.push(['RANGE', '', '', `${averages.systolicMin}-${averages.systolicMax}`, `${averages.diastolicMin}-${averages.diastolicMax}`, '', '']);
      if (category) {
        rows.push(['CATEGORY', category.label, '', '', '', '', '']);
      }
    }

    const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bp-readings-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('CSV downloaded');
  };

  const downloadSummary = () => {
    if (!averages) return;

    const content = `BP AVERAGE REPORT
Generated: ${new Date().toLocaleString('en-GB')}

SUMMARY
═══════════════════════════════════════
Average Blood Pressure: ${averages.systolic}/${averages.diastolic} mmHg
Number of Readings: ${includedReadings.length}
${category ? `NHS Category: ${category.label}` : ''}
${category ? `${category.description}` : ''}

Systolic Range: ${averages.systolicMin} – ${averages.systolicMax} mmHg
Diastolic Range: ${averages.diastolicMin} – ${averages.diastolicMax} mmHg
${averages.pulse ? `Average Pulse: ${averages.pulse} bpm` : ''}

INDIVIDUAL READINGS
═══════════════════════════════════════
${includedReadings.map((r, i) => 
  `${(i + 1).toString().padStart(2)}. ${r.systolic.toString().padStart(3)}/${r.diastolic.toString().padStart(3)}${r.pulse ? ` (Pulse: ${r.pulse})` : ''}${r.date ? ` – ${r.date}${r.time ? ` ${r.time}` : ''}` : ''}`
).join('\n')}

═══════════════════════════════════════
Report generated by Notewell AI BP Average Service
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bp-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded');
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">Export Results</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="flex flex-wrap gap-3">
          <Button onClick={copyToClipboard} variant="outline">
            <Copy className="mr-2 h-4 w-4" />
            Copy to Clipboard
          </Button>
          <Button onClick={downloadCSV} variant="outline">
            <Download className="mr-2 h-4 w-4" />
            Download CSV
          </Button>
          <Button onClick={downloadSummary} variant="outline">
            <FileText className="mr-2 h-4 w-4" />
            Download Report
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};
