export interface TrainingScenario {
  id: string;
  category: string;
  categoryIcon: string;
  categoryColour: string;
  title: string;
  description: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
}

export const TRAINING_SCENARIOS: TrainingScenario[] = [
  {
    id: 'appointment_booking',
    category: 'Routine Reception',
    categoryIcon: '📅',
    categoryColour: '#005EB8',
    title: 'Appointment Booking',
    description: 'Patient wants to book a routine appointment for ongoing knee pain.',
    difficulty: 'Easy',
  },
  {
    id: 'new_patient_registration',
    category: 'Routine Reception',
    categoryIcon: '📋',
    categoryColour: '#005EB8',
    title: 'New Patient Registration',
    description: 'Recently arrived patient needs to register — confused about how the NHS works.',
    difficulty: 'Easy',
  },
  {
    id: 'urgent_chest_pain',
    category: 'Urgent Triage',
    categoryIcon: '🚨',
    categoryColour: '#DA291C',
    title: 'Urgent: Chest Pain',
    description: 'Distressed patient with chest tightness and shortness of breath.',
    difficulty: 'Hard',
  },
  {
    id: 'child_fever',
    category: 'Urgent Triage',
    categoryIcon: '🌡️',
    categoryColour: '#DA291C',
    title: 'Worried Parent: Child with Fever',
    description: "Emotional parent with a feverish child who hasn't eaten for 2 days.",
    difficulty: 'Medium',
  },
  {
    id: 'prescription_collection',
    category: 'Admin & Paperwork',
    categoryIcon: '💊',
    categoryColour: '#7C3AED',
    title: 'Prescription Collection Problem',
    description: "Patient's repeat prescription hasn't been processed — running out today.",
    difficulty: 'Medium',
  },
  {
    id: 'test_results',
    category: 'Admin & Paperwork',
    categoryIcon: '🔬',
    categoryColour: '#7C3AED',
    title: 'Chasing Test Results',
    description: "Anxious patient wants blood test results — receptionist can't share them.",
    difficulty: 'Medium',
  },
  {
    id: 'sicknote_request',
    category: 'Admin & Paperwork',
    categoryIcon: '📝',
    categoryColour: '#7C3AED',
    title: 'Fit Note / Sick Note Request',
    description: "Patient needs a fit note for their employer — doesn't understand the process.",
    difficulty: 'Easy',
  },
  {
    id: 'medication_from_abroad',
    category: 'Admin & Paperwork',
    categoryIcon: '📦',
    categoryColour: '#7C3AED',
    title: 'Medication from Abroad',
    description: "Patient takes medication prescribed overseas — doesn't know the UK brand name.",
    difficulty: 'Hard',
  },
  {
    id: 'routine_frailty_review',
    category: 'Ageing Well',
    categoryIcon: '🏠',
    categoryColour: '#D97706',
    title: 'Routine Frailty Review',
    description: 'Annual review for stable 82-year-old. Mild mobility issues but managing with stick. Lives alone with weekly family visits.',
    difficulty: 'Easy',
  },
  {
    id: 'post_discharge_visit',
    category: 'Ageing Well',
    categoryIcon: '🏠',
    categoryColour: '#D97706',
    title: 'Post-Discharge Visit',
    description: 'Recently home after hip fracture repair. Anxious about mobility and needs reassurance about recovery and rehab plan.',
    difficulty: 'Easy',
  },
  {
    id: 'polypharmacy_review',
    category: 'Ageing Well',
    categoryIcon: '🏠',
    categoryColour: '#D97706',
    title: 'Polypharmacy Review',
    description: 'Patient on 12 medications and confused about timings. Skipping doses and unsure which are essential.',
    difficulty: 'Medium',
  },
  {
    id: 'falls_assessment',
    category: 'Ageing Well',
    categoryIcon: '🏠',
    categoryColour: '#D97706',
    title: 'Falls Assessment',
    description: 'Two falls in the past month with no injury. Patient downplays concerns but daughter is worried about safety.',
    difficulty: 'Medium',
  },
  {
    id: 'carer_strain',
    category: 'Ageing Well',
    categoryIcon: '🏠',
    categoryColour: '#D97706',
    title: 'Carer Strain',
    description: 'Exhausted daughter caring for mother with moderate dementia. Tearful, considering residential care placement.',
    difficulty: 'Hard',
  },
  {
    id: 'advance_care_planning',
    category: 'Ageing Well',
    categoryIcon: '🏠',
    categoryColour: '#D97706',
    title: 'Advance Care Planning',
    description: 'Frail 89-year-old with heart failure. Wants to discuss future wishes and avoid further hospital admissions.',
    difficulty: 'Hard',
  },
];
