import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const openAIApiKey = Deno.env.get('OPENAI_API_KEY');

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface TranslationRequest {
  content: {
    title: string;
    subtitle: string;
    sessionInfo: string;
    patientInfo: string;
    translationLogHeader: string;
    speakerLabels: {
      gp: string;
      patient: string;
    };
  };
  targetLanguage: string;
  practiceInfo: {
    name: string;
    address: string;
    phone?: string;
  };
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log('Starting patient document translation...');
    
    if (!openAIApiKey) {
      throw new Error('OpenAI API key not configured');
    }

    const { content, targetLanguage, practiceInfo }: TranslationRequest = await req.json();
    
    console.log(`Translating patient document to: ${targetLanguage}`);

    // Prepare the translation prompt  
    const translationPrompt = `Translate the following medical document content to ${targetLanguage}. Return ONLY valid JSON in the exact format shown below:

{
  "title": "NHS Translation Service - Patient Copy",
  "subtitle": "Summary of Translation Session for Your Records",
  "sessionInfo": "Session Information",
  "patientInfo": "Patient Information",
  "translationLogHeader": "Translation Record",
  "speakerLabels": {
    "gp": "GP",
    "patient": "Patient"
  },
  "practiceInfo": {
    "name": "${practiceInfo.name}",
    "address": "${practiceInfo.address}",
    "phone": "${practiceInfo.phone || ''}"
  },
  "practiceInfoHeader": "Practice Information",
  "generalLabels": {
    "reportGenerated": "Report Generated",
    "sessionDate": "Session Date", 
    "sessionStart": "Session Start",
    "sessionEnd": "Session End",
    "duration": "Duration",
    "patientLanguage": "Patient Language",
    "totalTranslations": "Total Translations",
    "time": "Time",
    "speaker": "Speaker",
    "originalText": "Original Text",
    "translation": "Translation",
    "practice": "Practice",
    "address": "Address",
    "phone": "Phone"
  },
  "patientInfoText": "This document contains a record of all translations made during your medical consultation. This is provided for your personal records and reference.",
  "disclaimerText": "IMPORTANT DISCLAIMER: This is an automated translation service for communication assistance only. All medical decisions should be based on professional clinical judgement.",
  "reportGeneratedBy": "Report generated by NHS Translation Tool"
}

Translate ALL the values in the JSON structure to ${targetLanguage}. Keep the practice name, address, and phone number as provided, but translate the labels. Return ONLY the JSON, no other text.`;

    console.log('Sending translation request to OpenAI...');

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openAIApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'openai/gpt-5-mini',
        messages: [
          { 
            role: 'system', 
            content: 'You are a medical translation assistant. Translate document headers and labels accurately while maintaining medical appropriateness for patient understanding. Always respond with valid JSON only.' 
          },
          { role: 'user', content: translationPrompt }
        ],
        max_tokens: 1000,
        temperature: 0.3,
      }),
    });

    if (!response.ok) {
      const errorData = await response.text();
      console.error('OpenAI API error:', errorData);
      throw new Error(`OpenAI API error: ${response.status} ${errorData}`);
    }

    const data = await response.json();
    console.log('OpenAI response received');
    console.log('Full OpenAI response:', JSON.stringify(data, null, 2));

    if (!data.choices || data.choices.length === 0) {
      throw new Error('No translation received from OpenAI');
    }

    const translatedContent = data.choices[0].message.content;
    console.log('Raw translation content:', translatedContent);

    // Check if content is empty
    if (!translatedContent || translatedContent.trim() === '') {
      console.error('Empty response from OpenAI');
      throw new Error('Empty response from translation service');
    }

    // Parse the JSON response
    let parsedTranslation;
    try {
      // Clean the content in case there's extra whitespace or markdown
      const cleanContent = translatedContent.trim().replace(/^```json\s*/, '').replace(/\s*```$/, '');
      parsedTranslation = JSON.parse(cleanContent);
    } catch (parseError) {
      console.error('Failed to parse translation JSON:', parseError);
      console.error('Raw content:', translatedContent);
      throw new Error(`Invalid JSON response from translation service: ${parseError.message}`);
    }

    console.log('Successfully translated patient document');
    console.log('Final parsed result:', JSON.stringify(parsedTranslation, null, 2));

    return new Response(JSON.stringify({ 
      success: true, 
      translatedContent: parsedTranslation 
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in translate-patient-document function:', error);
    return new Response(JSON.stringify({ 
      success: false, 
      error: error.message 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});