import { useState } from 'react';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { useUserProfile } from '@/hooks/useUserProfile';
import { isLetterFormat } from '@/utils/letterParser';
import { formatLetterForEmail, convertToEmailSafeHTML } from '@/utils/formatLetterForEmail';
import { usePracticeContext } from '@/hooks/usePracticeContext';

export function useAutoEmail() {
  const [isSending, setIsSending] = useState(false);
  const { toast } = useToast();
  const { profile } = useUserProfile();
  const { practiceContext } = usePracticeContext();

  const sendEmailAutomatically = async (content: string, defaultSubject?: string) => {
    if (!profile?.email) {
      toast({
        title: "Email Not Available",
        description: "Unable to send email - no email address found in your profile.",
        variant: "destructive"
      });
      return false;
    }

    setIsSending(true);
    try {
      // Auto-generate subject from content
      const cleanContent = content.replace(/[#*`]/g, '').trim();
      const words = cleanContent.split(/\s+/).slice(0, 15);
      const autoSubject = words.join(' ');
      const subject = defaultSubject || `AI Generated: ${autoSubject.length > 80 ? autoSubject.substring(0, 77) + '...' : autoSubject}`;
      
      // Format message with consultation intro
      const message = `Thank you for using our AI consultation service. Here is the information generated for you:\n\n${content}`;
      
      // Detect if content is a letter format
      const isLetter = isLetterFormat(content);
      
      // Generate Word attachment
      let wordAttachment = null;
      try {
        if (isLetter) {
          // Use NHS letter document generator for letters
          const { generateNHSLetterBlob } = await import('@/utils/nhsLetterExport');
          
          // Basic options without practice details (these would need to come from practice_details table)
          const options = {
            content: content,
            filename: subject,
            clinicianName: profile.full_name || undefined,
          };
          
          const blob = await generateNHSLetterBlob(options);
          
          const reader = new FileReader();
          const base64Promise = new Promise<string>((resolve) => {
            reader.onloadend = () => {
              const base64 = (reader.result as string).split(',')[1];
              resolve(base64);
            };
          });
          reader.readAsDataURL(blob);
          const base64Content = await base64Promise;
          
          wordAttachment = {
            content: base64Content,
            filename: `${subject.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 50)}.docx`,
            type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
          };
        } else {
          // Use the same clean Word export as the Document Preview modal
          const { generateCleanAIResponseBlob } = await import('@/utils/cleanWordExport');
          
          const logoUrl = practiceContext?.logoUrl;
          const practiceName = practiceContext?.practiceName;
          const practiceAddress = practiceContext?.practiceAddress;
          const footerNote = practiceName
            ? `${practiceName}${practiceAddress ? ' • ' + practiceAddress : ''}`
            : 'Generated by Notewell AI';
          
          const blob = await generateCleanAIResponseBlob(content, subject, {
            logoUrl: logoUrl || undefined,
            logoPosition: 'left',
            footerNote,
          });
          
          const reader = new FileReader();
          const base64Promise = new Promise<string>((resolve) => {
            reader.onloadend = () => {
              const base64 = (reader.result as string).split(',')[1];
              resolve(base64);
            };
          });
          reader.readAsDataURL(blob);
          const base64Content = await base64Promise;
          
          wordAttachment = {
            content: base64Content,
            filename: `${subject.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 50)}.docx`,
            type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
          };
        }
      } catch (docError) {
        console.error('Word document generation failed:', docError);
        toast({
          title: "Attachment Failed",
          description: "Could not generate the Word document attachment. Email not sent.",
          variant: "destructive"
        });
        return false;
      }

      if (!wordAttachment) {
        toast({
          title: "Attachment Required",
          description: "Word document attachment is required but could not be generated.",
          variant: "destructive"
        });
        return false;
      }

      // Convert content to email-safe HTML
      // Use letter formatter for letters, generic formatter for other content
      const emailHtml = isLetter 
        ? formatLetterForEmail(message)
        : convertToEmailSafeHTML(message);

      // Prepare email data for Resend service
      const emailData = {
        to_email: profile.email,
        subject,
        html_content: emailHtml,
        from_name: 'Notewell AI',
        word_attachment: wordAttachment
      };

      // Send email via Supabase edge function (Resend)
      const { data, error } = await supabase.functions.invoke('send-meeting-email-resend', {
        body: emailData
      });

      if (error) {
        console.error('Email sending error:', error);
        throw new Error(error.message || 'Failed to send email');
      }

      if (!data?.success) {
        console.error('Resend error:', data);
        throw new Error(data?.error || 'Failed to send email via Resend');
      }

      toast({
        title: "Email Sent Successfully",
        description: `AI-generated content has been sent to ${profile.email}`,
      });
      
      return true;
    } catch (error: any) {
      console.error('Error sending email:', error);
      toast({
        title: "Send Failed",
        description: error.message || "Failed to send the email. Please try again.",
        variant: "destructive"
      });
      return false;
    } finally {
      setIsSending(false);
    }
  };

  return { sendEmailAutomatically, isSending };
}
