import { useState, useEffect, useCallback } from "react";
import { useLocation } from "react-router-dom";
import { MeetingData, MeetingSettingsState, SummaryContent } from "@/types/meetingTypes";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

export const useMeetingData = () => {
  const location = useLocation();
  const { user } = useAuth();
  const [meetingData, setMeetingData] = useState<MeetingData | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const [practiceData, setPracticeData] = useState<any>(null);

  const [meetingSettings, setMeetingSettings] = useState<MeetingSettingsState>({
    title: "",
    description: "",
    meetingType: "general",
    meetingStyle: "standard",
    attendees: "",
    agenda: "",
    date: "",
    startTime: "",
    format: "",
    location: "",
    practiceId: "",
    meetingFormat: "f2f",
    transcriberService: "whisper",
    transcriberThresholds: {
      whisper: 0.30,
      deepgram: 0.30
    }
  });

  const [summaryContent, setSummaryContent] = useState<SummaryContent>({
    attendees: "",
    agenda: "",
    keyPoints: "",
    decisions: "",
    actionItems: "",
    nextSteps: "",
    additionalNotes: ""
  });

  const saveMeetingToDatabase = async (data: MeetingData) => {
    if (!user || isSaving) return;
    
    setIsSaving(true);
    try {
      const { data: savedMeeting, error } = await supabase
        .from('meetings')
        .insert({
          user_id: user.id,
          title: data.title,
          transcript: data.transcript,
          duration: data.duration,
          word_count: data.wordCount,
          speaker_count: data.speakerCount,
          start_time: data.startTime,
          practice_name: data.practiceName,
          practice_id: data.practiceId,
          meeting_format: data.meetingFormat,
          // generated_notes removed - using meeting_summaries table instead
          started_by: data.startedBy,
          participants: data.participants || [],
          agenda: data.agenda || '',
          meeting_location: data.meetingLocation || '',
          auto_generated_name: data.autoGeneratedName || data.title,
          live_transcript_text: data.liveTranscriptText || null, // Save live transcript shown during meeting
          meeting_context: {
            saved_via: 'meeting_data_hook',
            has_attendees: Boolean(data.attendees?.length),
            enhancement_level: 'basic'
          }
        })
        .select()
        .single();

      if (error) throw error;

      setMeetingData(prev => prev ? { ...prev, id: savedMeeting.id } : null);
      setIsSaved(true);
      toast.success('Meeting saved successfully with enhanced context');
    } catch (error) {
      console.error('Error saving meeting:', error);
      toast.error('Failed to save meeting');
    } finally {
      setIsSaving(false);
    }
  };

  const loadExistingSummary = async (meetingId: string) => {
    try {
      const { data, error } = await supabase
        .from('meetings')
        .select('*')
        .eq('id', meetingId)
        .single();

      if (error) throw error;

      if (data) {
        const startDate = data.start_time ? new Date(data.start_time) : null;
        const pad = (n: number) => n.toString().padStart(2, '0');

        // Fetch transcript from meeting_transcripts table
        let transcriptContent = '';
        let summaryContent = '';
        try {
          const { data: transcriptData } = await supabase
            .from('meeting_transcripts')
            .select('content')
            .eq('meeting_id', data.id)
            .order('created_at', { ascending: false })
            .limit(1)
            .single();
          
          transcriptContent = transcriptData?.content || '';
        } catch (transcriptError) {
          console.log('No transcript found in meeting_transcripts table');
        }

        // Fetch meeting summary from meeting_summaries table
        try {
          const { data: summaryData } = await supabase
            .from('meeting_summaries')
            .select('summary')
            .eq('meeting_id', data.id)
            .maybeSingle();
          
          summaryContent = summaryData?.summary || '';
        } catch (summaryError) {
          console.log('No summary found in meeting_summaries table');
        }

        setMeetingData({
          id: data.id,
          title: data.title || 'Meeting',
          duration: data.duration_minutes?.toString() || '00:00',
          wordCount: transcriptContent.split(' ').filter(word => word.trim()).length,
          transcript: transcriptContent,
          speakerCount: 1,
          startTime: data.start_time || '',
          practiceName: '',
          practiceId: '',
          meetingFormat: data.meeting_format || '',
          generatedNotes: summaryContent || '',
          startedBy: data.user_id || '',
          participants: data.participants || [],
          agenda: data.agenda || '',
          meetingLocation: data.meeting_location || '',
          autoGeneratedName: data.auto_generated_name || '',
          meetingContext: data.meeting_context || {},
          notesStyle2: data.notes_style_2 || '',
          notesStyle3: data.notes_style_3 || '',
          notesStyle4: data.notes_style_4 || '',
          notesStyle5: data.notes_style_5 || ''
        });

        setMeetingSettings(prev => ({
          ...prev,
          title: data.title || 'Meeting',
          date: startDate ? `${startDate.getFullYear()}-${pad(startDate.getMonth() + 1)}-${pad(startDate.getDate())}` : "",
          startTime: startDate ? `${pad(startDate.getHours())}:${pad(startDate.getMinutes())}` : "",
          attendees: (data.participants || []).join(', '),
          agenda: data.agenda || '',
          format: (data.meeting_format as "" | "face-to-face" | "online" | "hybrid" | "phone") || "",
          location: data.meeting_location || ''
        }));
      }
    } catch (error) {
      console.error('Error loading meeting:', error);
    }
  };

  const fetchPracticeData = async () => {
    if (!user?.id) return;
    
    try {
      const { data, error } = await supabase
        .from('profiles')
        .select('practice_name, practice_logo_url')
        .eq('user_id', user.id)
        .single();

      if (!error && data) {
        setPracticeData(data);
      }
    } catch (error) {
      console.error('Error fetching practice data:', error);
    }
  };

  // Load meeting settings from localStorage/user preferences
  const loadMeetingSettings = useCallback(async () => {
    if (!user?.id) return;

    console.log('🔄 Loading meeting transcriber settings for user:', user.id);

    try {
      // Try to load from user_settings table first
      const { data, error } = await supabase
        .from('user_settings')
        .select('setting_value')
        .eq('user_id', user.id)
        .eq('setting_key', 'meeting_transcriber_preferences')
        .single();

      if (!error && data?.setting_value) {
        const savedSettings = data.setting_value as any;
        console.log('✅ Loaded transcriber settings from database:', savedSettings);
        
        setMeetingSettings(prev => ({
          ...prev,
          transcriberService: "whisper", // Force default to whisper since deepgram is no longer available
          transcriberThresholds: {
            whisper: savedSettings.transcriberThresholds?.whisper || 0.30,
            deepgram: savedSettings.transcriberThresholds?.deepgram || 0.80
          }
        }));
      } else {
        console.log('📝 No saved transcriber settings found in database, trying localStorage...');
      }
    } catch (error) {
      console.warn('⚠️ Database load failed, falling back to localStorage:', error);
      // Fallback to localStorage if database fails
      try {
        const saved = localStorage.getItem(`meeting_settings_${user.id}`);
        if (saved) {
          const savedSettings = JSON.parse(saved);
          console.log('✅ Loaded transcriber settings from localStorage:', savedSettings);
          
          setMeetingSettings(prev => ({
            ...prev,
            transcriberService: "whisper", // Force default to whisper since deepgram is no longer available
            transcriberThresholds: {
              whisper: savedSettings.transcriberThresholds?.whisper || 0.30,
              deepgram: savedSettings.transcriberThresholds?.deepgram || 0.80
            }
          }));
        } else {
          console.log('📝 No saved transcriber settings found in localStorage either');
        }
      } catch (localError) {
        console.error('❌ Error loading settings from localStorage:', localError);
      }
    }
  }, [user?.id]);

  // Save meeting settings 
  const saveMeetingSettings = useCallback(async (settings: Partial<MeetingSettingsState>) => {
    if (!user?.id) return;

    const settingsToSave = {
      transcriberService: settings.transcriberService,
      transcriberThresholds: settings.transcriberThresholds
    };

    console.log('💾 Saving meeting transcriber settings:', settingsToSave);

    try {
      // Save to database
      await supabase
        .from('user_settings')
        .upsert({
          user_id: user.id,
          setting_key: 'meeting_transcriber_preferences',
          setting_value: settingsToSave
        }, {
          onConflict: 'user_id,setting_key'
        });

      // Also save to localStorage as backup
      localStorage.setItem(`meeting_settings_${user.id}`, JSON.stringify(settingsToSave));
      
      console.log('✅ Transcriber settings saved successfully to both database and localStorage');
    } catch (error) {
      console.error('❌ Error saving meeting settings to database:', error);
      // Fallback to localStorage only
      try {
        localStorage.setItem(`meeting_settings_${user.id}`, JSON.stringify(settingsToSave));
        console.log('✅ Transcriber settings saved to localStorage as fallback');
      } catch (localError) {
        console.error('❌ Error saving to localStorage:', localError);
      }
    }
  }, [user?.id]);

  // Auto-save settings when transcriber settings change
  useEffect(() => {
    if (meetingSettings.transcriberService !== "whisper" || 
        meetingSettings.transcriberThresholds.whisper !== 0.30 ||
        meetingSettings.transcriberThresholds.deepgram !== 0.80) {
      console.log('🔄 Auto-saving transcriber settings due to change:', {
        service: meetingSettings.transcriberService,
        thresholds: meetingSettings.transcriberThresholds
      });
      saveMeetingSettings(meetingSettings);
    }
  }, [meetingSettings.transcriberService, meetingSettings.transcriberThresholds, saveMeetingSettings]);

  // Load settings on mount
  useEffect(() => {
    loadMeetingSettings();
  }, [loadMeetingSettings]);

  // Sync attendees and agenda from Meeting Settings into summary content
  useEffect(() => {
    setSummaryContent(prev => {
      const next = { ...prev } as typeof prev;
      let changed = false;
      const mAtt = (meetingSettings.attendees || '').trim();
      const mAg = (meetingSettings.agenda || '').trim();
      if (mAtt && mAtt !== prev.attendees) { next.attendees = mAtt; changed = true; }
      if (mAg && mAg !== prev.agenda) { next.agenda = mAg; changed = true; }
      return changed ? next : prev;
    });
  }, [meetingSettings.attendees, meetingSettings.agenda]);

  return {
    meetingData,
    setMeetingData,
    isSaving,
    isSaved,
    setIsSaved,
    meetingSettings,
    setMeetingSettings,
    summaryContent,
    setSummaryContent,
    practiceData,
    saveMeetingToDatabase,
    loadExistingSummary,
    fetchPracticeData,
    saveMeetingSettings
  };
};