import { useState, useEffect, useCallback } from "react";
import { useLocation } from "react-router-dom";
import { MeetingData, MeetingSettingsState, SummaryContent } from "@/types/meetingTypes";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

export const useMeetingData = () => {
  const location = useLocation();
  const { user } = useAuth();
  const [meetingData, setMeetingData] = useState<MeetingData | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const [practiceData, setPracticeData] = useState<any>(null);

  const defaultSettings: MeetingSettingsState = {
    roomName: '',
    participants: [],
    reminderTime: 5,
    enableAutoEmail: false,
    emailTemplate: '',
    emailRecipients: [],
    transcriberService: 'deepgram' as const,
    transcriberThresholds: {
      deepgram: 0.6,
      whisper: 0.7,
      browser: 0.8,
    },
  };

  const [meetingSettings, setMeetingSettings] = useState<MeetingSettingsState>(defaultSettings);

  const [summaryContent, setSummaryContent] = useState<SummaryContent>({
    attendees: "",
    agenda: "",
    keyPoints: "",
    decisions: "",
    actionItems: "",
    nextSteps: "",
    additionalNotes: ""
  });

  const saveMeetingToDatabase = async (data: MeetingData) => {
    if (!user || isSaving) return;
    
    setIsSaving(true);
    try {
      const { data: savedMeeting, error } = await supabase
        .from('meetings')
        .insert({
          user_id: user.id,
          title: data.title,
          transcript: data.transcript,
          duration: data.duration,
          word_count: data.wordCount,
          speaker_count: data.speakerCount,
          start_time: data.startTime,
          practice_name: data.practiceName,
          practice_id: data.practiceId,
          meeting_format: data.meetingFormat,
          generated_notes: data.generatedNotes,
          started_by: data.startedBy,
          participants: data.participants || [],
          agenda: data.agenda || '',
          meeting_location: data.meetingLocation || '',
          auto_generated_name: data.autoGeneratedName || data.title,
          meeting_context: {
            saved_via: 'meeting_data_hook',
            has_attendees: Boolean(data.attendees?.length),
            enhancement_level: 'basic'
          }
        })
        .select()
        .single();

      if (error) throw error;

      setMeetingData(prev => prev ? { ...prev, id: savedMeeting.id } : null);
      setIsSaved(true);
      toast.success('Meeting saved successfully with enhanced context');
    } catch (error) {
      console.error('Error saving meeting:', error);
      toast.error('Failed to save meeting');
    } finally {
      setIsSaving(false);
    }
  };

  const loadExistingSummary = async (meetingId: string) => {
    try {
      const { data, error } = await supabase
        .from('meetings')
        .select('*')
        .eq('id', meetingId)
        .single();

      if (error) throw error;

      if (data) {
        const startDate = data.start_time ? new Date(data.start_time) : null;
        const pad = (n: number) => n.toString().padStart(2, '0');

        setMeetingData({
          id: data.id,
          title: data.title || 'Meeting',
          duration: data.duration_minutes?.toString() || '00:00',
          wordCount: 0,
          transcript: '', // Will be loaded from transcript chunks
          speakerCount: 1,
          startTime: data.start_time || '',
          practiceName: '',
          practiceId: '',
          meetingFormat: data.meeting_format || '',
          generatedNotes: data.description || '',
          startedBy: data.user_id || '',
          participants: data.participants || [],
          agenda: data.agenda || '',
          meetingLocation: data.meeting_location || '',
          autoGeneratedName: data.auto_generated_name || '',
          meetingContext: data.meeting_context || {}
        });

        setMeetingSettings(prev => ({
          ...prev,
          roomName: data.title || 'Meeting',
          participants: data.participants || []
        }));
      }
    } catch (error) {
      console.error('Error loading meeting:', error);
    }
  };

  const fetchPracticeData = async () => {
    if (!user?.id) return;
    
    try {
      const { data, error } = await supabase
        .from('profiles')
        .select('practice_name, practice_logo_url')
        .eq('user_id', user.id)
        .single();

      if (!error && data) {
        setPracticeData(data);
      }
    } catch (error) {
      console.error('Error fetching practice data:', error);
    }
  };

  // Load meeting settings from localStorage/user preferences
  const loadMeetingSettings = useCallback(async () => {
    if (!user?.id) return;
    
    try {
      const saved = localStorage.getItem(`meetingSettings_${user.id}`);
      if (saved) {
        const parsedSettings = JSON.parse(saved);
        setMeetingSettings({
          roomName: parsedSettings.roomName || '',
          participants: parsedSettings.participants || [],
          reminderTime: parsedSettings.reminderTime || 5,
          enableAutoEmail: parsedSettings.enableAutoEmail || false,
          emailTemplate: parsedSettings.emailTemplate || '',
          emailRecipients: parsedSettings.emailRecipients || [],
          transcriberService: parsedSettings.transcriberService || 'deepgram',
          transcriberThresholds: parsedSettings.transcriberThresholds || {
            deepgram: 0.6,
            whisper: 0.7,
            browser: 0.8,
          },
        });
      }
    } catch (error) {
      console.error('Error loading meeting settings:', error);
    }
  }, [user?.id]);

  // Save meeting settings 
  const saveMeetingSettings = useCallback(async (settings: Partial<MeetingSettingsState>) => {
    if (!user?.id) return;
    
    try {
      const currentSettings = localStorage.getItem(`meetingSettings_${user.id}`);
      const existing = currentSettings ? JSON.parse(currentSettings) : defaultSettings;
      
      const updatedSettings = {
        ...existing,
        ...settings
      };
      
      localStorage.setItem(`meetingSettings_${user.id}`, JSON.stringify(updatedSettings));
      setMeetingSettings(updatedSettings);
    } catch (error) {
      console.error('Error saving meeting settings:', error);
    }
  }, [user?.id]);

  // Load settings on mount
  useEffect(() => {
    loadMeetingSettings();
  }, [loadMeetingSettings]);

  // Sync attendees and agenda from Meeting Settings into summary content
  useEffect(() => {
    setSummaryContent(prev => {
      const next = { ...prev } as typeof prev;
      let changed = false;
      const mAtt = (meetingSettings.participants || []).join(', ');
      if (mAtt && mAtt !== prev.attendees) { next.attendees = mAtt; changed = true; }
      return changed ? next : prev;
    });
  }, [meetingSettings.participants]);

  return {
    meetingData,
    setMeetingData,
    isSaving,
    isSaved,
    setIsSaved,
    meetingSettings,
    setMeetingSettings,
    summaryContent,
    setSummaryContent,
    practiceData,
    saveMeetingToDatabase,
    loadExistingSummary,
    fetchPracticeData,
    saveMeetingSettings
  };
};