import { useState } from 'react';

interface TranslationContent {
  title: string;
  subtitle: string;
  sessionInfo: string;
  patientInfo: string;
  translationLogHeader: string;
  speakerLabels: {
    gp: string;
    patient: string;
  };
}

interface PracticeInfo {
  name: string;
  address: string;
  phone?: string;
}

interface TranslatedContent {
  title: string;
  subtitle: string;
  sessionInfo: string;
  patientInfo: string;
  translationLogHeader: string;
  speakerLabels: {
    gp: string;
    patient: string;
  };
  practiceInfo: {
    name: string;
    address: string;
    phone: string;
  };
  practiceInfoHeader: string;
  generalLabels: {
    reportGenerated: string;
    sessionDate: string;
    sessionStart: string;
    sessionEnd: string;
    duration: string;
    patientLanguage: string;
    totalTranslations: string;
    time: string;
    speaker: string;
    originalText: string;
    translation: string;
    practice: string;
    address: string;
    phone: string;
  };
  patientInfoText: string;
  disclaimerText: string;
  reportGeneratedBy: string;
}

export const usePatientDocumentTranslation = () => {
  const [isTranslating, setIsTranslating] = useState(false);
  const [translationError, setTranslationError] = useState<string | null>(null);

  const translatePatientDocument = async (
    targetLanguage: string,
    practiceInfo: PracticeInfo
  ): Promise<TranslatedContent | null> => {
    console.log(`Target language for translation: "${targetLanguage}"`);
    
    // Handle undefined or null language - fallback to English
    if (!targetLanguage) {
      console.log('No target language provided - using English fallback');
      targetLanguage = 'english';
    }
    
    // Only skip translation for explicit English values
    if (targetLanguage === 'en' || targetLanguage.toLowerCase() === 'english') {
      console.log('Skipping translation - English language detected');
      return {
        title: "Notewell AI Translation Service - Patient Copy",
        subtitle: "Summary of Translation Session for Your Records",
        sessionInfo: "Session Information",
        patientInfo: "Patient Information", 
        translationLogHeader: "Translation Record",
        speakerLabels: {
          gp: "GP",
          patient: "Patient"
        },
        practiceInfo: {
          name: practiceInfo.name,
          address: practiceInfo.address,
          phone: practiceInfo.phone || ''
        },
        practiceInfoHeader: "Practice Information",
        generalLabels: {
          reportGenerated: "Report Generated",
          sessionDate: "Session Date",
          sessionStart: "Session Start",
          sessionEnd: "Session End", 
          duration: "Duration",
          patientLanguage: "Patient Language",
          totalTranslations: "Total Translations",
          time: "Time",
          speaker: "Speaker",
          originalText: "Original Text",
          translation: "Translation",
          practice: "Practice",
          address: "Address",
          phone: "Phone"
        },
        patientInfoText: "This document contains a record of all translations made during your medical consultation. This is provided for your personal records and reference.",
        disclaimerText: "IMPORTANT DISCLAIMER: This is an automated translation service for communication assistance only. All medical decisions should be based on professional clinical judgement.",
        reportGeneratedBy: "Report generated by Notewell AI Translation Tool"
      };
    }

    // Translation service not yet implemented - return English content
    // TODO: Implement edge function for document translation when needed
    console.log(`Translation requested for ${targetLanguage} - returning English content for now`);
    setIsTranslating(true);
    
    // Simulate a brief delay to show loading state
    await new Promise(resolve => setTimeout(resolve, 300));
    
    setIsTranslating(false);
    
    return {
      title: "Notewell AI Translation Service - Patient Copy",
      subtitle: "Summary of Translation Session for Your Records",
      sessionInfo: "Session Information",
      patientInfo: "Patient Information", 
      translationLogHeader: "Translation Record",
      speakerLabels: {
        gp: "GP",
        patient: "Patient"
      },
      practiceInfo: {
        name: practiceInfo.name,
        address: practiceInfo.address,
        phone: practiceInfo.phone || ''
      },
      practiceInfoHeader: "Practice Information",
      generalLabels: {
        reportGenerated: "Report Generated",
        sessionDate: "Session Date",
        sessionStart: "Session Start",
        sessionEnd: "Session End", 
        duration: "Duration",
        patientLanguage: "Patient Language",
        totalTranslations: "Total Translations",
        time: "Time",
        speaker: "Speaker",
        originalText: "Original Text",
        translation: "Translation",
        practice: "Practice",
        address: "Address",
        phone: "Phone"
      },
      patientInfoText: "This document contains a record of all translations made during your medical consultation. This is provided for your personal records and reference.",
      disclaimerText: "IMPORTANT DISCLAIMER: This is an automated translation service for communication assistance only. All medical decisions should be based on professional clinical judgement.",
      reportGeneratedBy: "Report generated by Notewell AI Translation Tool"
    };
  };

  return {
    translatePatientDocument,
    isTranslating,
    translationError
  };
};