export interface GeneratedImage {
  url: string;
  alt: string;
  prompt: string;
  requestType?: 'chart' | 'diagram' | 'infographic' | 'calendar' | 'poster' | 'general';
}

export interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  files?: UploadedFile[];
  responseTime?: number;
  timeToFirstWords?: number;
  apiResponseTime?: number;
  model?: string;
  isStreaming?: boolean;
  isClinical?: boolean;
  clinicalVerification?: ClinicalVerificationData;
  isQuickPick?: boolean; // Flag to identify messages from quick pick actions
  webSearchPerformed?: boolean; // Flag to indicate real-time web search was used
  generatedImages?: GeneratedImage[]; // Images generated by AI4GP image generation
}

export interface ClinicalVerificationData {
  confidenceScore: number; // 0-100
  sourcesVerified: VerificationSource[];
  llmConsensus: LLMConsensusData[];
  verificationStatus: 'pending' | 'verified' | 'flagged';
  riskLevel: 'low' | 'medium' | 'high';
  evidenceSummary?: string;
}

export interface VerificationSource {
  source: string;
  url?: string;
  trustLevel: 'high' | 'medium' | 'low';
  verified: boolean;
}

export interface LLMConsensusData {
  model: string;
  service?: string;
  assessment: string;
  agreementLevel: number; // 0-100
  concerns?: string[];
}

export interface UploadedFile {
  name: string;
  type: string;
  content: string;
  size: number;
  isLoading?: boolean;
  metadata?: {
    hasNumericalData?: boolean;
    wordCount?: number;
    issues?: string[];
  };
}

export interface SearchHistory {
  id: string;
  title: string;
  brief_overview?: string;
  messages: Message[];
  created_at: string;
  updated_at: string;
  is_protected?: boolean;
  is_flagged?: boolean;
}

export interface PracticeContext {
  practiceName?: string;
  practiceManagerName?: string;
  pcnName?: string;
  neighbourhoodName?: string;
  otherPracticesInPCN?: string[];
  logoUrl?: string;
  // Enhanced practice details
  practiceAddress?: string;
  practicePhone?: string;
  practiceEmail?: string;
  practiceWebsite?: string;
  // User details
  userFullName?: string;
  userEmail?: string;
  userRole?: string;
  userRoles?: string[];
  emailSignature?: string;
  letterSignature?: string;
  // Organisation type (for non-GP organisations like ICB, PCN, LMC, Management)
  organisationType?: string;
}

export const SUPPORTED_VOICES = ["alloy","ash","ballad","coral","echo","sage","shimmer","verse"] as const;

export type SupportedVoice = typeof SUPPORTED_VOICES[number];