export interface MeetingData {
  id?: string;
  title: string;
  duration: string;
  wordCount: number;
  transcript: string;
  speakerCount: number;
  startTime: string;
  practiceName?: string;
  practiceId?: string;
  meetingFormat?: string;
  generatedNotes?: string;
  mixedAudioBlob?: Blob;
  leftAudioBlob?: Blob;
  rightAudioBlob?: Blob;
  startedBy?: string;
  needsAudioBackup?: boolean;
  audioBackupBlob?: Blob | null;
  participants?: string[];
  agenda?: string;
  meetingLocation?: string;
  autoGeneratedName?: string;
  meetingContext?: any;
  attendees?: string[];
}

export interface MeetingSettingsState {
  roomName: string;
  participants: string[];
  reminderTime: number;
  enableAutoEmail: boolean;
  emailTemplate: string;
  emailRecipients: string[];
  transcriberService: 'deepgram' | 'whisper' | 'browser';
  transcriberThresholds: {
    deepgram: number;
    whisper: number;
    browser: number;
  };
}

export interface SummaryContent {
  attendees: string;
  agenda: string;
  keyPoints: string;
  decisions: string;
  actionItems: string;
  nextSteps: string;
  additionalNotes: string;
}

export interface AudioBackupInfo {
  file_path: string;
  file_size: number;
  meeting_id: string;
}

export interface CleanProgress {
  done: number;
  total: number;
}