import React from 'react';
import { parseLetterContent, FormattedContent } from '@/utils/letterFormatter';

interface FormattedLetterContentProps {
  content: string;
}

export const FormattedLetterContent: React.FC<FormattedLetterContentProps> = ({ content }) => {
  
  // Extract practice logo URL from HTML comment if present
  const logoUrlMatch = content.match(/<!--\s*logo_url:\s*(https?:\/\/[^\s\n]+)\s*-->/);
  const logoUrl = logoUrlMatch ? logoUrlMatch[1] : null;
  
  // Remove the logo metadata comment from content for parsing
  const cleanContent = content.replace(/<!--\s*logo_url:.*?-->\s*\n*/g, '');
  const formattedContent = parseLetterContent(cleanContent);
  
  // Check if content contains practice header information
  const hasLetterhead = content.includes('Medical Practice') || content.includes('Medical Centre');
  
  const renderFormattedContent = (content: FormattedContent[]): JSX.Element[] => {
    const elements: JSX.Element[] = [];
    let currentParagraph: JSX.Element[] = [];
    let paragraphKey = 0;
    let isHeaderSection = true;

    content.forEach((item, index) => {
      if (item.type === 'text' && item.content === '\n') {
        // End current paragraph
        if (currentParagraph.length > 0) {
          const paragraphContent = currentParagraph.map(el => {
            if (React.isValidElement(el)) {
              const props = el.props as any;
              return typeof props.children === 'string' ? props.children : '';
            }
            return '';
          }).join('');
          
          // Check if this is a header/letterhead line
          const isHeaderLine = isHeaderSection && (
            paragraphContent.includes('Medical Practice') ||
            paragraphContent.includes('Medical Centre') ||
            paragraphContent.includes('Tel:') ||
            paragraphContent.includes('Email:') ||
            paragraphContent.includes('Private & Confidential') ||
            /^\d{1,2}\s+(January|February|March|April|May|June|July|August|September|October|November|December)/.test(paragraphContent)
          );

          elements.push(
            <p key={paragraphKey} className={`mb-4 leading-relaxed ${
              isHeaderLine 
                ? 'text-center font-semibold text-lg text-primary' 
                : 'text-sm'
            }`}>
              {currentParagraph}
            </p>
          );
          currentParagraph = [];
          paragraphKey++;
          
          // Stop treating as header after date line
          if (paragraphContent.includes('202')) {
            isHeaderSection = false;
          }
        } else {
          // Empty line for spacing
          elements.push(<br key={`br-${index}`} />);
        }
      } else if (item.type === 'bold') {
        currentParagraph.push(
          <strong key={`bold-${index}`} className="font-bold text-gray-900">
            {item.content}
          </strong>
        );
      } else if (item.type === 'text') {
        const text = item.content.replace('\n', '');
        if (text) {
          currentParagraph.push(
            <span key={`text-${index}`}>{text}</span>
          );
        }
      }
    });

    // Add any remaining paragraph
    if (currentParagraph.length > 0) {
      elements.push(
        <p key={paragraphKey} className="mb-4 leading-relaxed text-sm">
          {currentParagraph}
        </p>
      );
    }

    return elements;
  };

  return (
    <div className="max-w-4xl mx-auto bg-white">
      {/* Practice Logo and Letterhead */}
      {hasLetterhead && (
        <div className="border-b border-gray-200 pb-6 mb-6">
          <div className="flex items-center justify-between">
            {logoUrl && (
              <div className="flex-shrink-0">
                <img 
                  src={logoUrl} 
                  alt="Practice Logo" 
                  className="h-16 w-auto object-contain"
                  onError={(e) => {
                    // Hide image if it fails to load
                    e.currentTarget.style.display = 'none';
                  }}
                />
              </div>
            )}
            <div className={`${logoUrl ? 'flex-1 ml-6' : 'w-full'} text-right`}>
              <div className="text-sm text-gray-600">
                NHS Complaint Letter
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Letter Content */}
      <div className="font-serif text-base leading-relaxed space-y-4">
        {renderFormattedContent(formattedContent)}
      </div>

      {/* Footer */}
      <div className="mt-8 pt-4 border-t border-gray-200 text-xs text-gray-500 text-center">
        This letter was generated by the NHS Complaints Management System
      </div>
    </div>
  );
};