import React, { useMemo, useState, useEffect } from "react";
import { Clock, Calendar, FileText, Play, Square, Timer } from "lucide-react";

// GP Scribe – SOAP Notes UI with Transcript Demo
// - Dropdown of 15 common templates
// - GP Shorthand / Standard toggle
// - Summary Line (copy)
// - Tabs: Consultation Summary / Patient Copy / Referral / Review & Recs / Transcript
// - Transcript demo per template (specific for top 5, autogenerated for others)
// - Copy helpers for SOAP and transcript lines

type Soap = { S: string; O: string; A: string; P: string };
type Template = {
  id: string;
  name: string;
  category?: string;
  summaryLine: string;
  shorthand: Soap;
  standard: Soap;
  patientCopy?: string;
  referral?: string;
  review?: string;
};
type TranscriptEntry = { t: string; speaker: "Patient" | "Clinician" | "Other"; text: string };

export default function GPScribeSoapMock() {
  const TEMPLATES: Template[] = [
    {
      id: "urti",
      name: "General Consultation (URTI)",
      category: "Acute Illness",
      summaryLine: "URTI 3/7, well, safety-net",
      shorthand: {
        S: "pt c/o sore throat 3/7, blocked nose, cough now productive; chills yest; paracetamol partial relief; no SOB/CP",
        O: "Obs WNL, chest clear, nodes small, throat red, no wheeze",
        A: "Viral URTI",
        P: "Reassure, fluids, paracetamol, safety-net if fever >5/7, SOB, CP or rash",
      },
      standard: {
        S: "Patient reports 3-day history of sore throat, blocked nose and cough becoming productive. Subjective fever/chills yesterday. Partial relief with paracetamol. Denies shortness of breath or chest pain.",
        O: "Observations within normal limits. Chest clear. Mild cervical lymphadenopathy. Oropharynx erythematous. No wheeze.",
        A: "Likely viral upper respiratory tract infection.",
        P: "Reassurance. Advise fluids and regular paracetamol. Safety-net: seek care if symptoms worsen, fever persists beyond 5 days, shortness of breath, chest pain or new rash.",
      },
      patientCopy:
        "You have a viral upper respiratory infection (a common cold). Drink plenty of fluids, rest and use paracetamol for fever/sore throat. Seek help urgently if breathing becomes difficult, chest pain develops, or you feel much worse.",
      referral:
        "Not indicated today. Consider if persistent symptoms >3w or red flags (hemoptysis, weight loss, recurrent infections).",
      review: "Self-care, OTC meds, safety-net documented. No antibiotics given.",
    },
    {
      id: "t2dm",
      name: "Long-Term Condition Review (Diabetes)",
      category: "Chronic",
      summaryLine: "T2DM stable; HbA1c ↓; cont Rx; rpt 3/12",
      shorthand: {
        S: "DM review; no hypo sx; diet stable; meds compliant",
        O: "BP 128/78; BMI 29; HbA1c 52 (prev 58); feet NAD",
        A: "T2DM – stable; improving control",
        P: "Continue meds; reinforce diet/ex; repeat HbA1c 3/12; retinal screen up to date",
      },
      standard: {
        S: "Attends for routine diabetes review. No hypoglycaemia symptoms. Adhering to medication and diet.",
        O: "BP 128/78, BMI 29. HbA1c 52 mmol/mol (previously 58). Foot exam normal.",
        A: "Type 2 diabetes mellitus – stable with improving glycaemic control.",
        P: "Continue current medications. Reinforce diet and exercise. Repeat HbA1c in 3 months. Confirm retinal screening status.",
      },
      patientCopy:
        "Your diabetes is stable and improving. Continue your current tablets, healthy diet and physical activity. We'll repeat your HbA1c blood test in 3 months.",
      referral: "No routine referral required. Consider DSN if HbA1c worsens or hypo concerns.",
      review: "QOF checks complete; foot check done; follow-up 3/12.",
    },
    {
      id: "depression",
      name: "Mental Health (Depression)",
      category: "MH",
      summaryLine: "Mild depression; IAPT referral; FU 4/52; safety-net",
      shorthand: {
        S: "Low mood, ↓sleep; no SI; coping at work",
        O: "Affect flat; eye contact ok; no psychotic features",
        A: "Mild depression",
        P: "Self-help info; IAPT referral; consider SSRI if no improvement; FU 4/52; safety-net provided",
      },
      standard: {
        S: "Reports low mood and reduced sleep. Denies suicidal ideation. Managing work responsibilities.",
        O: "Flat affect; maintains eye contact; no psychosis.",
        A: "Mild depressive episode.",
        P: "Provided self-help resources and referred to IAPT. Consider SSRI if no improvement. Safety-net advice given. Review in 4 weeks.",
      },
      patientCopy:
        "Your symptoms are consistent with mild depression. We've referred you to talking therapies (IAPT). Try the self-help resources provided. If you feel unsafe or develop suicidal thoughts, seek urgent help (111/999/A&E).",
      referral: "IAPT referral submitted today.",
      review: "PHQ-9 to be repeated at FU; crisis plan documented.",
    },
    {
      id: "uti",
      name: "UTI (Cystitis)",
      category: "Acute Illness",
      summaryLine: "UTI 3/7; nitrofurantoin 100mg MR bd 3/7; safety-net pyelo",
      shorthand: {
        S: "Dysuria, freq, urgency 3/7; no fever; no loin pain",
        O: "Dip +nitrites +leuks; afebrile",
        A: "Lower UTI",
        P: "Nitrofurantoin 3/7; fluids; safety-net for pyelonephritis red flags",
      },
      standard: {
        S: "Three days of dysuria, urinary frequency and urgency. No fever or loin pain.",
        O: "Urine dip positive for nitrites and leukocytes. Afebrile.",
        A: "Lower urinary tract infection (uncomplicated).",
        P: "Nitrofurantoin 100 mg modified-release twice daily for 3 days. Encourage fluids. Safety-net for pyelonephritis red flags (fever, flank pain, vomiting).",
      },
      patientCopy:
        "You have a bladder infection. Take nitrofurantoin as prescribed and drink plenty of fluids. Seek urgent help if you get fever, back/flank pain or vomiting.",
      referral: "Not required today unless recurrent/complicated.",
      review: "If unresolved after course, send MSU and review.",
    },
    {
      id: "lbp",
      name: "Musculoskeletal (Back Pain)",
      category: "MSK",
      summaryLine: "Mech LBP 5/7; no red flags; advice+analgesia",
      shorthand: {
        S: "Back pain 5/7; no red flags; better with rest",
        O: "Gait normal; neuro NAD; SLR negative",
        A: "Mechanical lower back pain",
        P: "Advice, activity modification, simple analgesia PRN, physio info, safety-net",
      },
      standard: {
        S: "Five days of lower back pain. Denies red flags (weakness, incontinence, weight loss). Pain improves with rest.",
        O: "Normal gait; neurological exam normal; straight-leg raise negative.",
        A: "Mechanical lower back pain.",
        P: "Provide advice and activity modification. Simple analgesia as required. Physio/self-management leaflet. Safety-net for red flags.",
      },
      patientCopy:
        "Your back pain is mechanical (muscle/joint strain). Keep gently active, avoid bed rest, and use simple pain relief if needed. See a clinician urgently if you develop leg weakness, numbness in the saddle area, or bladder/bowel problems.",
      referral: "Physio if persisting >6w or recurrent; urgent pathway if red flags.",
      review: "FU PRN; consider MSK pathway if not improving.",
    },

    // Placeholders for the remaining 10 (content autogenerates transcript)
    ..."Respiratory (Asthma/COPD Review)|Cardiac (Chest Pain / ?Angina)|Child Consultation (Fever)|Elderly / Multimorbidity|Women's Health (Contraception / HRT)|Palliative Care Review|ENT (Otitis / Tonsillitis)|Dermatology (Eczema / Rash)|Gastrointestinal (Abdo pain / Diarrhoea)|Medication Review / Polypharmacy"
      .split("|")
      .map((name, idx) => {
        const id = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
        return {
          id,
          name,
          category: idx === 0 ? "Review" : "",
          summaryLine: `${name} – example summary line`,
          shorthand: { S: "Example shorthand S", O: "Example shorthand O", A: "Example shorthand A", P: "Example shorthand P" },
          standard: { S: "Example standard S", O: "Example standard O", A: "Example standard A", P: "Example standard P" },
          patientCopy: "Plain-English patient copy goes here.",
          referral: "Referral guidance goes here.",
          review: "Review & recommendations notes go here.",
        } as Template;
      }),
  ];

  const [selectedId, setSelectedId] = useState<string>(TEMPLATES[0].id);
  const [mode, setMode] = useState<"shorthand" | "standard">("shorthand");
  const [tab, setTab] = useState<"summary" | "patient" | "referral" | "review" | "transcript">("summary");

  // Demo transcripts for the top 5 + default generator for others
  const SPECIFIC_TRANSCRIPTS: Record<string, TranscriptEntry[]> = {
    urti: [
      { t: "00:00", speaker: "Clinician", text: "Hello, I'm Dr Smith. Can I confirm your name and DOB?" },
      { t: "00:08", speaker: "Patient", text: "Yes, it's Alex Jones, 12th March 1989." },
      { t: "00:15", speaker: "Clinician", text: "What can I help with today?" },
      { t: "00:18", speaker: "Patient", text: "I've had a sore throat and blocked nose for three days, now coughing stuff up." },
      { t: "00:32", speaker: "Clinician", text: "Any shortness of breath or chest pain?" },
      { t: "00:35", speaker: "Patient", text: "No, none of that. I had chills yesterday." },
      { t: "01:10", speaker: "Clinician", text: "Exam normal today, sounds like a viral infection. I'll share self-care and safety-netting." },
    ],
    t2dm: [
      { t: "00:00", speaker: "Clinician", text: "Here for diabetes review — any hypos or concerns?" },
      { t: "00:07", speaker: "Patient", text: "No hypos. Been taking tablets and watching diet." },
      { t: "00:20", speaker: "Clinician", text: "Great. We'll check BP and feet, and discuss your HbA1c result of 52." },
    ],
    depression: [
      { t: "00:00", speaker: "Clinician", text: "How have your mood and sleep been?" },
      { t: "00:05", speaker: "Patient", text: "Low, sleeping badly. No thoughts of harming myself." },
      { t: "00:20", speaker: "Clinician", text: "Thanks for sharing — we can refer to IAPT and plan a review in 4 weeks." },
    ],
    uti: [
      { t: "00:00", speaker: "Patient", text: "It stings when I pass urine and I'm going more often." },
      { t: "00:10", speaker: "Clinician", text: "Any fever or pain in your back/flank?" },
      { t: "00:14", speaker: "Patient", text: "No fever, no back pain." },
    ],
    lbp: [
      { t: "00:00", speaker: "Patient", text: "Lower back pain for 5 days — worse after lifting boxes." },
      { t: "00:10", speaker: "Clinician", text: "Any leg weakness, numbness in the saddle area, or bladder/bowel issues?" },
      { t: "00:15", speaker: "Patient", text: "None of those." },
    ],
  };

  const autoTranscript = (name: string): TranscriptEntry[] => [
    { t: "00:00", speaker: "Clinician", text: `Let's talk about your ${name.toLowerCase().split(" (")[0]}.` },
    { t: "00:10", speaker: "Patient", text: "I've noticed symptoms over the last few days; they're a bit better today." },
    { t: "00:25", speaker: "Clinician", text: "Thanks. I'll summarize what I've heard and explain the plan." },
  ];

  const activeTemplate = useMemo(() => TEMPLATES.find((t) => t.id === selectedId)!, [selectedId]);
  const soap = mode === "shorthand" ? activeTemplate.shorthand : activeTemplate.standard;

  const [transcript, setTranscript] = useState<TranscriptEntry[]>([]);
  const [q, setQ] = useState("");

  useEffect(() => {
    const specific = SPECIFIC_TRANSCRIPTS[selectedId];
    setTranscript(specific ?? autoTranscript(activeTemplate.name));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedId]);

  const copy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied to clipboard");
    } catch {
      alert("Copy failed – select and copy manually.");
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800">
      {/* Top bar */}
      <div className="sticky top-0 z-10 border-b bg-white/80 backdrop-blur">
        <div className="mx-auto max-w-5xl px-4 py-3 flex items-center gap-4">
          <div className="flex-1">
            <h1 className="text-xl font-semibold tracking-tight">{activeTemplate.name}</h1>
            <p className="text-xs text-slate-500">{activeTemplate.category || "Consultation"} • demo transcript</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => copy(activeTemplate.summaryLine)}
              className="rounded-full border px-3 py-1.5 text-xs hover:bg-slate-100"
              title="Copy Summary Line"
            >
              Copy Summary Line
            </button>
            <button
              onClick={() => window.print()}
              className="rounded-full border px-3 py-1.5 text-xs hover:bg-slate-100"
              title="Print/Save PDF"
            >
              Export PDF
            </button>
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-5xl px-4 py-6 space-y-6">
        {/* Template + Mode */}
        <div className="grid grid-cols-1 gap-3 md:grid-cols-3">
          <div className="md:col-span-2">
            <label className="block text-xs font-medium text-slate-500 mb-1">Template</label>
            <select
              value={selectedId}
              onChange={(e) => setSelectedId(e.target.value)}
              className="w-full rounded-xl border bg-white px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-sky-400"
            >
              {TEMPLATES.map((t) => (
                <option key={t.id} value={t.id}>
                  {t.name}
                </option>
              ))}
            </select>
          </div>
          <div className="md:col-span-1">
            <label className="block text-xs font-medium text-slate-500 mb-1">Format</label>
            <div className="flex items-center gap-2 rounded-xl border bg-white p-2 shadow-sm">
              <button
                onClick={() => setMode("shorthand")}
                className={`flex-1 rounded-lg px-3 py-2 text-sm ${mode === "shorthand" ? "bg-sky-500 text-white" : "hover:bg-slate-100"}`}
              >
                GP Shorthand
              </button>
              <button
                onClick={() => setMode("standard")}
                className={`flex-1 rounded-lg px-3 py-2 text-sm ${mode === "standard" ? "bg-sky-500 text-white" : "hover:bg-slate-100"}`}
              >
                Standard Detail
              </button>
            </div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex items-center gap-2 text-sm">
          {[
            { id: "summary", label: "Consultation Summary" },
            { id: "patient", label: "Patient Copy" },
            { id: "referral", label: "Referral" },
            { id: "review", label: "Review & Recommendations" },
            { id: "transcript", label: "Transcript" },
          ].map(({ id, label }) => (
            <button
              key={id}
              onClick={() => setTab(id as any)}
              className={`rounded-lg px-3 py-2 ${tab === id ? "bg-sky-600 text-white" : "bg-white border hover:bg-slate-50"}`}
            >
              {label}
            </button>
          ))}
        </div>

        {/* Summary Line */}
        <div className="rounded-2xl border bg-white p-3 shadow-sm">
          <div className="flex items-center justify-between gap-3">
            <p className="text-sm">
              <span className="font-semibold">Summary Line:</span> {activeTemplate.summaryLine}
            </p>
            <button onClick={() => copy(activeTemplate.summaryLine)} className="rounded-lg border px-2 py-1 text-xs hover:bg-slate-100">
              Copy
            </button>
          </div>
        </div>

        {/* Panels */}
        {tab === "summary" && (
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <SoapCard title="S – Subjective" icon="📝" text={soap.S} tone="sky" mono={mode === "shorthand"} />
            <SoapCard title="O – Objective" icon="🩺" text={soap.O} tone="emerald" mono={mode === "shorthand"} />
            <SoapCard title="A – Assessment" icon="🔎" text={soap.A} tone="amber" mono={false} />
            <SoapCard title="P – Plan" icon="✅" text={soap.P} tone="violet" mono={false} />
          </div>
        )}

        {tab === "patient" && <PlainCard title="Patient Copy" body={activeTemplate.patientCopy || "Patient-friendly summary will appear here."} />}
        {tab === "referral" && <PlainCard title="Referral" body={activeTemplate.referral || "Referral text/criteria will appear here."} />}
        {tab === "review" && (
          <PlainCard title="Review & Recommendations" body={activeTemplate.review || "Follow-up plan, safety-netting and recommendations go here."} />
        )}

        {tab === "transcript" && (
          <div className="space-y-4">
            {/* Recording Summary */}
            <div className="rounded-2xl border bg-gradient-to-r from-blue-50 to-sky-50 p-4 shadow-sm">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="flex items-center gap-3">
                  <div className="flex items-center justify-center w-10 h-10 rounded-full bg-green-100">
                    <Play className="h-5 w-5 text-green-600" />
                  </div>
                  <div>
                    <p className="text-xs font-medium text-slate-600">Started</p>
                    <div className="flex items-center gap-1">
                      <Calendar className="h-3 w-3 text-slate-500" />
                      <p className="text-sm font-semibold">18 Aug 2025</p>
                    </div>
                    <div className="flex items-center gap-1">
                      <Clock className="h-3 w-3 text-slate-500" />
                      <p className="text-sm font-semibold">14:32:15</p>
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center gap-3">
                  <div className="flex items-center justify-center w-10 h-10 rounded-full bg-red-100">
                    <Square className="h-5 w-5 text-red-600" />
                  </div>
                  <div>
                    <p className="text-xs font-medium text-slate-600">Stopped</p>
                    <div className="flex items-center gap-1">
                      <Calendar className="h-3 w-3 text-slate-500" />
                      <p className="text-sm font-semibold">18 Aug 2025</p>
                    </div>
                    <div className="flex items-center gap-1">
                      <Clock className="h-3 w-3 text-slate-500" />
                      <p className="text-sm font-semibold">{
                        transcript.length > 0 
                          ? (() => {
                              const lastTime = transcript[transcript.length - 1]?.t || "00:00";
                              const [minutes, seconds] = lastTime.split(':').map(Number);
                              const totalMinutes = minutes + Math.floor(seconds / 60);
                              const remainingSeconds = seconds % 60;
                              const endTime = new Date();
                              endTime.setHours(14, 32 + totalMinutes, 15 + remainingSeconds);
                              return endTime.toTimeString().slice(0, 8);
                            })()
                          : "14:32:15"
                      }</p>
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className="flex items-center justify-center w-10 h-10 rounded-full bg-orange-100">
                    <Timer className="h-5 w-5 text-orange-600" />
                  </div>
                  <div>
                    <p className="text-xs font-medium text-slate-600">Duration</p>
                    <p className="text-lg font-bold text-slate-800">
                      {transcript.length > 0 ? transcript[transcript.length - 1]?.t || "00:00" : "00:00"}
                    </p>
                    <p className="text-xs text-slate-500">mm:ss</p>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className="flex items-center justify-center w-10 h-10 rounded-full bg-purple-100">
                    <FileText className="h-5 w-5 text-purple-600" />
                  </div>
                  <div>
                    <p className="text-xs font-medium text-slate-600">Words Recorded</p>
                    <p className="text-lg font-bold text-slate-800">
                      {transcript.reduce((total, entry) => total + entry.text.split(' ').length, 0)}
                    </p>
                    <p className="text-xs text-slate-500">
                      {transcript.length > 0 
                        ? `${Math.round(transcript.reduce((total, entry) => total + entry.text.split(' ').length, 0) / 
                            (parseInt(transcript[transcript.length - 1]?.t.split(':')[0] || "1") * 60 + 
                             parseInt(transcript[transcript.length - 1]?.t.split(':')[1] || "0")) * 60)} words/min`
                        : "0 words/min"
                      }
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Transcript Controls */}
            <div className="rounded-2xl border bg-white p-4 shadow-sm space-y-3">
              <div className="flex items-center gap-2">
                <input
                  className="flex-1 rounded-lg border px-3 py-2 text-sm"
                  placeholder="Search transcript (e.g. cough, chest, fever)"
                  value={q}
                  onChange={(e) => setQ(e.target.value)}
                />
                <button
                  onClick={() => copy(JSON.stringify(transcript, null, 2))}
                  className="rounded-lg border px-3 py-2 text-sm hover:bg-slate-100"
                >
                  Copy JSON
                </button>
                <button onClick={() => window.print()} className="rounded-lg border px-3 py-2 text-sm hover:bg-slate-100">
                  Export PDF
                </button>
              </div>
              <div className="space-y-2 max-h-[60vh] overflow-auto pr-1">
                {transcript
                  .filter((e) => !q || e.text.toLowerCase().includes(q.toLowerCase()))
                  .map((e, i) => (
                    <div key={i} className="flex gap-3 rounded-xl border p-3">
                      <div className="w-16 shrink-0 text-xs text-slate-500">{e.t}</div>
                      <div className="flex-1">
                        <div className="mb-1 flex items-center gap-2">
                          <span
                            className={`rounded-full px-2 py-0.5 text-xs ${
                              e.speaker === "Clinician"
                                ? "bg-sky-100 text-sky-700"
                                : e.speaker === "Patient"
                                ? "bg-emerald-100 text-emerald-700"
                                : "bg-slate-100 text-slate-700"
                            }`}
                          >
                            {e.speaker}
                          </span>
                          <div className="ml-auto flex items-center gap-1">
                            <button
                              onClick={() => copy(`S: ${e.text}`)}
                              className="rounded border px-2 py-1 text-xs hover:bg-slate-50"
                              title="Copy to Subjective"
                            >
                              → S
                            </button>
                            <button
                              onClick={() => copy(`O: ${e.text}`)}
                              className="rounded border px-2 py-1 text-xs hover:bg-slate-50"
                              title="Copy to Objective"
                            >
                              → O
                            </button>
                          </div>
                        </div>
                        <p className="text-sm">{e.text}</p>
                      </div>
                    </div>
                  ))}
              </div>
            </div>
          </div>
        )}

        {/* Footer action bar */}
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="text-xs text-slate-500">Design mock • SOAP + Transcript demo • Copy helpers</div>
          <div className="flex items-center gap-2">
            <button onClick={() => copy(renderSoap(soap))} className="rounded-lg border px-3 py-2 text-sm hover:bg-slate-100">
              Copy SOAP
            </button>
            <button onClick={() => copy(activeTemplate.patientCopy || "")} className="rounded-lg border px-3 py-2 text-sm hover:bg-slate-100">
              Copy Patient Copy
            </button>
            <button onClick={() => window.print()} className="rounded-lg border px-3 py-2 text-sm hover:bg-slate-100">
              Export PDF
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function SoapCard({
  title,
  icon,
  text,
  tone = "sky",
  mono = false,
}: {
  title: string;
  icon: string;
  text: string;
  tone?: "sky" | "emerald" | "amber" | "violet";
  mono?: boolean;
}) {
  const toneMap: Record<string, string> = {
    sky: "bg-sky-50 border-sky-200",
    emerald: "bg-emerald-50 border-emerald-200",
    amber: "bg-amber-50 border-amber-200",
    violet: "bg-violet-50 border-violet-200",
  };
  return (
    <div
      className={`rounded-2xl border ${toneMap[tone]} p-4 shadow-sm`}
      style={{ boxShadow: "0 1px 0 rgba(2,6,23,0.04), 0 1px 2px rgba(2,6,23,0.08)" }}
    >
      <div className="mb-2 flex items-center gap-2">
        <span className="text-lg" aria-hidden>
          {icon}
        </span>
        <h3 className="text-sm font-semibold tracking-tight">{title}</h3>
      </div>
      <p className={`text-sm ${mono ? "font-mono" : ""}`}>{text}</p>
    </div>
  );
}

function PlainCard({ title, body }: { title: string; body: string }) {
  return (
    <div className="rounded-2xl border bg-white p-4 shadow-sm">
      <h3 className="mb-2 text-sm font-semibold tracking-tight">{title}</h3>
      <p className="whitespace-pre-wrap text-sm">{body}</p>
    </div>
  );
}

function renderSoap(s: { S: string; O: string; A: string; P: string }) {
  return `S: ${s.S}\nO: ${s.O}\nA: ${s.A}\nP: ${s.P}`;
}