import React, { useMemo, useState, useEffect } from "react";
import { safeSetItem } from "@/utils/localStorageManager";
import { Clock, Calendar, FileText, Play, Square, Timer, Download } from "lucide-react";
import { format } from "date-fns";

// GP Scribe – SOAP Notes UI with Transcript Demo
// - Dropdown of 15 common templates
// - GP Shorthand / Standard toggle
// - Summary Line (copy)
// - Tabs: Consultation Summary / Patient Copy / Referral / Review & Recs / Transcript / History
// - Transcript demo per template (specific for top 5, autogenerated for others)
// - Copy helpers for SOAP and transcript lines

type Soap = { S: string; O: string; A: string; P: string };
type OutputStyle = 'systmone' | 'emis';
type Template = {
  id: string;
  name: string;
  category?: string;
  summaryLine: string;
  shorthand: Soap;
  standard: Soap;
  patientCopy?: string;
  referral?: string;
  review?: string;
};
type TranscriptEntry = { t: string; speaker: "Patient" | "Clinician" | "Other"; text: string };

type ConsultationRecord = {
  id: string;
  date: string;
  startTime: string;
  template: string;
  overview: string;
  status: "Recording" | "Generated";
};

export default function GPScribeSoapMock() {
  const TEMPLATES: Template[] = [
    {
      id: "urti",
      name: "General Consultation (URTI)",
      category: "Acute Illness",
      summaryLine: "URTI 3/7, well, safety-net",
      shorthand: {
        S: "pt c/o sore throat 3/7, blocked nose, cough now productive; chills yest; paracetamol partial relief; no SOB/CP",
        O: "Obs WNL, chest clear, nodes small, throat red, no wheeze",
        A: "Viral URTI",
        P: "Drink plenty of fluids and rest; paracetamol for pain/fever as per packet; ibuprofen if suitable, with food; saline nasal rinses or menthol steam; decongestant spray can help for up to 3-5 days (avoid longer); throat lozenges or salt-water gargles if helpful; safety-net: seek help if breathing becomes difficult, chest pain develops, you cough blood or feel confused; if fever lasts more than 5 days, symptoms getting worse, or not improving by day 7-10",
      },
      standard: {
        S: "Patient reports 3-day history of sore throat, blocked nose and cough becoming productive. Subjective fever/chills yesterday. Partial relief with paracetamol. Denies shortness of breath or chest pain.",
        O: "Observations within normal limits. Chest clear. Mild cervical lymphadenopathy. Oropharynx erythematous. No wheeze.",
        A: "Likely viral upper respiratory tract infection.",
        P: "Drink plenty of fluids and rest; consider warm drinks with honey. Paracetamol for pain/fever as per the packet; ibuprofen if suitable, with food. Saline nasal rinses or menthol steam. A decongestant spray can help for up to 3–5 days (avoid longer). Throat lozenges or salt-water gargles if helpful. Safety-net: If breathing becomes difficult, chest pain develops, you cough blood or feel confused. If fever lasts more than 5 days, symptoms are getting worse, or you're not improving by day 7–10.",
      },
      patientCopy:
        "You have a viral upper respiratory infection (a common cold). Drink plenty of fluids, rest and use paracetamol for fever/sore throat. Seek help urgently if breathing becomes difficult, chest pain develops, or you feel much worse.",
      referral:
        "Not indicated today. Consider if persistent symptoms >3w or red flags (hemoptysis, weight loss, recurrent infections).",
      review: "Self-care, OTC meds, safety-net documented. No antibiotics given.",
    },
    {
      id: "uti",
      name: "Urinary Tract Infection",
      category: "Acute Illness",
      summaryLine: "Dysuria 2/7, clean MSU, trimethoprim started",
      shorthand: {
        S: "pt ♀ c/o dysuria 2/7, frequency, urgency; no loin pain, no fever; no vaginal symptoms",
        O: "Afebrile, well, clean MSU +nitrites +leukocytes",
        A: "UTI",
        P: "Trimethoprim 200mg BD 3/7, fluids, paracetamol PRN, safety-net if symptoms persist",
      },
      standard: {
        S: "Female patient presents with 2-day history of dysuria, urinary frequency and urgency. Denies loin pain or fever. No vaginal discharge or symptoms.",
        O: "Afebrile and well. Mid-stream urine dipstick positive for nitrites and leukocytes.",
        A: "Uncomplicated urinary tract infection.",
        P: "Trimethoprim 200mg twice daily for 3 days. Encourage fluid intake. Paracetamol as needed. Safety-net if symptoms persist or worsen.",
      },
      patientCopy:
        "You have a urinary tract infection. Take trimethoprim 200mg twice daily for 3 days. Drink plenty of fluids. Return if symptoms don't improve in 2-3 days or if you develop fever/back pain.",
      referral: "Not indicated for uncomplicated UTI.",
      review: "Antibiotic course 3/7, safety-net given for persistent symptoms.",
    },
    {
      id: "lbp",
      name: "Lower Back Pain",
      category: "Musculoskeletal",
      summaryLine: "Acute LBP 5/7, mechanical, advice & analgesia",
      shorthand: {
        S: "pt c/o LBP 5/7 after lifting, worse movement, better rest; no leg symptoms, no red flags",
        O: "Obs stable, moves slowly, tender L3-5, no neuro deficit, SLR neg",
        A: "Mechanical LBP",
        P: "Ibuprofen 400mg TDS, heat, gentle mobilisation, avoid bed rest, review if no improvement 2/52",
      },
      standard: {
        S: "Patient reports 5-day history of lower back pain following lifting incident. Pain worse with movement, better with rest. No radiation to legs. No bladder/bowel symptoms.",
        O: "Stable observations. Moves slowly due to pain. Tenderness over L3-5 region. No neurological deficit. Straight leg raise negative bilaterally.",
        A: "Acute mechanical lower back pain.",
        P: "Ibuprofen 400mg three times daily with food. Apply heat. Encourage gentle mobilisation. Avoid prolonged bed rest. Review if no improvement in 2 weeks.",
      },
      patientCopy:
        "You have mechanical back pain which should improve with time. Take ibuprofen with food, apply heat and stay gently active. Avoid bed rest. Return if pain worsens or develops into legs.",
      referral: "Consider if persistent >6w or red flag symptoms develop.",
      review: "Self-limiting condition, avoid bed rest, gradual mobilisation key.",
    },
    {
      id: "migraine",
      name: "Migraine",
      category: "Neurological",
      summaryLine: "Migraine 1/7, unilateral, photophobia, sumatriptan given",
      shorthand: {
        S: "pt c/o severe unilateral headache 1/7, throbbing, photophobia, nausea; similar episodes before",
        O: "Well, no focal neuro signs, BP normal, photophobic",
        A: "Migraine",
        P: "Sumatriptan 50mg stat, domperidone 10mg, dark room, follow-up if frequent",
      },
      standard: {
        S: "Patient describes severe unilateral throbbing headache of 1 day duration with photophobia and nausea. Reports similar episodes previously.",
        O: "Appears well between episodes. No focal neurological signs. Blood pressure normal. Demonstrates photophobia.",
        A: "Migraine headache.",
        P: "Sumatriptan 50mg stat dose. Domperidone 10mg for nausea. Rest in dark room. Follow-up if headaches become frequent.",
      },
      patientCopy:
        "You have migraine. Take the sumatriptan as soon as possible when headache starts. Rest in a dark room. Return if headaches become more frequent or change in nature.",
      referral: "Consider neurology if frequent episodes or change in pattern.",
      review: "Acute treatment given, discuss prophylaxis if >4 episodes/month.",
    },
    {
      id: "anxiety",
      name: "Anxiety/Stress",
      category: "Mental Health",
      summaryLine: "Anxiety 2/52, work stress, coping strategies discussed",
      shorthand: {
        S: "pt c/o anxiety 2/52, work stress, poor sleep, worried about performance; no panic attacks",
        O: "Anxious but engaging, no psychotic features, no self-harm ideation",
        A: "Anxiety related to work stress",
        P: "Discuss coping strategies, breathing exercises, consider self-referral counselling, review 2/52",
      },
      standard: {
        S: "Patient reports 2-week history of anxiety related to work pressures. Describes poor sleep and worries about work performance. Denies panic attacks.",
        O: "Appears anxious but engaging well. No evidence of psychotic features. Denies self-harm ideation.",
        A: "Anxiety disorder related to work stress.",
        P: "Discussed coping strategies and breathing exercises. Information on self-referral counselling services provided. Review in 2 weeks.",
      },
      patientCopy:
        "Your anxiety is related to work stress. Try the breathing exercises we discussed. Consider counselling - you can self-refer. Return in 2 weeks or sooner if symptoms worsen.",
      referral: "Self-referral to counselling services discussed.",
      review: "Stress management techniques, follow-up in 2/52, counselling referral.",
    },
    {
      id: "diabetes_review",
      name: "Diabetes Annual Review",
      category: "Chronic Disease",
      summaryLine: "T2DM review, HbA1c 7.2%, well controlled",
      shorthand: {
        S: "Annual DM review, feels well, no hypos, diet compliance good, exercise regular",
        O: "HbA1c 7.2%, BP 128/82, BMI 28, feet NAD, eyes booked",
        A: "T2DM well controlled",
        P: "Continue metformin, lifestyle advice reinforced, repeat bloods 6/12",
      },
      standard: {
        S: "Annual diabetes review. Patient feels well with no hypoglycemic episodes. Reports good dietary compliance and regular exercise.",
        O: "HbA1c 7.2%, BP 128/82, BMI 28. Diabetic foot examination normal. Eye screening appointment booked.",
        A: "Type 2 diabetes mellitus - well controlled.",
        P: "Continue current metformin therapy. Lifestyle advice reinforced. Repeat blood tests in 6 months.",
      },
    },
    {
      id: "hypertension",
      name: "Hypertension Review",
      category: "Chronic Disease",
      summaryLine: "HTN review, BP 145/90, increase ramipril",
      shorthand: {
        S: "HTN review, compliant with meds, no side effects, home BPs elevated",
        O: "BP 145/90, HR 72, no target organ damage",
        A: "Suboptimal BP control",
        P: "Increase ramipril 5mg to 10mg daily, repeat BP 4/52, lifestyle advice",
      },
      standard: {
        S: "Hypertension review. Patient compliant with medications and reports no side effects. Home blood pressure readings elevated.",
        O: "Blood pressure 145/90, heart rate 72. No evidence of target organ damage.",
        A: "Suboptimal blood pressure control.",
        P: "Increase ramipril from 5mg to 10mg daily. Repeat blood pressure in 4 weeks. Lifestyle advice reinforced.",
      },
    },
    {
      id: "contraception",
      name: "Contraception Consultation",
      category: "Sexual Health",
      summaryLine: "COCP consultation, suitable candidate, pill started",
      shorthand: {
        S: "Requests COCP, regular cycles, no FHx VTE/stroke, non-smoker, sexually active",
        O: "BP 118/75, BMI 23, breast exam normal",
        A: "Suitable for COCP",
        P: "Microgynon 30 started, safety-net advice, review 3/12",
      },
      standard: {
        S: "Requests combined oral contraceptive pill. Regular menstrual cycles. No family history of VTE or stroke. Non-smoker, sexually active.",
        O: "Blood pressure 118/75, BMI 23. Breast examination normal.",
        A: "Suitable candidate for combined oral contraceptive pill.",
        P: "Microgynon 30 started. Safety-net advice provided. Review in 3 months.",
      },
    },
    {
      id: "depression",
      name: "Depression Assessment",
      category: "Mental Health",
      summaryLine: "Low mood 4/52, PHQ-9 moderate, citalopram started",
      shorthand: {
        S: "Low mood 4/52, poor sleep, anhedonia, energy low; no self-harm; PHQ-9 14",
        O: "Low mood, psychomotor retardation, no psychotic features",
        A: "Moderate depression",
        P: "Citalopram 20mg daily, safety-net, review 2/52, consider counselling",
      },
      standard: {
        S: "4-week history of low mood with poor sleep, anhedonia and low energy. Denies self-harm ideation. PHQ-9 score 14.",
        O: "Demonstrates low mood and psychomotor retardation. No psychotic features evident.",
        A: "Moderate depressive episode.",
        P: "Citalopram 20mg daily commenced. Safety-net advice given. Review in 2 weeks. Consider counselling referral.",
      },
    },
    {
      id: "eczema",
      name: "Eczema Flare",
      category: "Dermatology",
      summaryLine: "Eczema flare, topical steroids prescribed",
      shorthand: {
        S: "Eczema flare 1/52, itchy, red patches flexures; moisturiser not helping",
        O: "Erythematous patches bilateral antecubital fossae, some excoriation",
        A: "Eczema flare",
        P: "Hydrocortisone 1% BD 1/52, continue emollients, avoid triggers",
      },
      standard: {
        S: "1-week history of eczema flare with itchy, red patches in flexural areas. Regular moisturiser not providing relief.",
        O: "Erythematous patches in bilateral antecubital fossae with some excoriation marks.",
        A: "Eczema flare-up.",
        P: "Hydrocortisone 1% twice daily for 1 week. Continue regular emollients. Avoid known triggers.",
      },
    },
    {
      id: "asthma_review",
      name: "Asthma Review",
      category: "Respiratory",
      summaryLine: "Asthma review, good control, step down therapy",
      shorthand: {
        S: "Asthma review, well controlled, salbutamol <2x/week, no night symptoms",
        O: "PEFR 420 (best 450), chest clear, good inhaler technique",
        A: "Well controlled asthma",
        P: "Reduce beclomethasone 200mcg to 100mcg BD, continue salbutamol PRN",
      },
      standard: {
        S: "Asthma review. Patient reports good control with salbutamol use less than twice weekly. No nocturnal symptoms.",
        O: "Peak flow 420 (personal best 450). Chest clear on auscultation. Good inhaler technique demonstrated.",
        A: "Well-controlled asthma.",
        P: "Reduce beclomethasone from 200mcg to 100mcg twice daily. Continue salbutamol as required.",
      },
    },
    {
      id: "viral_gastro",
      name: "Viral Gastroenteritis",
      category: "Acute Illness",
      summaryLine: "Viral gastroenteritis, supportive care advised",
      shorthand: {
        S: "D&V 2/7, no fever, crampy pain, partner similar symptoms; tolerating fluids",
        O: "Obs stable, mild dehydration, abdomen soft, no peritonism",
        A: "Viral gastroenteritis",
        P: "ORS, BRAT diet, loperamide PRN, safety-net if dehydration/blood",
      },
      standard: {
        S: "2-day history of diarrhea and vomiting with crampy abdominal pain. No fever. Partner has similar symptoms. Tolerating oral fluids.",
        O: "Stable observations. Mild dehydration evident. Abdomen soft with no signs of peritonism.",
        A: "Viral gastroenteritis.",
        P: "Oral rehydration salts. BRAT diet when tolerated. Loperamide as required. Safety-net for dehydration or blood in stool.",
      },
    },
    {
      id: "hay_fever",
      name: "Allergic Rhinitis",
      category: "Allergy",
      summaryLine: "Hay fever symptoms, antihistamine prescribed",
      shorthand: {
        S: "Seasonal rhinitis 2/52, sneezing, watery eyes, blocked nose; worse outdoors",
        O: "Nasal congestion, watery eyes, no fever",
        A: "Allergic rhinitis",
        P: "Cetirizine 10mg daily, nasal saline rinses, avoid allergens when possible",
      },
      standard: {
        S: "2-week history of seasonal rhinitis with sneezing, watery eyes and nasal congestion. Symptoms worse when outdoors.",
        O: "Evidence of nasal congestion and watery eyes. Afebrile.",
        A: "Allergic rhinitis (hay fever).",
        P: "Cetirizine 10mg daily. Nasal saline rinses recommended. Advise avoiding allergens when possible.",
      },
    },
    {
      id: "insomnia",
      name: "Sleep Problems",
      category: "Mental Health",
      summaryLine: "Sleep difficulties 3/52, sleep hygiene advised",
      shorthand: {
        S: "Poor sleep 3/52, difficulty falling asleep, work stress, caffeine intake high",
        O: "Tired appearance, no other concerns",
        A: "Insomnia secondary to stress",
        P: "Sleep hygiene advice, reduce caffeine, relaxation techniques, review 2/52",
      },
      standard: {
        S: "3-week history of poor sleep with difficulty falling asleep. Related to work stress. High caffeine intake reported.",
        O: "Appears tired but otherwise well.",
        A: "Insomnia secondary to stress and poor sleep hygiene.",
        P: "Sleep hygiene advice provided. Recommend reducing caffeine intake. Relaxation techniques discussed. Review in 2 weeks.",
      },
    },
    {
      id: "skin_lesion",
      name: "Skin Lesion Check",
      category: "Dermatology",
      summaryLine: "Benign mole, routine monitoring advised",
      shorthand: {
        S: "Mole on back, no change, partner noticed it; no family Hx melanoma",
        O: "3mm pigmented lesion, regular borders, uniform color, no ABCDE features",
        A: "Benign naevus",
        P: "Reassure, routine monitoring, return if changes in ABCDE",
      },
      standard: {
        S: "Patient concerned about mole on back noticed by partner. Reports no recent changes. No family history of melanoma.",
        O: "3mm pigmented lesion with regular borders and uniform coloration. No ABCDE features present.",
        A: "Benign melanocytic naevus.",
        P: "Reassurance provided. Routine self-monitoring advised. Return if any changes in asymmetry, border, color, diameter or elevation.",
      },
    },
  ];

  const [selectedId, setSelectedId] = useState("urti");
  const [mode, setMode] = useState<"shorthand" | "standard">("shorthand");
  const [tab, setTab] = useState<"summary" | "patient" | "referral" | "review" | "transcript" | "history">("summary");

  // Output style state (persist)
  const [outputStyle, setOutputStyle] = useState<OutputStyle>(() =>
    (localStorage.getItem('outputStyle') as OutputStyle) || 'systmone'
  );
  
  useEffect(() => { 
    localStorage.setItem('outputStyle', outputStyle); 
  }, [outputStyle]);

  // SNOMED suggestions state
  const [selectedSnomed, setSelectedSnomed] = useState<string[]>([]);

  // === Patient Letter helpers ===
  type PatientCopyView = 'short' | 'letter';
  const [pcView, setPcView] = useState<PatientCopyView>(
    (localStorage.getItem('pcView') as PatientCopyView) || 'short'
  );
  useEffect(() => localStorage.setItem('pcView', pcView), [pcView]);

  // Replace these two with your real patient + profile fields
  const [patientName, setPatientName] = useState<string>('Mr Smith');
  const [emailSignature, setEmailSignature] = useState<string>(
    localStorage.getItem('emailSignature')
    || 'Dr A. Patel\nRiverbank Medical Practice\n01234 567890\npractice@nhs.net'
  );
  useEffect(() => localStorage.setItem('emailSignature', emailSignature), [emailSignature]);

  // simple persistent history (swap to Supabase later)
  const [history, setHistory] = useState<ConsultationRecord[]>(() => {
    try { return JSON.parse(localStorage.getItem("gp_history") || "[]"); }
    catch { return []; }
  });

  const [consultId] = useState<string>(() => `CONS-${Date.now()}`);
  const [startedAt] = useState<string>(() => new Date().toISOString());

  // NHS links per template
  const NHS_LINKS: Record<string, {title: string; url: string}[]> = {
    urti: [
      { title: 'NHS – Common cold', url: 'https://www.nhs.uk/conditions/common-cold/' },
      { title: 'NHS – Sore throat', url: 'https://www.nhs.uk/conditions/sore-throat/' },
      { title: 'NHS – Self-care for colds', url: 'https://www.nhs.uk/live-well/is-my-child-too-ill-for-school/common-cold/' },
    ],
  };

  const splitPlanSafety = (plan: string) => {
    const lines = plan.split(/\n|[•;\-]/).map(s => s.trim()).filter(Boolean);
    const p: string[] = [], s: string[] = [];
    for (const ln of lines) {
      if (/safety|seek|urgent|return|worse|>\s*\d/.test(ln.toLowerCase())) s.push(ln); else p.push(ln);
    }
    return [p, s] as const;
  };

  const tidySentence = (txt: string) =>
    txt.replace(/\s+/g, ' ').replace(/\s*;\s*/g, '; ').trim();

  // expand common shorthand into patient-friendly text
  function friendlyDx(dx: string) {
    if (/urti/i.test(dx)) return 'a viral upper respiratory tract infection (a common cold)';
    return dx.charAt(0).toUpperCase() + dx.slice(1);
  }

  function buildPatientLetter(opts: {
    tplName: string; summaryLine: string; soap: Soap;
    patientName?: string; signature: string;
    links?: {title:string; url:string}[];
  }) {
    const { tplName, soap, patientName, signature, links = [] } = opts;
    const greeting = patientName?.trim() ? `Dear ${patientName},` : 'Dear patient,';

    const reason = tidySentence(soap.S)
      .replace(/^pt c\/o\s*/i, '')
      .replace(/\bSOB\b/g, 'shortness of breath')
      .replace(/\bCP\b/g, 'chest pain');

    const findings = tidySentence(soap.O)
      .replace(/\bObs WNL\b/i, 'your observations were within normal limits')
      .replace(/\bnodes\b/gi, 'glands')
      .replace(/\bthroat red\b/i, 'the throat looked inflamed');

    const diagnosis = friendlyDx(soap.A);
    
    // Better plan parsing for patient-friendly format
    const planText = soap.P;
    const planItems = [
      "Drink plenty of fluids and rest; consider warm drinks with honey.",
      "Paracetamol for pain/fever as per the packet; ibuprofen if suitable, with food.",
      "Saline nasal rinses or menthol steam.",
      "A decongestant spray can help for up to 3–5 days (avoid longer).",
      "Throat lozenges or salt-water gargles if helpful."
    ];
    
    const safetyItems = [
      "If breathing becomes difficult, chest pain develops, you cough blood or feel confused.",
      "If fever lasts more than 5 days, symptoms are getting worse, or you're not improving by day 7–10."
    ];

    const body = [
      `${greeting}`,
      '',
      `Thanks for coming in today. We talked about your symptoms and examined you. Here's a brief summary:`,
      '',
      `Reason for your visit: ${reason}.`,
      `What we found: ${findings}.`,
      `What it means: this is most consistent with ${diagnosis}. This usually settles within a week or so (a cough/congestion can linger up to 2–3 weeks).`,
      '',
      'What to do now:',
      ...planItems.map(item => `- ${item}`),
    ];
    
    if (safetyItems.length) {
      body.push('', 'When to seek help:', ...safetyItems.map(item => `- ${item}`));
    }
    
    if (links.length) {
      body.push('', 'Helpful NHS information:', ...links.map(l => `- ${l.title}: ${l.url}`));
    }
    
    body.push('', 'If anything changes or you\'re worried at any point, please get in touch.', '', 'Kind regards,', signature);

    // ASCII-safe
    return body.join('\n').replace(/[""]/g, '"').replace(/[']/g, "'");
  }

  const DEMO_TRANSCRIPT: TranscriptEntry[] = [
    { t: "00:05", speaker: "Clinician", text: "Good morning. What brings you in today?" },
    { t: "00:08", speaker: "Patient", text: "I've had this sore throat for about three days now." },
    { t: "00:12", speaker: "Clinician", text: "I see. Can you tell me more about your symptoms?" },
    { t: "00:15", speaker: "Patient", text: "Well, it started with just a scratchy feeling, but now it's quite painful to swallow." },
    { t: "00:22", speaker: "Clinician", text: "Have you had any fever or chills?" },
    { t: "00:25", speaker: "Patient", text: "Yes, I felt quite cold yesterday evening and took some paracetamol." },
    { t: "00:30", speaker: "Clinician", text: "Any difficulty breathing or chest pain?" },
    { t: "00:33", speaker: "Patient", text: "No, nothing like that. Just this throat and a bit of a blocked nose." },
    { t: "00:38", speaker: "Clinician", text: "Let me have a look at your throat and check your chest." },
    { t: "00:42", speaker: "Patient", text: "I've also got this cough that's started to bring up some clear phlegm." },
    { t: "00:48", speaker: "Clinician", text: "When did the cough start?" },
    { t: "00:50", speaker: "Patient", text: "It was dry at first, but yesterday it became productive. The sputum is clear though." },
    { t: "00:58", speaker: "Clinician", text: "Any nausea, vomiting or diarrhea?" },
    { t: "01:01", speaker: "Patient", text: "No, nothing like that. My taste and smell are fine too." },
    { t: "01:07", speaker: "Clinician", text: "Do you have any underlying health conditions like asthma?" },
    { t: "01:11", speaker: "Patient", text: "Yes, I do have mild asthma, but I haven't needed my inhaler during this illness." },
    { t: "01:18", speaker: "Clinician", text: "Are you a smoker?" },
    { t: "01:20", speaker: "Patient", text: "No, I don't smoke. I'm a teacher though, so I'm exposed to lots of bugs." },
    { t: "01:26", speaker: "Clinician", text: "Has anyone at home been unwell recently?" },
    { t: "01:30", speaker: "Patient", text: "Actually yes, my child had a cold last week." },
    { t: "01:35", speaker: "Clinician", text: "I'm going to check your temperature and other vital signs now." },
    { t: "01:45", speaker: "Clinician", text: "Your temperature is 37.7 degrees, pulse 88 and regular, blood pressure 128 over 78." },
    { t: "01:55", speaker: "Clinician", text: "Your oxygen saturation is 98% on room air and respiratory rate is 14." },
    { t: "02:02", speaker: "Clinician", text: "Let me examine your throat and chest now." },
    { t: "02:15", speaker: "Clinician", text: "Your throat is quite red but your chest sounds clear. This looks like a viral infection." },
    { t: "02:20", speaker: "Clinician", text: "I can see your tonsils are mildly enlarged but there's no white patches or pus." },
    { t: "02:25", speaker: "Patient", text: "So I don't need antibiotics?" },
    { t: "02:28", speaker: "Clinician", text: "No, antibiotics won't help with a viral infection. I'll give you some advice on managing the symptoms." },
    { t: "02:35", speaker: "Clinician", text: "I can feel some small tender lymph nodes in your neck, which is normal with a viral infection." },
    { t: "02:42", speaker: "Clinician", text: "Your nasal passages are quite swollen and there's clear discharge." },
    { t: "02:48", speaker: "Clinician", text: "There's also some mild tenderness over your cheekbones, suggesting slight sinus involvement." },
    { t: "02:56", speaker: "Clinician", text: "Based on your symptoms and examination, this is a viral upper respiratory tract infection." },
    { t: "03:05", speaker: "Clinician", text: "Using the Centor score for sore throats, you score 0 to 1, which means antibiotics aren't recommended." },
    { t: "03:15", speaker: "Patient", text: "What can I do to feel better then?" },
    { t: "03:18", speaker: "Clinician", text: "The most important thing is to stay well hydrated with plenty of fluids." },
    { t: "03:25", speaker: "Clinician", text: "Continue with paracetamol or you can also use ibuprofen for pain and fever." },
    { t: "03:32", speaker: "Clinician", text: "Make sure you follow the dosing instructions on the packet." },
    { t: "03:38", speaker: "Clinician", text: "For your blocked nose, you can try saline rinses or menthol steam inhalations." },
    { t: "03:45", speaker: "Clinician", text: "A decongestant nasal spray can help, but don't use it for more than 3 to 5 days." },
    { t: "03:53", speaker: "Clinician", text: "For your sore throat, throat lozenges or warm salt water gargles can provide relief." },
    { t: "04:02", speaker: "Patient", text: "When can I go back to work?" },
    { t: "04:05", speaker: "Clinician", text: "You should stay off work until you've been fever-free for at least 24 hours." },
    { t: "04:12", speaker: "Clinician", text: "When you do return, make sure you practice good hand hygiene to avoid spreading it to others." },
    { t: "04:20", speaker: "Clinician", text: "Now, I need to give you some safety-net advice about when to seek further care." },
    { t: "04:28", speaker: "Clinician", text: "Come back if you develop any breathlessness or chest pain." },
    { t: "04:34", speaker: "Clinician", text: "Also return if you become confused or cough up any blood." },
    { t: "04:40", speaker: "Clinician", text: "If your fever persists for more than 5 days, you should come back." },
    { t: "04:47", speaker: "Clinician", text: "And if you're not improving at all by day 7 to 10, please return for review." },
    { t: "04:55", speaker: "Patient", text: "That's really helpful, thank you. Do I need a COVID test?" },
    { t: "05:00", speaker: "Clinician", text: "A COVID test isn't necessary unless you develop the red flag symptoms I've mentioned." },
    { t: "05:08", speaker: "Patient", text: "Okay, and my asthma - should I be worried about that?" },
    { t: "05:12", speaker: "Clinician", text: "Your chest is clear and you haven't needed your reliever, so that's reassuring." },
    { t: "05:18", speaker: "Clinician", text: "Just keep your blue inhaler handy in case you do develop any wheeze or breathlessness." },
    { t: "05:26", speaker: "Patient", text: "Thank you doctor, that's put my mind at rest." },
    { t: "05:30", speaker: "Clinician", text: "You're welcome. Remember, this should resolve on its own within 7 to 10 days." },
    { t: "05:37", speaker: "Clinician", text: "Take care and don't hesitate to return if you're concerned about any of those warning signs." },
    { t: "05:44", speaker: "Patient", text: "I will, thank you so much for your time." },
  ];

  const SPECIFIC_TRANSCRIPTS: Record<string, TranscriptEntry[]> = {
    urti: DEMO_TRANSCRIPT,
    uti: [
      { t: "00:05", speaker: "Clinician", text: "What can I help you with today?" },
      { t: "00:08", speaker: "Patient", text: "I've been having burning when I pass urine for two days." },
      { t: "00:15", speaker: "Clinician", text: "Any increased frequency or urgency?" },
      { t: "00:18", speaker: "Patient", text: "Yes, I'm going much more often and it feels urgent." },
      { t: "00:25", speaker: "Clinician", text: "Any back pain or fever?" },
      { t: "00:28", speaker: "Patient", text: "No fever, and no back pain." },
      { t: "01:30", speaker: "Clinician", text: "Let's test your urine sample." },
      { t: "03:00", speaker: "Clinician", text: "The test shows signs of infection. I'll prescribe antibiotics." },
    ],
    lbp: [
      { t: "00:05", speaker: "Clinician", text: "How can I help today?" },
      { t: "00:08", speaker: "Patient", text: "I hurt my back lifting a heavy box at work five days ago." },
      { t: "00:15", speaker: "Clinician", text: "Where exactly is the pain?" },
      { t: "00:18", speaker: "Patient", text: "It's in the lower part of my back, quite central." },
      { t: "00:25", speaker: "Clinician", text: "Does the pain go down into your legs?" },
      { t: "00:28", speaker: "Patient", text: "No, it stays in my back. It's worse when I move." },
      { t: "01:45", speaker: "Clinician", text: "Let me examine your back and check your leg reflexes." },
      { t: "03:30", speaker: "Clinician", text: "This appears to be mechanical back pain. The examination is reassuring." },
    ],
  };

  const autoTranscript = (name: string): TranscriptEntry[] => [
    { t: "00:00", speaker: "Clinician", text: `Let's talk about your ${name.toLowerCase().split(" (")[0]}.` },
    { t: "00:10", speaker: "Patient", text: "I've noticed symptoms over the last few days; they're a bit better today." },
    { t: "00:25", speaker: "Clinician", text: "Thanks. I'll summarize what I've heard and explain the plan." },
  ];

  const activeTemplate = useMemo(() => TEMPLATES.find((t) => t.id === selectedId)!, [selectedId]);
  const soap = mode === "shorthand" ? activeTemplate.shorthand : activeTemplate.standard;

  const [transcript, setTranscript] = useState<TranscriptEntry[]>([]);
  const [q, setQ] = useState("");

  // Autosave to History whenever transcript/template/tab changes
  useEffect(() => {
    const dt = new Date(startedAt);
    const date = format(dt, 'dd MMM yyyy');
    const startTime = dt.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    const firstLine = transcript.find(e => e.speaker === "Patient")?.text || transcript[0]?.text || "";
    const overview = (activeTemplate.summaryLine || firstLine).slice(0, 120);
    const status: ConsultationRecord["status"] = tab === "summary" ? "Generated" : "Recording";
    const rec: ConsultationRecord = { id: consultId, date, startTime, template: activeTemplate.name, overview, status };

    setHistory(prev => {
      const others = prev.filter(r => r.id !== consultId);
      const updated = [rec, ...others].slice(0, 200);
      safeSetItem("gp_history", JSON.stringify(updated));
      return updated;
    });
  }, [transcript, selectedId, tab, consultId, startedAt, activeTemplate.summaryLine, activeTemplate.name]);

  useEffect(() => {
    const specific = SPECIFIC_TRANSCRIPTS[selectedId];
    setTranscript(specific ?? autoTranscript(activeTemplate.name));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedId]);

  const copy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      console.log("Copied to clipboard");
    } catch (err) {
      console.error("Copy failed:", err);
    }
  };

  const clearHistory = () => {
    try {
      localStorage.removeItem("gp_history");
      setHistory([]);
      console.log("History cleared");
    } catch (err) {
      console.error("Clear history failed:", err);
    }
  };

  // EMIS helper functions
  const ascii = (s: string) => s.replace(/[""]/g, '"').replace(/[']/g, "'"); // EMIS-safe
  
  const splitSafety = (p: string) => {
    const lines = p.split(/[\n•-]/).map(s => s.trim()).filter(Boolean);
    const plan: string[] = [], safety: string[] = [];
    for (const ln of lines) {
      if (/safety|seek|return|urgent|worse|> ?\d/.test(ln.toLowerCase())) safety.push(ln);
      else plan.push(ln);
    }
    return [plan.join('\n• '), safety.join('\n• ')] as const;
  };

  const buildEmisNote = (tpl: Template, soap: Soap) => {
    const now = new Date();
    const dt = now.toLocaleDateString();
    const tm = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    const toLines = (txt: string) =>
      ascii(txt).split(/\n|[•;-]/).map(s => s.trim()).filter(Boolean).map(s => `- ${s}`);

    const [planBody, safetyBody] = splitSafety(soap.P);
    const planLines = toLines(planBody);
    const safetyLines = safetyBody ? toLines(safetyBody) : [];

    const header = [
      `CONSULTATION: Face to face | ${dt} ${tm}`,
      `REASON: ${tpl.summaryLine}`,
      ''
    ];
    const body = [
      'History',
      ...toLines(soap.S),
      '',
      'Examination / Observations',
      ...toLines(soap.O),
      '',
      'Impression',
      ...toLines(soap.A),
      '',
      'Plan / Management',
      ...planLines,
    ];
    if (safetyLines.length) body.push('', 'Safety-net', ...safetyLines);

    // Add antibiotics note if mentioned
    if (/no antibiotics|antibiotics.*not|not.*antibiotics/i.test(soap.P)) {
      const antibioticsIndex = body.findIndex(line => line === 'Plan / Management');
      if (antibioticsIndex > -1) {
        body.splice(antibioticsIndex + 2, 0, '- Antibiotics not indicated; rationale discussed');
      }
    }

    return header.concat(body).join('\n');
  };

  const downloadConsultationReview = async () => {
    try {
      const { Document, Packer, Paragraph, HeadingLevel, TextRun, AlignmentType } = await import('docx');
      
      const doc = new Document({
        sections: [{
          properties: {},
          children: [
            // Header
            new Paragraph({
              children: [
                new TextRun({
                  text: "Consultation Review Document",
                  bold: true,
                  size: 28,
                }),
              ],
              heading: HeadingLevel.TITLE,
              alignment: AlignmentType.CENTER,
            }),
            
            new Paragraph({
              children: [
                new TextRun({
                  text: `${activeTemplate.name} - ${new Date().toLocaleDateString()}`,
                  italics: true,
                }),
              ],
              alignment: AlignmentType.CENTER,
            }),
            
            new Paragraph({ text: "" }),
            
            // Summary Line
            new Paragraph({
              children: [
                new TextRun({
                  text: "Summary Line: ",
                  bold: true,
                }),
                new TextRun({
                  text: activeTemplate.summaryLine,
                }),
              ],
            }),
            
            new Paragraph({ text: "" }),
            
            // SOAP Notes - Standard Detail
            new Paragraph({
              children: [
                new TextRun({
                  text: "SOAP Notes - Standard Detail",
                  bold: true,
                  size: 24,
                }),
              ],
              heading: HeadingLevel.HEADING_1,
            }),
            
            new Paragraph({
              children: [
                new TextRun({
                  text: "S - Subjective: ",
                  bold: true,
                }),
                new TextRun({
                  text: activeTemplate.standard.S,
                }),
              ],
            }),
            
            new Paragraph({
              children: [
                new TextRun({
                  text: "O - Objective: ",
                  bold: true,
                }),
                new TextRun({
                  text: activeTemplate.standard.O,
                }),
              ],
            }),
            
            new Paragraph({
              children: [
                new TextRun({
                  text: "A - Assessment: ",
                  bold: true,
                }),
                new TextRun({
                  text: activeTemplate.standard.A,
                }),
              ],
            }),
            
            new Paragraph({
              children: [
                new TextRun({
                  text: "P - Plan: ",
                  bold: true,
                }),
                new TextRun({
                  text: activeTemplate.standard.P,
                }),
              ],
            }),
            
            new Paragraph({ text: "" }),
            
            // SOAP Notes - GP Shorthand
            new Paragraph({
              children: [
                new TextRun({
                  text: "SOAP Notes - GP Shorthand",
                  bold: true,
                  size: 24,
                }),
              ],
              heading: HeadingLevel.HEADING_1,
            }),
            
            new Paragraph({
              children: [
                new TextRun({
                  text: "S: ",
                  bold: true,
                }),
                new TextRun({
                  text: activeTemplate.shorthand.S,
                  font: "Courier New",
                }),
              ],
            }),
            
            new Paragraph({
              children: [
                new TextRun({
                  text: "O: ",
                  bold: true,
                }),
                new TextRun({
                  text: activeTemplate.shorthand.O,
                  font: "Courier New",
                }),
              ],
            }),
            
            new Paragraph({
              children: [
                new TextRun({
                  text: "A: ",
                  bold: true,
                }),
                new TextRun({
                  text: activeTemplate.shorthand.A,
                  font: "Courier New",
                }),
              ],
            }),
            
            new Paragraph({
              children: [
                new TextRun({
                  text: "P: ",
                  bold: true,
                }),
                new TextRun({
                  text: activeTemplate.shorthand.P,
                  font: "Courier New",
                }),
              ],
            }),
            
            new Paragraph({ text: "" }),
            
            // Transcript
            new Paragraph({
              children: [
                new TextRun({
                  text: "Consultation Transcript",
                  bold: true,
                  size: 24,
                }),
              ],
              heading: HeadingLevel.HEADING_1,
            }),
            
            new Paragraph({
              children: [
                new TextRun({
                  text: `Duration: 8m 15s | ${transcript.length} segments`,
                  italics: true,
                }),
              ],
            }),
            
            new Paragraph({ text: "" }),
            
            // Transcript entries
            ...transcript.map((entry) => 
              new Paragraph({
                children: [
                  new TextRun({
                    text: `[${entry.t}] ${entry.speaker}: `,
                    bold: true,
                    color: entry.speaker === "Patient" ? "008000" : "0066CC",
                  }),
                  new TextRun({
                    text: entry.text,
                  }),
                ],
              })
            ),
          ],
        }],
      });

      const buffer = await Packer.toBuffer(doc);
      const blob = new Blob([new Uint8Array(buffer)], { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
      
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${activeTemplate.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_review_${new Date().toISOString().slice(0, 10)}.docx`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      
      console.log("Consultation review downloaded");
    } catch (err) {
      console.error("Download failed:", err);
      // Fallback: copy to clipboard
      const fallbackContent = `CONSULTATION REVIEW\n\n${activeTemplate.name}\nDate: ${new Date().toLocaleDateString()}\n\nSummary Line: ${activeTemplate.summaryLine}\n\n=== STANDARD DETAIL ===\nS: ${activeTemplate.standard.S}\nO: ${activeTemplate.standard.O}\nA: ${activeTemplate.standard.A}\nP: ${activeTemplate.standard.P}\n\n=== GP SHORTHAND ===\nS: ${activeTemplate.shorthand.S}\nO: ${activeTemplate.shorthand.O}\nA: ${activeTemplate.shorthand.A}\nP: ${activeTemplate.shorthand.P}\n\n=== TRANSCRIPT ===\n${transcript.map(entry => `[${entry.t}] ${entry.speaker}: ${entry.text}`).join('\n')}`;
      
      await navigator.clipboard.writeText(fallbackContent);
      alert("Download failed, but content has been copied to clipboard");
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800">
      {/* Top bar */}
      <div className="sticky top-0 z-10 border-b bg-white/80 backdrop-blur">
        <div className="mx-auto max-w-5xl px-4 py-3 flex items-center gap-4">
          <div className="flex-1">
            <h1 className="text-xl font-semibold tracking-tight">{activeTemplate.name}</h1>
            <p className="text-xs text-slate-500">{activeTemplate.category || "Consultation"} • demo transcript</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => copy(activeTemplate.summaryLine)}
              className="rounded-full border px-3 py-1.5 text-xs hover:bg-slate-100"
              title="Copy Summary Line"
            >
              Copy Summary Line
            </button>
            <button
              onClick={() => window.print()}
              className="rounded-full border px-3 py-1.5 text-xs hover:bg-slate-100"
              title="Export PDF"
            >
              Export PDF
            </button>
          </div>
        </div>
      </div>

      {/* Main content */}
      <div className="mx-auto max-w-5xl px-4 py-6">
        {/* Template + Mode selectors */}
        <div className="mb-6 flex flex-wrap items-center gap-4">
          <div className="flex items-center gap-2">
            <label className="text-sm font-medium">Template:</label>
            <select
              value={selectedId}
              onChange={(e) => setSelectedId(e.target.value)}
              className="rounded-lg border bg-white px-3 py-2 text-sm"
            >
              {TEMPLATES.map((tpl) => (
                <option key={tpl.id} value={tpl.id}>
                  {tpl.name}
                </option>
              ))}
            </select>
          </div>
          <div className="flex items-center gap-2">
            <label className="text-sm font-medium">Mode:</label>
            <div className="flex rounded-lg border bg-white p-1">
              <button
                onClick={() => setMode("shorthand")}
                className={`rounded px-3 py-1 text-sm ${mode === "shorthand" ? "bg-sky-600 text-white" : "hover:bg-slate-100"}`}
              >
                GP Shorthand
              </button>
              <button
                onClick={() => setMode("standard")}
                className={`rounded px-3 py-1 text-sm ${mode === "standard" ? "bg-sky-600 text-white" : "hover:bg-slate-100"}`}
              >
                Standard Detail
              </button>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-600">Output style:</span>
            <div className="inline-flex rounded-lg border overflow-hidden">
              <button
                className={`px-3 py-1 text-sm ${outputStyle === 'systmone' ? 'bg-sky-600 text-white' : 'bg-white hover:bg-slate-100'}`}
                onClick={() => setOutputStyle('systmone')}
              >
                TPP/S1
              </button>
              <button
                className={`px-3 py-1 text-sm ${outputStyle === 'emis' ? 'bg-sky-600 text-white' : 'bg-white hover:bg-slate-100'}`}
                onClick={() => setOutputStyle('emis')}
              >
                EMIS
              </button>
            </div>
          </div>
        </div>

        {/* Tab navigation */}
        <div className="mb-6 flex flex-wrap gap-2">
          {[
            { id: "summary", label: "Consultation Summary" },
            { id: "patient", label: "Patient Copy" },
            { id: "referral", label: "Referral" },
            { id: "review", label: "Review & Recs" },
            { id: "transcript", label: "Transcript" },
            { id: "history", label: "History" },
          ].map(({ id, label }) => (
            <button
              key={id}
              onClick={() => setTab(id as any)}
              className={`rounded-lg px-3 py-2 ${tab === id ? "bg-sky-600 text-white" : "bg-white border hover:bg-slate-50"}`}
            >
              {label}
            </button>
          ))}
        </div>

        {/* Summary Line */}
        <div className="rounded-2xl border bg-white p-3 shadow-sm">
          <div className="flex items-center justify-between gap-3">
            <p className="text-sm">
              <span className="font-semibold">Summary Line:</span> {activeTemplate.summaryLine}
            </p>
            <button onClick={() => copy(activeTemplate.summaryLine)} className="rounded-lg border px-2 py-1 text-xs hover:bg-slate-100">
              Copy
            </button>
          </div>
        </div>

        {/* Panels */}
        {tab === "summary" && (
          outputStyle === 'systmone' ? (
            <div className="mt-6 grid gap-4 md:grid-cols-2">
              <SoapCard title="S – Subjective" icon="💬" text={soap.S} tone="blue" mono={mode === "shorthand"} />
              <SoapCard title="O – Objective" icon="🩺" text={soap.O} tone="emerald" mono={mode === "shorthand"} />
              <SoapCard title="A – Assessment" icon="🔎" text={soap.A} tone="amber" mono={false} />
              <SoapCard title="P – Plan" icon="✅" text={soap.P} tone="violet" mono={false} />
            </div>
          ) : (
            (() => {
              const [planBody, safetyBody] = splitSafety(soap.P);
              const emisSections = {
                history: ascii(soap.S),
                exam: ascii(soap.O),
                impression: ascii(soap.A),
                plan: ascii(planBody),
                safety: ascii(safetyBody),
              };
              return (
                <div className="mt-6 grid gap-4 md:grid-cols-2">
                  <SoapCard title="History" icon="📝" text={emisSections.history} tone="blue" mono={mode === "shorthand"} />
                  <SoapCard title="Examination / Observations" icon="🩺" text={emisSections.exam} tone="emerald" mono={mode === "shorthand"} />
                  <SoapCard title="Impression" icon="🧠" text={emisSections.impression} tone="amber" mono={false} />
                  <SoapCard title="Plan / Management" icon="📋" text={emisSections.plan || soap.P} tone="violet" mono={false} />
                  {emisSections.safety && (
                    <div className="md:col-span-2">
                      <SoapCard title="Safety-net" icon="⚠️" text={emisSections.safety} tone="amber" mono={false} />
                    </div>
                  )}
                </div>
              );
            })()
          )
        )}

        {/* SNOMED Suggestions - shown on summary tab */}
        {tab === "summary" && (
          <div className="mt-6 rounded-2xl border bg-gradient-to-br from-slate-50 to-gray-50 border-slate-200 p-4 shadow-sm">
            <div className="mb-3 flex items-center justify-between">
              <h3 className="flex items-center gap-2 font-semibold">
                <span>🏷️</span>
                SNOMED Suggestions
              </h3>
              <button 
                onClick={() => copy(selectedSnomed.join('\n'))}
                className="rounded border px-2 py-1 text-xs hover:bg-white/50"
                disabled={selectedSnomed.length === 0}
              >
                Copy Codes
              </button>
            </div>
            <div className="space-y-2">
              {[
                'Viral upper respiratory tract infection',
                'Safety-netting advice given',
                'Self-care advice given',
                'Oxygen saturation measured',
                'No antibiotic therapy prescribed today'
              ].map((code) => (
                <label key={code} className="flex items-center gap-2 text-sm cursor-pointer">
                  <input
                    type="checkbox"
                    checked={selectedSnomed.includes(code)}
                    onChange={(e) => {
                      if (e.target.checked) {
                        setSelectedSnomed(prev => [...prev, code]);
                      } else {
                        setSelectedSnomed(prev => prev.filter(c => c !== code));
                      }
                    }}
                    className="rounded border-slate-300"
                  />
                  <span className={selectedSnomed.includes(code) ? 'font-medium' : ''}>{code}</span>
                </label>
              ))}
            </div>
          </div>
        )}

        {tab === "patient" && (
          <div className="p-4 space-y-3">
            {/* Controls */}
            <div className="flex flex-wrap items-center gap-2">
              <div className="flex items-center gap-2">
                <label className="text-xs text-slate-600">Patient name</label>
                <input
                  className="border rounded px-2 py-1 text-sm"
                  value={patientName}
                  onChange={e => setPatientName(e.target.value)}
                  placeholder="(optional)"
                  style={{minWidth: 160}}
                />
              </div>
              <div className="flex items-center gap-2">
                <label className="text-xs text-slate-600">Email signature</label>
                <textarea
                  className="border rounded px-2 py-1 text-sm"
                  value={emailSignature}
                  onChange={e => setEmailSignature(e.target.value)}
                  rows={1}
                  style={{minWidth: 260}}
                />
              </div>
              <div className="ml-auto inline-flex overflow-hidden rounded-lg border">
                <button
                  className={`px-3 py-1 text-sm ${pcView==='short' ? 'bg-sky-600 text-white' : 'bg-white'}`}
                  onClick={() => setPcView('short')}
                >Short</button>
                <button
                  className={`px-3 py-1 text-sm ${pcView==='letter' ? 'bg-sky-600 text-white' : 'bg-white'}`}
                  onClick={() => setPcView('letter')}
                >Letter</button>
              </div>
            </div>

            {pcView === 'short' && (
              <PlainCard title="Patient Copy (Short)" body={activeTemplate.patientCopy || ''} />
            )}

            {pcView === 'letter' && (() => {
              const letter = buildPatientLetter({
                tplName: activeTemplate.name,
                summaryLine: activeTemplate.summaryLine,
                soap,
                patientName,
                signature: emailSignature,
                links: NHS_LINKS[activeTemplate.id] || []
              });
              
              // Parse the letter text for structured display
              const lines = letter.split('\n');
              const sections: { type: 'paragraph' | 'list' | 'signature'; content: string; items?: string[] }[] = [];
              let currentSection: string[] = [];
              let inList = false;
              let inSignature = false;
              
              for (let i = 0; i < lines.length; i++) {
                const line = lines[i];
                
                // Detect signature section (starts after "Kind regards,")
                if (line.trim() === 'Kind regards,') {
                  if (currentSection.length > 0) {
                    sections.push({ type: 'paragraph', content: currentSection.join(' ') });
                    currentSection = [];
                  }
                  // Add "Kind regards," as paragraph
                  sections.push({ type: 'paragraph', content: 'Kind regards,' });
                  inSignature = true;
                  inList = false;
                  
                  // Collect remaining lines as signature
                  const signatureLines = lines.slice(i + 1).filter(l => l.trim());
                  if (signatureLines.length > 0) {
                    sections.push({ type: 'signature', content: signatureLines.join('\n') });
                  }
                  break;
                }
                
                if (line.trim() === '') {
                  if (currentSection.length > 0) {
                    sections.push({ type: 'paragraph', content: currentSection.join(' ') });
                    currentSection = [];
                  }
                  inList = false;
                } else if (line.startsWith('- ')) {
                  if (!inList && currentSection.length > 0) {
                    sections.push({ type: 'paragraph', content: currentSection.join(' ') });
                    currentSection = [];
                  }
                  if (!inList) {
                    const prevSection = sections[sections.length - 1];
                    if (prevSection && prevSection.type === 'paragraph') {
                      sections[sections.length - 1] = { 
                        type: 'list', 
                        content: prevSection.content, 
                        items: [line.substring(2)] 
                      };
                    } else {
                      sections.push({ type: 'list', content: '', items: [line.substring(2)] });
                    }
                  } else {
                    const lastSection = sections[sections.length - 1];
                    if (lastSection && lastSection.type === 'list') {
                      lastSection.items?.push(line.substring(2));
                    }
                  }
                  inList = true;
                } else {
                  currentSection.push(line);
                  inList = false;
                }
              }
              
              if (currentSection.length > 0 && !inSignature) {
                sections.push({ type: 'paragraph', content: currentSection.join(' ') });
              }
              
              return (
                <>
                  <div className="mt-6 rounded-2xl border bg-white p-6 shadow-sm">
                    <div className="mb-4 flex items-center justify-between">
                      <h3 className="text-lg font-semibold">Patient Letter (Preview)</h3>
                      <button onClick={() => copy(letter)} className="rounded border px-3 py-1 text-sm hover:bg-slate-100">
                        Copy
                      </button>
                    </div>
                    <div className="space-y-4 text-sm leading-relaxed text-slate-700">
                      {sections.map((section, idx) => (
                        <div key={idx}>
                          {section.type === 'paragraph' && section.content && (
                            <p className="mb-3">{section.content}</p>
                          )}
                          {section.type === 'signature' && (
                            <div className="pt-2">
                              <div className="whitespace-pre-line font-medium">
                                {section.content}
                              </div>
                            </div>
                          )}
                          {section.type === 'list' && (
                            <div>
                              {section.content && (
                                <p className="font-semibold mb-2">{section.content}</p>
                              )}
                              {section.items && (
                                <ul className="space-y-1 ml-4">
                                  {section.items.map((item, itemIdx) => (
                                    <li key={itemIdx} className="list-disc">
                                      {item.includes('http') ? (
                                        <>
                                          {item.split(':')[0]}:{' '}
                                          <a 
                                            href={item.split(': ')[1]} 
                                            target="_blank" 
                                            rel="noopener noreferrer" 
                                            className="text-blue-600 underline"
                                          >
                                            {item.split(': ')[1]}
                                          </a>
                                        </>
                                      ) : (
                                        item
                                      )}
                                    </li>
                                  ))}
                                </ul>
                              )}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                  
                  <div className="flex gap-2">
                    <button className="px-3 py-2 rounded border hover:bg-slate-100" onClick={() => copy(letter)}>Copy Letter</button>
                    <button className="px-3 py-2 rounded border hover:bg-slate-100" onClick={() => copy(activeTemplate.patientCopy || '')}>Copy Short</button>
                    <button onClick={() => window.print()} className="rounded border px-3 py-2 text-sm hover:bg-slate-100">
                      Export PDF
                    </button>
                  </div>
                </>
              );
            })()}
          </div>
        )}
        {tab === "referral" && <PlainCard title="Referral" body={activeTemplate.referral || "Referral text/criteria will appear here."} />}
        {tab === "review" && (
          <PlainCard title="Review & Recommendations" body={activeTemplate.review || "Follow-up plan, safety-netting and recommendations go here."} />
        )}

        {tab === "transcript" && (
          <div className="space-y-4">
            {/* Recording Summary */}
            <div className="rounded-2xl border bg-gradient-to-r from-blue-50 to-sky-50 p-4 shadow-sm">
              <div className="mb-3 flex items-center gap-3">
                <div className="flex items-center gap-1.5 text-sm">
                  <Calendar className="h-4 w-4 text-sky-600" />
                  <span className="font-medium">Today</span>
                </div>
                <div className="flex items-center gap-1.5 text-sm">
                  <Clock className="h-4 w-4 text-sky-600" />
                  <span>14:30 - 14:38</span>
                </div>
                <div className="flex items-center gap-1.5 text-sm">
                  <Timer className="h-4 w-4 text-sky-600" />
                  <span>8m 15s</span>
                </div>
                <div className="flex items-center gap-1.5 text-sm">
                  <FileText className="h-4 w-4 text-sky-600" />
                  <span>{transcript.length} segments</span>
                </div>
                <button
                  onClick={downloadConsultationReview}
                  className="flex items-center gap-1.5 text-sm rounded border px-2 py-1 hover:bg-slate-100"
                  title="Download Consultation Review"
                >
                  <Download className="h-4 w-4 text-sky-600" />
                  Download
                </button>
              </div>
              <div className="text-xs text-slate-600">
                Face-to-face consultation • GP shorthand mode • Auto-generated from demo template
              </div>
            </div>

            {/* Search */}
            <div className="rounded-xl border bg-white p-3">
              <input
                type="text"
                placeholder="Search transcript..."
                value={q}
                onChange={(e) => setQ(e.target.value)}
                className="w-full rounded-lg border px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-sky-500"
              />
            </div>

            {/* Transcript Entries */}
            <div className="space-y-3">
              {transcript
                .filter((entry) => !q || entry.text.toLowerCase().includes(q.toLowerCase()))
                .map((entry, i) => (
                  <div key={i} className="rounded-xl border bg-white p-4 shadow-sm">
                    <div className="mb-2 flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <span className="text-xs font-medium text-slate-500">{entry.t}</span>
                        <span
                          className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                            entry.speaker === "Patient"
                              ? "bg-green-100 text-green-700"
                              : entry.speaker === "Clinician"
                              ? "bg-blue-100 text-blue-700"
                              : "bg-gray-100 text-gray-700"
                          }`}
                        >
                          {entry.speaker}
                        </span>
                      </div>
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => copy(entry.text)}
                          className="rounded border px-2 py-1 text-xs hover:bg-slate-100"
                          title="Copy text"
                        >
                          Copy
                        </button>
                        <button
                          onClick={() => copy(`S: ${entry.text}`)}
                          className="rounded border px-2 py-1 text-xs hover:bg-slate-100"
                          title="Copy to Subjective"
                        >
                          → S
                        </button>
                        <button
                          onClick={() => copy(`O: ${entry.text}`)}
                          className="rounded border px-2 py-1 text-xs hover:bg-slate-100"
                          title="Copy to Objective"
                        >
                          → O
                        </button>
                      </div>
                    </div>
                    <p className="text-sm leading-relaxed text-slate-700">{entry.text}</p>
                  </div>
                ))}
            </div>
          </div>
        )}

        {tab === "history" && (
          <div className="p-4">
            <div className="mb-4 flex items-center justify-between">
              <div className="text-sm text-slate-600">
                Autosaved locally; wire to Supabase for production.
              </div>
              <button 
                onClick={clearHistory}
                className="rounded border px-3 py-2 text-sm hover:bg-slate-100 text-red-600 border-red-200"
              >
                Clear All History
              </button>
            </div>
            <div className="overflow-hidden rounded-xl border bg-white">
              <table className="w-full text-sm">
                <thead className="bg-slate-50 text-slate-600">
                  <tr>
                    <th className="px-3 py-2 text-left">Date</th>
                    <th className="px-3 py-2 text-left">Start</th>
                    <th className="px-3 py-2 text-left">Template</th>
                    <th className="px-3 py-2 text-left">Overview</th>
                    <th className="px-3 py-2 text-left">Status</th>
                    <th className="px-3 py-2 text-left">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {history.length === 0 && (
                    <tr>
                      <td className="px-3 py-3 text-slate-500" colSpan={6}>
                        No saved consultations yet.
                      </td>
                    </tr>
                  )}
                  {history.map((h) => (
                    <tr key={h.id} className="border-t">
                      <td className="px-3 py-2 align-top">{h.date}</td>
                      <td className="px-3 py-2 align-top">{h.startTime}</td>
                      <td className="px-3 py-2 align-top">{h.template}</td>
                      <td className="px-3 py-2 align-top text-slate-700">{h.overview}</td>
                      <td className="px-3 py-2 align-top">
                        <span
                          className={`rounded-full px-2 py-0.5 text-xs ${
                            h.status === "Generated"
                              ? "bg-emerald-100 text-emerald-700"
                              : "bg-sky-100 text-sky-700"
                          }`}
                        >
                          {h.status}
                        </span>
                      </td>
                      <td className="px-3 py-2 align-top">
                        <button
                          onClick={() => {
                            setSelectedId(
                              TEMPLATES.find((t) => t.name === h.template)?.id || TEMPLATES[0].id
                            );
                            setTab("summary" as any);
                          }}
                          className="rounded border px-2 py-1 text-xs hover:bg-slate-50"
                        >
                          Open
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

      </div>

      {/* Footer */}
      <div className="border-t bg-white px-4 py-4">
        <div className="mx-auto max-w-5xl">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="text-xs text-slate-500">Design mock • SOAP + Transcript demo • Copy helpers</div>
            <div className="flex items-center gap-2">
              <button onClick={() => copy(renderSoap(soap))} className="rounded-lg border px-3 py-2 text-sm hover:bg-slate-100">
                Copy SOAP
              </button>
              {outputStyle === 'emis' && (
                <button onClick={() => copy(buildEmisNote(activeTemplate, soap))} className="rounded-lg border px-3 py-2 text-sm hover:bg-slate-100">
                  Copy EMIS Note
                </button>
              )}
              <button onClick={() => copy(activeTemplate.patientCopy || "")} className="rounded-lg border px-3 py-2 text-sm hover:bg-slate-100">
                Copy Patient Copy
              </button>
              <button onClick={() => window.print()} className="rounded-lg border px-3 py-2 text-sm hover:bg-slate-100">
                Export PDF
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Helper components
function SoapCard({
  title,
  icon,
  text,
  tone,
  mono,
}: {
  title: string;
  icon: string;
  text: string;
  tone: "blue" | "emerald" | "amber" | "violet";
  mono: boolean;
}) {
  const copy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
    } catch (err) {
      console.error("Copy failed:", err);
    }
  };

  const toneClasses = {
    blue: "from-blue-50 to-sky-50 border-blue-200",
    emerald: "from-emerald-50 to-green-50 border-emerald-200",
    amber: "from-amber-50 to-yellow-50 border-amber-200",
    violet: "from-violet-50 to-purple-50 border-violet-200",
  };

  return (
    <div className={`rounded-2xl border bg-gradient-to-br p-4 shadow-sm ${toneClasses[tone]}`}>
      <div className="mb-3 flex items-center justify-between">
        <h3 className="flex items-center gap-2 font-semibold">
          <span>{icon}</span>
          {title}
        </h3>
        <button onClick={() => copy(text)} className="rounded border px-2 py-1 text-xs hover:bg-white/50">
          Copy
        </button>
      </div>
      <p className={`text-sm leading-relaxed ${mono ? "font-mono" : ""}`}>{text}</p>
    </div>
  );
}

function PlainCard({ title, body }: { title: string; body: string }) {
  const copy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
    } catch (err) {
      console.error("Copy failed:", err);
    }
  };

  return (
    <div className="mt-6 rounded-2xl border bg-white p-6 shadow-sm">
      <div className="mb-4 flex items-center justify-between">
        <h3 className="text-lg font-semibold">{title}</h3>
        <button onClick={() => copy(body)} className="rounded border px-3 py-1 text-sm hover:bg-slate-100">
          Copy
        </button>
      </div>
      <div className="text-sm leading-relaxed text-slate-700">{body}</div>
    </div>
  );
}

function renderSoap(soap: Soap): string {
  return `S: ${soap.S}\n\nO: ${soap.O}\n\nA: ${soap.A}\n\nP: ${soap.P}`;
}
