import React, { useState, useEffect, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Mic, Square, Clock, FileText, Sparkles } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { useRecording } from '@/contexts/RecordingContext';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/hooks/use-toast';
import { useNavigate } from 'react-router-dom';
import { MeetingCompletionModal } from './MeetingCompletionModal';

interface MeetingRecordingInterfaceProps {
  onClose: () => void;
}

interface MeetingContextData {
  title: string;
  format: string;
  location: string;
  agenda: string;
  selectedAttendees: any[];
  participants: string[];
}

export const MeetingRecordingInterface: React.FC<MeetingRecordingInterfaceProps> = ({ onClose }) => {
  const { user } = useAuth();
  const { setRecordingState } = useRecording();
  const navigate = useNavigate();
  const [isRecording, setIsRecording] = useState(false);
  const [currentMeetingId, setCurrentMeetingId] = useState<string | null>(null);
  const [autoGeneratedTitle, setAutoGeneratedTitle] = useState('');
  const [transcript, setTranscript] = useState('');
  const [recordingTime, setRecordingTime] = useState(0);
  const [processingStatus, setProcessingStatus] = useState<'idle' | 'processing' | 'completed'>('idle');
  const [showCompletionModal, setShowCompletionModal] = useState(false);
  const [audioChunks, setAudioChunks] = useState<Blob[]>([]);

  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const intervalRef = useRef<NodeJS.Timeout | null>(null);
  const chunkIntervalRef = useRef<NodeJS.Timeout | null>(null);

  const generateAutoTitle = () => {
    const now = new Date();
    const roundedTime = new Date(Math.ceil(now.getTime() / (15 * 60 * 1000)) * (15 * 60 * 1000));
    return `Meeting Recorded on ${roundedTime.toLocaleDateString()} at ${roundedTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
  };

  const startRecording = async () => {
    console.log('🚀 startRecording called', { user: user?.id, navigator: !!navigator.mediaDevices });
    
    if (!user?.id) {
      console.error('❌ No user ID found');
      toast({ 
        title: "Authentication Error", 
        description: "Please log in to record meetings", 
        variant: "destructive" 
      });
      return;
    }

    if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
      console.error('❌ Media devices not supported');
      toast({ 
        title: "Not Supported", 
        description: "Your browser doesn't support audio recording", 
        variant: "destructive" 
      });
      return;
    }

    try {
      const title = generateAutoTitle();
      setAutoGeneratedTitle(title);

      console.log('🎙️ Starting recording process...', { user: user?.id, title });

      // Create meeting record immediately
      console.log('💾 Creating meeting record...');
      const { data: meeting, error: meetingError } = await supabase
        .from('meetings')
        .insert({
          title,
          auto_generated_name: title,
          user_id: user.id,
          start_time: new Date().toISOString(),
          status: 'recording',
          meeting_context: { recording_started: true }
        })
        .select()
        .single();

      if (meetingError) {
        console.error('❌ Failed to create meeting record:', meetingError);
        throw meetingError;
      }
      
      console.log('✅ Meeting record created:', meeting.id);
      setCurrentMeetingId(meeting.id);

      // Start audio recording with chunking
      console.log('🎤 Requesting media access...');
      
      const stream = await navigator.mediaDevices.getUserMedia({ 
        audio: { 
          sampleRate: 24000, 
          channelCount: 1, 
          echoCancellation: true,
          noiseSuppression: true,
          autoGainControl: true
        }
      });

      console.log('✅ Media access granted, stream tracks:', stream.getTracks().length);
      
      // Check MediaRecorder support
      const mimeType = MediaRecorder.isTypeSupported('audio/webm;codecs=opus') 
        ? 'audio/webm;codecs=opus' 
        : MediaRecorder.isTypeSupported('audio/webm') 
          ? 'audio/webm' 
          : MediaRecorder.isTypeSupported('audio/wav')
            ? 'audio/wav'
            : '';
      
      if (!mimeType) {
        console.error('❌ No supported audio format found');
        throw new Error('Browser does not support audio recording');
      }
      
      console.log('📹 Creating MediaRecorder with mimeType:', mimeType);
      const mediaRecorder = new MediaRecorder(stream, { mimeType });
      mediaRecorderRef.current = mediaRecorder;

      let chunkNumber = 0;
      
      mediaRecorder.ondataavailable = async (event) => {
        console.log(`📦 Data available: chunk ${chunkNumber}, size: ${event.data.size} bytes`);
        if (event.data.size > 0) {
          try {
            await storeAudioChunk(event.data, chunkNumber++, meeting.id);
            console.log(`✅ Chunk ${chunkNumber - 1} stored successfully`);
          } catch (chunkError) {
            console.error(`❌ Failed to store chunk ${chunkNumber - 1}:`, chunkError);
          }
        }
      };

      mediaRecorder.onstop = () => {
        console.log('⏹️ MediaRecorder stopped, cleaning up stream...');
        stream.getTracks().forEach(track => {
          console.log('🔇 Stopping track:', track.kind, track.readyState);
          track.stop();
        });
        console.log('🔄 Processing recording and setting showCompletionModal to true');
        setProcessingStatus('processing');
        processRecordingBasic();
        setShowCompletionModal(true);
      };

      mediaRecorder.onerror = (event) => {
        console.error('❌ MediaRecorder error:', event);
        toast({ 
          title: "Recording Error", 
          description: "An error occurred during recording", 
          variant: "destructive" 
        });
      };

      console.log('▶️ Starting MediaRecorder...');
      mediaRecorder.start(5000); // 5-second chunks
      setIsRecording(true);
      setRecordingState(true, meeting.id); // Notify global recording context
      setRecordingTime(0);

      console.log('🎬 Recording started successfully, state:', mediaRecorder.state);
      intervalRef.current = setInterval(() => setRecordingTime(prev => prev + 1), 1000);
      toast({ title: "Recording started", description: "Meeting is now visible in your history" });

    } catch (error) {
      console.error('❌ Error starting recording:', error);
      
      // More specific error messages
      let errorMessage = 'Unknown error';
      if (error instanceof Error) {
        if (error.name === 'NotAllowedError') {
          errorMessage = 'Microphone access denied. Please allow microphone access and try again.';
        } else if (error.name === 'NotFoundError') {
          errorMessage = 'No microphone found. Please connect a microphone and try again.';
        } else if (error.name === 'NotSupportedError') {
          errorMessage = 'Audio recording not supported in this browser.';
        } else {
          errorMessage = error.message;
        }
      }
      
      // Clean up if meeting was created but recording failed
      if (currentMeetingId) {
        console.log('🧹 Cleaning up failed meeting record...');
        try {
          await supabase.from('meetings').delete().eq('id', currentMeetingId);
          console.log('✅ Failed meeting record cleaned up');
        } catch (cleanupError) {
          console.error('❌ Failed to cleanup meeting record:', cleanupError);
        }
        setCurrentMeetingId(null);
      }
      
      toast({ 
        title: "Recording Failed", 
        description: errorMessage, 
        variant: "destructive" 
      });
    }
  };

  const storeAudioChunk = async (chunk: Blob, chunkNumber: number, meetingId: string) => {
    try {
      const fileName = `${user?.id}/${meetingId}/chunk-${chunkNumber}.webm`;
      
      const { error: uploadError } = await supabase.storage
        .from('meeting-audio-chunks')
        .upload(fileName, chunk);

      if (uploadError) throw uploadError;

      await supabase.from('audio_chunks').insert({
        meeting_id: meetingId,
        chunk_number: chunkNumber,
        start_time: new Date(Date.now() - 5000).toISOString(),
        end_time: new Date().toISOString(),
        audio_blob_path: fileName,
        file_size: chunk.size,
        chunk_duration_ms: 5000,
        processing_status: 'stored'
      });

    } catch (error) {
      console.error('Error storing audio chunk:', error);
    }
  };

  const stopRecording = () => {
    console.log('🛑 stopRecording called', { 
      recorderState: mediaRecorderRef.current?.state,
      currentMeetingId,
      isRecording
    });
    
    if (mediaRecorderRef.current?.state === 'recording') {
      console.log('⏹️ Stopping MediaRecorder...');
      mediaRecorderRef.current.stop();
      setIsRecording(false);
      setRecordingState(false); // Notify global recording context
      
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
        intervalRef.current = null;
      }

      console.log('🔄 MediaRecorder stop initiated, processing will happen in onstop event');
    } else {
      console.log('⚠️ MediaRecorder not in recording state:', mediaRecorderRef.current?.state);
    }
  };

  const processRecordingBasic = async () => {
    console.log('🔄 processRecordingBasic called', { currentMeetingId, recordingTime });
    
    if (!currentMeetingId) {
      console.error('❌ No currentMeetingId found, cannot process recording');
      return;
    }

    try {
      console.log('🔄 Starting recording processing for meeting:', currentMeetingId);
      
      // Generate basic transcript from stored chunks or use simple note
      const basicTranscript = `Meeting recorded from ${new Date(Date.now() - recordingTime * 1000).toLocaleTimeString()} to ${new Date().toLocaleTimeString()}. Duration: ${Math.floor(recordingTime / 60)} minutes ${recordingTime % 60} seconds.`;
      
      setTranscript(basicTranscript);
      
      // Update meeting status to completed
      const { error: updateError } = await supabase.from('meetings').update({
        end_time: new Date().toISOString(),
        status: 'completed',
        duration: `${Math.floor(recordingTime / 60)}:${(recordingTime % 60).toString().padStart(2, '0')}`,
        word_count: Math.floor(basicTranscript.split(' ').length)
      }).eq('id', currentMeetingId);

      if (updateError) {
        throw updateError;
      }
      
      console.log('✅ Meeting status updated successfully');
      
      // Trigger unified meeting processing
      console.log('🚀 Triggering unified meeting completion processing...');
      setProcessingStatus('processing');
      
      try {
        const { data, error } = await supabase.functions.invoke('meeting-completion-processor', {
          body: { meetingId: currentMeetingId }
        });

        if (error) {
          console.error('❌ Meeting processing failed:', error);
          toast({ 
            title: "Processing Error", 
            description: "Meeting saved but automatic processing failed. You can generate notes manually.",
            variant: "destructive" 
          });
        } else {
          console.log('✅ Meeting processing completed:', data);
          toast({ 
            title: "Meeting Completed!", 
            description: "Transcript cleaned and notes generated automatically." 
          });
        }
      } catch (processingError) {
        console.error('❌ Meeting processing error:', processingError);
        toast({ 
          title: "Processing Error", 
          description: "Meeting saved but processing failed. You can enhance it manually.",
          variant: "destructive" 
        });
      }

      setProcessingStatus('completed');

    } catch (error) {
      console.error('❌ Critical error processing recording:', error);
      
      toast({ 
        title: "Recording Error", 
        description: "Recording saved but status update failed. Meeting may need manual recovery.", 
        variant: "destructive" 
      });
      
      setProcessingStatus('completed'); // Allow user to continue despite error
    }
  };

  const handleSaveForLater = async (contextData: MeetingContextData) => {
    if (!currentMeetingId) return;

    try {
      await supabase.from('meetings').update({
        title: contextData.title,
        meeting_format: contextData.format,
        meeting_location: contextData.location,
        agenda: contextData.agenda,
        participants: contextData.participants,
        meeting_context: { ...contextData, enhancement_level: 'basic' }
      }).eq('id', currentMeetingId);

      toast({ title: "Meeting saved", description: "Basic notes generated, ready for enhancement anytime" });
      setShowCompletionModal(false);
      navigate(`/meeting-summary/${currentMeetingId}`);
    } catch (error) {
      console.error('Error saving meeting context:', error);
      toast({ title: "Error", description: "Failed to save meeting details", variant: "destructive" });
    }
  };

  const handleGenerateNow = async (contextData: MeetingContextData) => {
    if (!currentMeetingId) return;

    try {
      setProcessingStatus('processing');
      
      const { data, error } = await supabase.functions.invoke('generate-meeting-notes-claude', {
        body: {
          transcript,
          meetingTitle: contextData.title,
          meetingDate: new Date().toISOString().split('T')[0],
          meetingTime: new Date().toLocaleTimeString(),
          detailLevel: 'detailed',
          meetingContext: contextData
        }
      });

      if (error) throw error;

      await supabase.from('meetings').update({
        title: contextData.title,
        meeting_format: contextData.format,
        meeting_location: contextData.location,
        agenda: contextData.agenda,
        participants: contextData.participants,
        generated_notes: data?.generatedNotes,
        meeting_context: { ...contextData, enhancement_level: 'enhanced', ai_generated: true }
      }).eq('id', currentMeetingId);

      toast({ title: "Success", description: "Enhanced meeting notes generated!" });
      setShowCompletionModal(false);
      navigate(`/meeting-summary/${currentMeetingId}`);

    } catch (error) {
      console.error('Error generating enhanced notes:', error);
      toast({ title: "Error", description: "Failed to generate enhanced notes", variant: "destructive" });
    }
  };

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  return (
    <>
      <Card className="w-full max-w-2xl mx-auto">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Mic className="h-5 w-5" />
            Enhanced Meeting Recorder
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {!currentMeetingId ? (
            <div className="text-center space-y-4">
              <p className="text-muted-foreground">Ready to start recording your meeting</p>
              <Button onClick={startRecording} size="lg" className="w-full">
                <Mic className="h-4 w-4 mr-2" />
                Start Recording
              </Button>
              <p className="text-xs text-muted-foreground">
                Meeting will be auto-named and immediately visible in your history
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              <div className="text-center">
                <h3 className="font-semibold text-lg">{autoGeneratedTitle}</h3>
                <div className="flex items-center justify-center gap-4 mt-2">
                  {isRecording && (
                    <Badge variant="destructive" className="animate-pulse">
                      Recording Live
                    </Badge>
                  )}
                  <div className="flex items-center gap-1 text-muted-foreground">
                    <Clock className="h-4 w-4" />
                    {formatTime(recordingTime)}
                  </div>
                </div>
              </div>

              <div className="flex justify-center">
                {isRecording ? (
                  <Button onClick={stopRecording} variant="destructive" size="lg">
                    <Square className="h-4 w-4 mr-2" />
                    Stop Recording
                  </Button>
                ) : processingStatus === 'processing' ? (
                  <div className="text-center">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-2"></div>
                    <p className="text-sm text-muted-foreground">Processing...</p>
                  </div>
                ) : (
                  <div className="text-center space-y-2">
                    <p className="text-sm text-muted-foreground">Recording completed and saved</p>
                    <Button onClick={() => navigate(`/meeting-summary/${currentMeetingId}`)}>
                      <FileText className="h-4 w-4 mr-2" />
                      View Meeting
                    </Button>
                  </div>
                )}
              </div>
            </div>
          )}

          <div className="flex justify-between pt-4 border-t">
            <Button variant="outline" onClick={() => navigate('/meeting-history')}>
              View All Meetings
            </Button>
            <Button variant="outline" onClick={onClose}>
              Close
            </Button>
          </div>
        </CardContent>
      </Card>

      <MeetingCompletionModal
        isOpen={showCompletionModal}
        onClose={() => setShowCompletionModal(false)}
        meetingId={currentMeetingId || ''}
        initialTitle={autoGeneratedTitle}
        onSaveForLater={handleSaveForLater}
        onGenerateNow={handleGenerateNow}
      />
    </>
  );
};