import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, BorderStyle, AlignmentType, convertInchesToTwip } from 'docx';
import { saveAs } from 'file-saver';

interface PolicyMetadata {
  title: string;
  version: string;
  effective_date: string;
  review_date: string;
  references: string[];
}

// Professional colour scheme matching NHS/Notewell branding
const COLORS = {
  nhsBlue: "005EB8",
  headingBlue: "1E3A8A",
  subHeadingBlue: "2563EB",
  textGrey: "374151",
  lightGrey: "6B7280",
  tableBorder: "D1D5DB",
  tableHeaderBg: "EFF6FF",
  white: "FFFFFF",
};

export const generatePolicyDocx = async (
  content: string,
  metadata: PolicyMetadata,
  policyName: string
): Promise<void> => {
  const today = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  // Parse markdown content into sections
  const sections = parseMarkdownToSections(content);

  const doc = new Document({
    styles: {
      paragraphStyles: [
        {
          id: "Normal",
          name: "Normal",
          basedOn: "Normal",
          next: "Normal",
          run: {
            font: "Calibri",
            size: 22, // 11pt
            color: COLORS.textGrey,
          },
          paragraph: {
            spacing: {
              after: 120, // 6pt
              line: 276, // 1.15 line spacing
            },
          },
        },
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          run: {
            font: "Calibri",
            size: 28, // 14pt
            bold: true,
            color: COLORS.headingBlue,
          },
          paragraph: {
            spacing: {
              before: 280,
              after: 120,
            },
          },
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          run: {
            font: "Calibri",
            size: 24, // 12pt
            bold: true,
            color: COLORS.subHeadingBlue,
          },
          paragraph: {
            spacing: {
              before: 200,
              after: 100,
            },
          },
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1),
              right: convertInchesToTwip(1),
            },
          },
        },
        children: [
          // Title
          new Paragraph({
            children: [
              new TextRun({
                text: metadata.title,
                bold: true,
                size: 48, // 24pt
                color: COLORS.nhsBlue,
                font: "Calibri",
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),

          // Document Control Table
          createDocumentControlTable(metadata, today),

          // Spacing after table
          new Paragraph({ text: "", spacing: { after: 300 } }),

          // Content sections
          ...sections,

          // References section
          new Paragraph({
            children: [
              new TextRun({
                text: "References & Legislation",
                bold: true,
                size: 28,
                color: COLORS.headingBlue,
                font: "Calibri",
              }),
            ],
            spacing: { before: 280, after: 120 },
          }),
          ...metadata.references.map(ref =>
            new Paragraph({
              children: [
                new TextRun({ text: "• ", bold: true, font: "Calibri", size: 22 }),
                new TextRun({ text: ref, font: "Calibri", size: 22, color: COLORS.textGrey }),
              ],
              spacing: { after: 60 },
              indent: { left: convertInchesToTwip(0.25) },
            })
          ),

          // Footer info
          new Paragraph({ text: "", spacing: { before: 600 } }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated by Notewell Policy Service on ${today}`,
                italics: true,
                size: 18,
                color: COLORS.lightGrey,
                font: "Calibri",
              }),
            ],
            alignment: AlignmentType.CENTER,
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const filename = `${policyName.replace(/[^a-zA-Z0-9]/g, '_')}_v${metadata.version}.docx`;
  saveAs(blob, filename);
};

function createDocumentControlTable(metadata: PolicyMetadata, generatedDate: string): Table {
  const cellBorder = {
    top: { style: BorderStyle.SINGLE, size: 1, color: COLORS.tableBorder },
    bottom: { style: BorderStyle.SINGLE, size: 1, color: COLORS.tableBorder },
    left: { style: BorderStyle.SINGLE, size: 1, color: COLORS.tableBorder },
    right: { style: BorderStyle.SINGLE, size: 1, color: COLORS.tableBorder },
  };

  const headerCellStyle = {
    borders: cellBorder,
    shading: { fill: COLORS.tableHeaderBg },
    margins: {
      top: convertInchesToTwip(0.05),
      bottom: convertInchesToTwip(0.05),
      left: convertInchesToTwip(0.1),
      right: convertInchesToTwip(0.1),
    },
  };

  const valueCellStyle = {
    borders: cellBorder,
    margins: {
      top: convertInchesToTwip(0.05),
      bottom: convertInchesToTwip(0.05),
      left: convertInchesToTwip(0.1),
      right: convertInchesToTwip(0.1),
    },
  };

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ 
              children: [new TextRun({ text: "Version", bold: true, font: "Calibri", size: 22 })] 
            })],
            width: { size: 20, type: WidthType.PERCENTAGE },
            ...headerCellStyle,
          }),
          new TableCell({
            children: [new Paragraph({ 
              children: [new TextRun({ text: metadata.version, font: "Calibri", size: 22 })] 
            })],
            width: { size: 30, type: WidthType.PERCENTAGE },
            ...valueCellStyle,
          }),
          new TableCell({
            children: [new Paragraph({ 
              children: [new TextRun({ text: "Effective Date", bold: true, font: "Calibri", size: 22 })] 
            })],
            width: { size: 20, type: WidthType.PERCENTAGE },
            ...headerCellStyle,
          }),
          new TableCell({
            children: [new Paragraph({ 
              children: [new TextRun({ text: metadata.effective_date, font: "Calibri", size: 22 })] 
            })],
            width: { size: 30, type: WidthType.PERCENTAGE },
            ...valueCellStyle,
          }),
        ],
      }),
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ 
              children: [new TextRun({ text: "Review Date", bold: true, font: "Calibri", size: 22 })] 
            })],
            ...headerCellStyle,
          }),
          new TableCell({
            children: [new Paragraph({ 
              children: [new TextRun({ text: metadata.review_date, font: "Calibri", size: 22 })] 
            })],
            ...valueCellStyle,
          }),
          new TableCell({
            children: [new Paragraph({ 
              children: [new TextRun({ text: "Generated", bold: true, font: "Calibri", size: 22 })] 
            })],
            ...headerCellStyle,
          }),
          new TableCell({
            children: [new Paragraph({ 
              children: [new TextRun({ text: generatedDate, font: "Calibri", size: 22 })] 
            })],
            ...valueCellStyle,
          }),
        ],
      }),
    ],
  });
}

/**
 * Create a proper table from markdown pipe table syntax
 */
function createMarkdownTable(lines: string[]): Table {
  const cellBorder = {
    top: { style: BorderStyle.SINGLE, size: 1, color: COLORS.tableBorder },
    bottom: { style: BorderStyle.SINGLE, size: 1, color: COLORS.tableBorder },
    left: { style: BorderStyle.SINGLE, size: 1, color: COLORS.tableBorder },
    right: { style: BorderStyle.SINGLE, size: 1, color: COLORS.tableBorder },
  };

  const rows: TableRow[] = [];
  let isHeader = true;

  for (const line of lines) {
    // Skip separator lines (---|---|---)
    if (/^[\s|:-]+$/.test(line.replace(/\|/g, '').trim()) && line.includes('-')) {
      isHeader = false;
      continue;
    }

    const cells = line.split('|')
      .map(cell => cell.trim())
      .filter(cell => cell.length > 0);

    if (cells.length === 0) continue;

    const tableCells = cells.map(cellText => 
      new TableCell({
        children: [
          new Paragraph({
            children: parseInlineFormatting(cellText),
          }),
        ],
        borders: cellBorder,
        shading: isHeader ? { fill: COLORS.tableHeaderBg } : undefined,
        margins: {
          top: convertInchesToTwip(0.05),
          bottom: convertInchesToTwip(0.05),
          left: convertInchesToTwip(0.1),
          right: convertInchesToTwip(0.1),
        },
      })
    );

    rows.push(new TableRow({ children: tableCells }));
  }

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows,
  });
}

function parseMarkdownToSections(markdown: string): (Paragraph | Table)[] {
  const elements: (Paragraph | Table)[] = [];
  const lines = markdown.split('\n');
  
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();
    
    // Skip empty lines
    if (!trimmed) {
      elements.push(new Paragraph({ text: "", spacing: { after: 60 } }));
      i++;
      continue;
    }

    // Clean up malformed HTML tags that might appear
    const cleanedLine = trimmed
      .replace(/<\/h\d+>/gi, '')
      .replace(/<h\d+>/gi, '')
      .replace(/&amp;/g, '&')
      .replace(/&#x26;/g, '&');

    // Check for markdown table (starts with |)
    if (cleanedLine.startsWith('|') || (cleanedLine.includes('|') && i + 1 < lines.length && lines[i + 1].includes('---'))) {
      const tableLines: string[] = [];
      while (i < lines.length && (lines[i].includes('|') || lines[i].trim().includes('---'))) {
        tableLines.push(lines[i]);
        i++;
      }
      if (tableLines.length >= 2) {
        elements.push(createMarkdownTable(tableLines));
        elements.push(new Paragraph({ text: "", spacing: { after: 120 } }));
      }
      continue;
    }

    // Heading 1: # Title
    if (cleanedLine.startsWith('# ') && !cleanedLine.startsWith('## ')) {
      elements.push(new Paragraph({
        children: [
          new TextRun({
            text: cleanedLine.substring(2),
            bold: true,
            size: 28,
            color: COLORS.headingBlue,
            font: "Calibri",
          }),
        ],
        spacing: { before: 280, after: 120 },
      }));
      i++;
      continue;
    }

    // Heading 2: ## Subtitle
    if (cleanedLine.startsWith('## ')) {
      elements.push(new Paragraph({
        children: [
          new TextRun({
            text: cleanedLine.substring(3),
            bold: true,
            size: 24,
            color: COLORS.subHeadingBlue,
            font: "Calibri",
          }),
        ],
        spacing: { before: 200, after: 100 },
      }));
      i++;
      continue;
    }

    // Heading 3: ### Subheading
    if (cleanedLine.startsWith('### ')) {
      elements.push(new Paragraph({
        children: [
          new TextRun({
            text: cleanedLine.substring(4),
            bold: true,
            size: 22,
            color: COLORS.textGrey,
            font: "Calibri",
          }),
        ],
        spacing: { before: 160, after: 80 },
      }));
      i++;
      continue;
    }

    // Bullet point: - item or * item
    if (cleanedLine.startsWith('- ') || cleanedLine.startsWith('* ')) {
      const bulletText = cleanedLine.substring(2);
      elements.push(new Paragraph({
        children: [
          new TextRun({ text: "• ", font: "Calibri", size: 22 }),
          ...parseInlineFormatting(bulletText),
        ],
        indent: { left: convertInchesToTwip(0.25) },
        spacing: { after: 60 },
      }));
      i++;
      continue;
    }

    // Numbered list: 1. item
    const numberedMatch = cleanedLine.match(/^(\d+)\.\s+(.+)$/);
    if (numberedMatch) {
      elements.push(new Paragraph({
        children: [
          new TextRun({ text: `${numberedMatch[1]}. `, font: "Calibri", size: 22, bold: true }),
          ...parseInlineFormatting(numberedMatch[2]),
        ],
        indent: { left: convertInchesToTwip(0.25) },
        spacing: { after: 60 },
      }));
      i++;
      continue;
    }

    // Regular paragraph
    const runs = parseInlineFormatting(cleanedLine);
    elements.push(new Paragraph({
      children: runs,
      spacing: { after: 120 },
    }));
    i++;
  }

  return elements;
}

function parseInlineFormatting(text: string): TextRun[] {
  const runs: TextRun[] = [];
  
  // Clean up any stray markdown/HTML artifacts
  let cleanText = text
    .replace(/<\/h\d+>/gi, '')
    .replace(/<h\d+>/gi, '')
    .replace(/&amp;/g, '&')
    .replace(/&#x26;/g, '&');

  // Process bold (**text**) and regular text
  const boldPattern = /\*\*([^*]+)\*\*/g;
  let lastIndex = 0;
  let match;

  while ((match = boldPattern.exec(cleanText)) !== null) {
    // Add text before the bold match
    if (match.index > lastIndex) {
      const beforeText = cleanText.substring(lastIndex, match.index);
      if (beforeText) {
        runs.push(new TextRun({ 
          text: beforeText, 
          font: "Calibri", 
          size: 22, 
          color: COLORS.textGrey 
        }));
      }
    }
    
    // Add the bold text
    runs.push(new TextRun({ 
      text: match[1], 
      bold: true, 
      font: "Calibri", 
      size: 22, 
      color: COLORS.textGrey 
    }));
    
    lastIndex = match.index + match[0].length;
  }

  // Add remaining text after last bold match
  if (lastIndex < cleanText.length) {
    const remainingText = cleanText.substring(lastIndex);
    if (remainingText) {
      runs.push(new TextRun({ 
        text: remainingText, 
        font: "Calibri", 
        size: 22, 
        color: COLORS.textGrey 
      }));
    }
  }

  // If no runs were created, return the full text
  if (runs.length === 0) {
    runs.push(new TextRun({ 
      text: cleanText || ' ', 
      font: "Calibri", 
      size: 22, 
      color: COLORS.textGrey 
    }));
  }

  return runs;
}
