import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, BorderStyle, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';

interface PolicyMetadata {
  title: string;
  version: string;
  effective_date: string;
  review_date: string;
  references: string[];
}

export const generatePolicyDocx = async (
  content: string,
  metadata: PolicyMetadata,
  policyName: string
): Promise<void> => {
  const today = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  // Parse markdown content into sections
  const sections = parseMarkdownToSections(content);

  const doc = new Document({
    styles: {
      paragraphStyles: [
        {
          id: "Normal",
          name: "Normal",
          basedOn: "Normal",
          next: "Normal",
          run: {
            font: "Calibri",
            size: 22, // 11pt
          },
          paragraph: {
            spacing: {
              after: 120, // 6pt
              line: 276, // 1.15 line spacing
            },
          },
        },
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          run: {
            font: "Calibri",
            size: 32, // 16pt
            bold: true,
            color: "2563EB", // Professional blue
          },
          paragraph: {
            spacing: {
              before: 240,
              after: 120,
            },
          },
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          run: {
            font: "Calibri",
            size: 26, // 13pt
            bold: true,
            color: "2563EB",
          },
          paragraph: {
            spacing: {
              before: 200,
              after: 100,
            },
          },
        },
      ],
    },
    sections: [
      {
        properties: {},
        children: [
          // Title
          new Paragraph({
            children: [
              new TextRun({
                text: metadata.title,
                bold: true,
                size: 48, // 24pt
                color: "1E3A8A", // Dark blue
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),

          // Document Control Table
          createDocumentControlTable(metadata, today),

          // Spacing
          new Paragraph({ text: "", spacing: { after: 400 } }),

          // Content sections
          ...sections,

          // References section
          new Paragraph({
            text: "References & Legislation",
            heading: HeadingLevel.HEADING_1,
          }),
          ...metadata.references.map(ref =>
            new Paragraph({
              children: [
                new TextRun({ text: "• ", bold: true }),
                new TextRun({ text: ref }),
              ],
              spacing: { after: 60 },
            })
          ),

          // Footer info
          new Paragraph({ text: "", spacing: { before: 600 } }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated by Notewell Policy Service on ${today}`,
                italics: true,
                size: 18,
                color: "666666",
              }),
            ],
            alignment: AlignmentType.CENTER,
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const filename = `${policyName.replace(/[^a-zA-Z0-9]/g, '_')}_v${metadata.version}.docx`;
  saveAs(blob, filename);
};

function createDocumentControlTable(metadata: PolicyMetadata, generatedDate: string): Table {
  const cellBorder = {
    top: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
    bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
    left: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
    right: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
  };

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: "Version", bold: true })] })],
            width: { size: 25, type: WidthType.PERCENTAGE },
            borders: cellBorder,
            shading: { fill: "F3F4F6" },
          }),
          new TableCell({
            children: [new Paragraph({ text: metadata.version })],
            width: { size: 25, type: WidthType.PERCENTAGE },
            borders: cellBorder,
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: "Effective Date", bold: true })] })],
            width: { size: 25, type: WidthType.PERCENTAGE },
            borders: cellBorder,
            shading: { fill: "F3F4F6" },
          }),
          new TableCell({
            children: [new Paragraph({ text: metadata.effective_date })],
            width: { size: 25, type: WidthType.PERCENTAGE },
            borders: cellBorder,
          }),
        ],
      }),
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: "Review Date", bold: true })] })],
            borders: cellBorder,
            shading: { fill: "F3F4F6" },
          }),
          new TableCell({
            children: [new Paragraph({ text: metadata.review_date })],
            borders: cellBorder,
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: "Generated", bold: true })] })],
            borders: cellBorder,
            shading: { fill: "F3F4F6" },
          }),
          new TableCell({
            children: [new Paragraph({ text: generatedDate })],
            borders: cellBorder,
          }),
        ],
      }),
    ],
  });
}

function parseMarkdownToSections(markdown: string): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  const lines = markdown.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();
    
    if (!trimmed) {
      paragraphs.push(new Paragraph({ text: "" }));
      continue;
    }

    // Heading 1: # Title
    if (trimmed.startsWith('# ') && !trimmed.startsWith('## ')) {
      paragraphs.push(new Paragraph({
        text: trimmed.substring(2),
        heading: HeadingLevel.HEADING_1,
      }));
      continue;
    }

    // Heading 2: ## Subtitle
    if (trimmed.startsWith('## ')) {
      paragraphs.push(new Paragraph({
        text: trimmed.substring(3),
        heading: HeadingLevel.HEADING_2,
      }));
      continue;
    }

    // Heading 3: ### Subheading
    if (trimmed.startsWith('### ')) {
      paragraphs.push(new Paragraph({
        children: [
          new TextRun({
            text: trimmed.substring(4),
            bold: true,
            size: 24, // 12pt
          }),
        ],
        spacing: { before: 160, after: 80 },
      }));
      continue;
    }

    // Bullet point: - item or * item
    if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      paragraphs.push(new Paragraph({
        children: [
          new TextRun({ text: "• " }),
          new TextRun({ text: trimmed.substring(2) }),
        ],
        indent: { left: 360 },
        spacing: { after: 60 },
      }));
      continue;
    }

    // Numbered list: 1. item
    const numberedMatch = trimmed.match(/^(\d+)\.\s+(.+)$/);
    if (numberedMatch) {
      paragraphs.push(new Paragraph({
        children: [
          new TextRun({ text: `${numberedMatch[1]}. ` }),
          new TextRun({ text: numberedMatch[2] }),
        ],
        indent: { left: 360 },
        spacing: { after: 60 },
      }));
      continue;
    }

    // Regular paragraph - handle bold (**text**) and italic (*text*)
    const runs = parseInlineFormatting(trimmed);
    paragraphs.push(new Paragraph({
      children: runs,
      spacing: { after: 120 },
    }));
  }

  return paragraphs;
}

function parseInlineFormatting(text: string): TextRun[] {
  const runs: TextRun[] = [];
  let remaining = text;

  while (remaining.length > 0) {
    // Bold: **text**
    const boldMatch = remaining.match(/^(.*?)\*\*(.+?)\*\*(.*)$/);
    if (boldMatch) {
      if (boldMatch[1]) {
        runs.push(new TextRun({ text: boldMatch[1] }));
      }
      runs.push(new TextRun({ text: boldMatch[2], bold: true }));
      remaining = boldMatch[3];
      continue;
    }

    // Italic: *text* (but not **)
    const italicMatch = remaining.match(/^(.*?)(?<!\*)\*([^*]+)\*(?!\*)(.*)$/);
    if (italicMatch) {
      if (italicMatch[1]) {
        runs.push(new TextRun({ text: italicMatch[1] }));
      }
      runs.push(new TextRun({ text: italicMatch[2], italics: true }));
      remaining = italicMatch[3];
      continue;
    }

    // No more formatting found
    runs.push(new TextRun({ text: remaining }));
    break;
  }

  return runs.length > 0 ? runs : [new TextRun({ text })];
}
