import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getPracticeName, getOdsCode } from '@/data/nresPractices';
import type { BuyBackClaim } from '@/hooks/useNRESBuyBackClaims';

interface InvoiceData {
  claim: BuyBackClaim;
  invoiceNumber: string;
  neighbourhoodName: string;
}

const fmt = (n: number) =>
  `£${n.toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export function generateInvoicePdf(data: InvoiceData): jsPDF {
  const { claim, invoiceNumber, neighbourhoodName } = data;
  const doc = new jsPDF();
  const practiceName = getPracticeName(claim.practice_key);
  const odsCode = getOdsCode(claim.practice_key);
  const staffDetails = (claim.staff_details as any[]) || [];
  const claimDate = new Date(claim.claim_month);
  const claimMonthLabel = claimDate.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' });

  // --- Header ---
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('INVOICE', 14, 20);

  doc.setFontSize(16);
  doc.setTextColor(0, 48, 135); // NHS dark blue
  doc.text(practiceName, 14, 30);

  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(`ODS Code: ${odsCode}`, 14, 36);
  doc.text(`${neighbourhoodName} Neighbourhood Access Service`, 14, 41);

  // --- Invoice Details (right side) ---
  doc.setFontSize(9);
  doc.setTextColor(60);
  const rightX = 130;
  doc.text('Invoice To:', rightX, 20);
  doc.setFontSize(10);
  doc.setTextColor(0);
  doc.text('PML (Practice Makes Perfect Ltd)', rightX, 26);
  doc.setFontSize(9);
  doc.setTextColor(60);
  doc.text(`Invoice No: ${invoiceNumber}`, rightX, 36);
  doc.text(`Invoice Date: ${new Date().toLocaleDateString('en-GB')}`, rightX, 41);
  doc.text(`Claim Period: ${claimMonthLabel}`, rightX, 46);
  doc.text('Payment Terms: 14 days', rightX, 51);

  // --- Separator ---
  doc.setDrawColor(0, 94, 184); // NHS blue
  doc.setLineWidth(0.5);
  doc.line(14, 56, 196, 56);

  // --- Staff Lines Table ---
  const tableData = staffDetails.map((s: any, i: number) => [
    i + 1,
    s.staff_name || '—',
    s.staff_role || '—',
    s.gl_category || (s.staff_role === 'GP' ? 'GP' : 'Other Clinical'),
    s.allocation_type === 'sessions'
      ? `${s.allocation_value} session${s.allocation_value !== 1 ? 's' : ''}`
      : s.allocation_type === 'hours'
        ? `${s.allocation_value} hrs/wk`
        : `${s.allocation_value} WTE`,
    fmt(s.claimed_amount || 0),
  ]);

  autoTable(doc, {
    startY: 62,
    head: [['#', 'Staff Member', 'Role', 'GL Category', 'Allocation', 'Amount']],
    body: tableData,
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [0, 94, 184], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 10 },
      5: { halign: 'right' },
    },
    alternateRowStyles: { fillColor: [240, 244, 245] },
  });

  // --- GL Subtotals ---
  const gpTotal = staffDetails
    .filter((s: any) => (s.gl_category || (s.staff_role === 'GP' ? 'GP' : 'Other Clinical')) === 'GP')
    .reduce((sum: number, s: any) => sum + (s.claimed_amount || 0), 0);
  const otherTotal = staffDetails
    .filter((s: any) => (s.gl_category || (s.staff_role === 'GP' ? 'GP' : 'Other Clinical')) !== 'GP')
    .reduce((sum: number, s: any) => sum + (s.claimed_amount || 0), 0);
  const grandTotal = gpTotal + otherTotal;

  const finalY = (doc as any).lastAutoTable.finalY + 8;

  doc.setFontSize(9);
  doc.setTextColor(60);
  doc.text('GP Subtotal:', 140, finalY);
  doc.text(fmt(gpTotal), 196, finalY, { align: 'right' });
  doc.text('Other Clinical Subtotal:', 140, finalY + 5);
  doc.text(fmt(otherTotal), 196, finalY + 5, { align: 'right' });

  doc.setDrawColor(0, 94, 184);
  doc.line(140, finalY + 8, 196, finalY + 8);

  doc.setFontSize(12);
  doc.setTextColor(0, 48, 135);
  doc.text('TOTAL:', 140, finalY + 14);
  doc.text(fmt(grandTotal), 196, finalY + 14, { align: 'right' });

  // --- Footer ---
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Claim ID: ${claim.id}`, 14, 280);
  doc.text(`Generated by Notewell AI — ${neighbourhoodName} SDA Programme`, 14, 284);

  return doc;
}
