import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface EmailRequest {
  userEmail: string;
  attendeeEmails?: string[];
  meetingTitle: string;
  meetingDate: string;
  duration: string;
  summary: string;
  includeTranscript: boolean;
  transcript?: string;
  practiceName?: string;
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { 
      userEmail, 
      attendeeEmails = [], 
      meetingTitle, 
      meetingDate, 
      duration, 
      summary, 
      includeTranscript, 
      transcript, 
      practiceName 
    }: EmailRequest = await req.json();

    const emailContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #0066cc; border-bottom: 2px solid #0066cc; padding-bottom: 10px;">
          NHS Meeting Summary - ${meetingTitle}
        </h2>
        
        <div style="background-color: #f5f5f5; padding: 15px; margin: 20px 0; border-left: 4px solid #0066cc;">
          <p><strong>Meeting Date:</strong> ${meetingDate}</p>
          <p><strong>Duration:</strong> ${duration}</p>
          ${practiceName ? `<p><strong>Practice:</strong> ${practiceName}</p>` : ''}
        </div>
        
        <div style="margin: 20px 0;">
          <h3 style="color: #0066cc;">Meeting Summary</h3>
          <div style="white-space: pre-wrap; line-height: 1.6;">${summary}</div>
        </div>
        
        ${includeTranscript && transcript ? `
          <div style="margin: 20px 0;">
            <h3 style="color: #0066cc;">Meeting Transcript</h3>
            <div style="background-color: #f9f9f9; padding: 15px; border: 1px solid #ddd; white-space: pre-wrap; font-family: monospace; font-size: 12px; max-height: 300px; overflow-y: auto;">
              ${transcript}
            </div>
          </div>
        ` : ''}
        
        <footer style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666;">
          <p>This summary was generated by Notewell AI Meeting Notes Service</p>
        </footer>
      </div>
    `;

    // Send to user
    const userEmailResponse = await resend.emails.send({
      from: "Notewell AI <onboarding@resend.dev>",
      to: [userEmail],
      subject: `Meeting Summary: ${meetingTitle}`,
      html: emailContent,
    });

    // Send to attendees if provided
    const attendeeResponses = [];
    if (attendeeEmails.length > 0) {
      for (const email of attendeeEmails) {
        const response = await resend.emails.send({
          from: "Notewell AI <onboarding@resend.dev>",
          to: [email],
          subject: `Meeting Summary: ${meetingTitle}`,
          html: emailContent,
        });
        attendeeResponses.push(response);
      }
    }

    return new Response(JSON.stringify({ 
      success: true, 
      userEmailResponse, 
      attendeeResponses 
    }), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders,
      },
    });
  } catch (error: any) {
    console.error("Error in send-meeting-summary function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);