import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface EmailRequest {
  userEmail: string;
  attendeeEmails?: string[];
  meetingTitle: string;
  meetingDate: string;
  duration: string;
  summary: string;
  includeTranscript: boolean;
  transcript?: string;
  practiceName?: string;
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { 
      userEmail, 
      attendeeEmails = [], 
      meetingTitle, 
      meetingDate, 
      duration, 
      summary, 
      includeTranscript, 
      transcript, 
      practiceName 
    }: EmailRequest = await req.json();

    // Get EmailJS configuration
    const serviceId = Deno.env.get("EMAILJS_SERVICE_ID");
    const templateId = Deno.env.get("EMAILJS_TEMPLATE_ID");
    const publicKey = Deno.env.get("EMAILJS_PUBLIC_KEY");
    const privateKey = Deno.env.get("EMAILJS_PRIVATE_KEY");

    if (!serviceId || !templateId || !publicKey || !privateKey) {
      throw new Error("EmailJS configuration is incomplete");
    }

    // Prepare email content
    const emailContent = `NHS Meeting Summary - ${meetingTitle}

Meeting Date: ${meetingDate}
Duration: ${duration}
${practiceName ? `Practice: ${practiceName}` : ''}

MEETING SUMMARY
===============
${summary}

${includeTranscript && transcript ? `
MEETING TRANSCRIPT
==================
${transcript}
` : ''}

---
This summary was generated by Notewell AI Meeting Notes Service`;

    // Send to user first
    const userEmailData = {
      service_id: serviceId,
      template_id: templateId,
      user_id: publicKey,
      template_params: {
        to_email: userEmail,
        to_name: userEmail.split('@')[0],
        subject: `${meetingTitle}, ${meetingDate} - Minutes`,
        message: emailContent,
        from_name: "Notewell AI",
        reply_to: "noreply@notewell.ai"
      },
      accessToken: privateKey
    };

    console.log("Sending email to user:", userEmail);
    
    const userResponse = await fetch("https://api.emailjs.com/api/v1.0/email/send", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(userEmailData),
    });

    if (!userResponse.ok) {
      const errorText = await userResponse.text();
      throw new Error(`Failed to send email to user: ${errorText}`);
    }

    // Send to attendees if provided
    const attendeeResponses = [];
    for (const attendeeEmail of attendeeEmails) {
      if (attendeeEmail && attendeeEmail.trim()) {
        console.log("Sending email to attendee:", attendeeEmail);
        
        const attendeeEmailData = {
          service_id: serviceId,
          template_id: templateId,
          user_id: publicKey,
          template_params: {
            to_email: attendeeEmail,
            to_name: attendeeEmail.split('@')[0],
            subject: `${meetingTitle}, ${meetingDate} - Minutes`,
            message: emailContent,
            from_name: "Notewell AI",
            reply_to: "noreply@notewell.ai"
          },
          accessToken: privateKey
        };

        const attendeeResponse = await fetch("https://api.emailjs.com/api/v1.0/email/send", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(attendeeEmailData),
        });

        if (attendeeResponse.ok) {
          attendeeResponses.push({ email: attendeeEmail, status: "sent" });
        } else {
          const errorText = await attendeeResponse.text();
          console.error(`Failed to send to ${attendeeEmail}:`, errorText);
          attendeeResponses.push({ email: attendeeEmail, status: "failed", error: errorText });
        }
      }
    }

    console.log("Email sending completed successfully");

    return new Response(JSON.stringify({ 
      success: true,
      message: "Meeting summary sent successfully",
      attendee_results: attendeeResponses
    }), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders,
      },
    });
  } catch (error: any) {
    console.error("Error in send-meeting-summary function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);