-- Comprehensive demo responses for all 20 complaint examples
-- Ensures idempotent upsert so this migration can be run safely multiple times

INSERT INTO complaint_demo_responses (complaint_reference, key_findings, actions_taken, improvements_made, additional_context) VALUES
('COMP250001', 'Delayed referral identified due to administrative backlog. Referral was placed in incorrect tray and not actioned for 12 days.', 'Immediate referral processed. Patient contacted and apologised to. Administrative workflows reviewed.', 'Implemented new tray labelling system and daily audit of pending referrals to prevent future delays.', 'Practice manager now conducts weekly spot-checks on referral processing times.'),
('COMP250002', 'GP conduct during consultation did not meet expected standards. Patient felt rushed and concerns were not adequately addressed.', 'GP has completed reflective practice session. Appointment times reviewed to allow adequate consultation time.', 'Enhanced communication training arranged for all GPs. Consultation feedback system implemented.', 'Practice now monitors consultation times and patient satisfaction scores quarterly.'),
('COMP250003', 'Medical records accessed inappropriately by staff member without clinical need. Breach of data protection identified.', 'Staff member disciplined according to HR policy. Patient informed and apology issued. ICO notified as required.', 'Mandatory data protection refresher training for all staff. Access logging system enhanced.', 'New audit trail system implemented to monitor record access patterns.'),
('COMP250004', 'Test results not communicated to patient within acceptable timeframe. Results were filed but patient not contacted.', 'Patient contacted immediately with results. Apology issued. Failsafe system reviewed.', 'New protocol requiring double-check on all abnormal results. Results tracking system upgraded.', 'Weekly review meetings now include results communication checks.'),
('COMP250005', 'Appointment system failure led to double-booking and extended wait time of 90 minutes.', 'Patients contacted and offered alternative slots. System bug identified and fixed by IT provider.', 'Upgraded appointment management system. Buffer slots added to prevent overbooking.', 'Real-time monitoring dashboard now alerts reception team to booking conflicts.'),
('COMP250006', 'Prescription error: incorrect medication issued due to similar drug names (confusion between medications).', 'Correct prescription issued immediately. Patient safety incident reported. Pharmacist counselling provided.', 'Computerised alerts added for sound-alike medications. Prescription verification process strengthened.', 'Monthly medication safety audits now conducted by lead pharmacist.'),
('COMP250007', 'Diagnosis delay occurred due to symptoms not being escalated appropriately during triage.', 'Patient referred urgently to specialist. Triage protocols reviewed with clinical team.', 'Enhanced triage training provided. Red flag symptom checklist updated and distributed.', 'Clinical governance team now reviews all delayed diagnosis cases monthly.'),
('COMP250008', 'Confidential information discussed in reception area within earshot of other patients.', 'Staff member counselled on confidentiality. Patient apologised to. Reception area acoustics assessed.', 'Soundproofing installed at reception desk. Privacy screens added. Staff retrained on confidentiality.', 'Mystery shopper assessments now include confidentiality checks.'),
('COMP250009', 'Home visit not conducted as arranged. Patient left waiting without notification of cancellation.', 'Emergency home visit arranged same day. Apology issued. Scheduling system reviewed.', 'New home visit confirmation protocol implemented. Backup GP assigned for visit coverage.', 'Real-time visit tracking system now in place with patient SMS notifications.'),
('COMP250010', 'Rude and dismissive behaviour by receptionist when patient called about urgent medical concern.', 'Receptionist disciplined. Customer service retraining completed. Patient contacted with apology.', 'Customer service standards refreshed for all reception staff. Complaint feedback integrated into training.', 'Reception team now has monthly customer service reviews with practice manager.'),
('COMP250011', 'Incorrect treatment plan provided. Clinical review revealed alternative treatment was more appropriate.', 'Treatment plan revised immediately. Second opinion arranged. Clinical case review conducted.', 'Enhanced peer review process for complex cases. Clinical decision support tools updated.', 'Monthly clinical audit meetings now review treatment pathways.'),
('COMP250012', 'Patient charged incorrectly for NHS service that should have been provided free of charge.', 'Refund processed immediately. Apology issued. Charging policy reviewed and corrected.', 'Staff retrained on NHS charging rules. Charging checklist created and displayed at reception.', 'Financial compliance officer now audits all charges quarterly.'),
('COMP250013', 'Repeat prescription request processed incorrectly, resulting in medication not being available at pharmacy.', 'Emergency prescription issued. Pharmacy liaison established. Process reviewed.', 'Electronic prescription tracking system upgraded. Repeat prescription protocol revised.', 'Prescription coordinator role created to oversee repeat prescription system.'),
('COMP250014', 'Interpreter not arranged for patient consultation despite advance request. Language barrier affected care.', 'Interpreter arranged for follow-up appointment. Booking system updated to flag interpreter requirements.', 'New protocol ensures interpreter bookings confirmed 24 hours in advance. Backup telephone interpretation available.', 'Language needs now recorded prominently in patient records with automatic alerts.'),
('COMP250015', 'Medical equipment failure during examination. Blood pressure monitor not working correctly.', 'Equipment replaced immediately. All devices tested. Maintenance schedule reviewed.', 'Preventative maintenance programme established. Daily equipment checks introduced.', 'Equipment register now maintained with test certificates and service records.'),
('COMP250016', 'Staff member made inappropriate comment about patient''s weight during consultation.', 'Staff member underwent sensitivity training. Patient apologised to. Incident reviewed with HR.', 'Enhanced professional boundaries training for all clinical staff. Patient feedback system improved.', 'Bi-annual equality and diversity training now mandatory for all staff.'),
('COMP250017', 'Medication dispensing error. Incorrect dosage of medication provided due to pharmacy stock error.', 'Patient contacted immediately. Correct medication dispensed same day. Follow-up appointment arranged.', 'Double-check system implemented for all prescriptions. Pharmacy stock reorganised and clearly labelled.', 'Monthly pharmacy audits now conducted. Stock management system upgraded.'),
('COMP250018', 'Patient not informed about test results indicating need for further investigation. Results filed but no action taken.', 'Patient contacted urgently. Specialist referral expedited. Results handling process reviewed.', 'Abnormal results now trigger automatic alerts. Results review meetings scheduled weekly.', 'Safety net system implemented with multiple checkpoints for all test results.'),
('COMP250019', 'Practice failed to provide reasonable adjustments for patient with disability as required by Equality Act.', 'Adjustments implemented immediately. Disability access audit conducted. Patient support plan created.', 'Accessibility coordinator appointed. Reasonable adjustments policy revised and communicated to all staff.', 'Quarterly accessibility reviews now conducted with patient feedback.'),
('COMP250020', 'Surgery cancelled at short notice without adequate explanation or alternative offered.', 'Alternative surgery date arranged urgently. Apology issued. Cancellation protocol reviewed.', 'Enhanced communication protocol for surgery changes. Automatic alternative appointment booking system.', 'Surgery coordinator role created to manage scheduling and patient communication.')
ON CONFLICT (complaint_reference) DO UPDATE SET
  key_findings = EXCLUDED.key_findings,
  actions_taken = EXCLUDED.actions_taken,
  improvements_made = EXCLUDED.improvements_made,
  additional_context = EXCLUDED.additional_context;

-- Verification comment: After this migration, complaint_demo_responses should contain exactly 20 rows
-- SELECT COUNT(*) FROM complaint_demo_responses; -- Should return 20