-- Add processing timing columns to lg_patients table
ALTER TABLE public.lg_patients
ADD COLUMN IF NOT EXISTS upload_started_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS upload_completed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS ocr_started_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS ocr_completed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS pdf_started_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS pdf_completed_at TIMESTAMP WITH TIME ZONE;