-- Replace with the complete comprehensive transcript from all logs
UPDATE meeting_transcripts 
SET content = 'I think you can apply that to the whole of arts, can''t you? Something''s going to happen, but then what are you going to do with all these people? The redundancy costs are being massive. If you produce a stable, as in they''re just taken on like GPs, they just happen to be funded through a bit of a different channel, but you provide stability and practice where that GP then stays year after year after year, and all of a sudden 30, 40 grand disappears, it''s going to be hard. It''s going to be very difficult. There''s a lot of change coming, isn''t there? Julia said that even when she was talking, Ellie, she looked a bit doughy-eyed. She said, oh, I don''t even know if we''ve got a job. That bit really annoyed me. I was talking about how insecure these people are. That''s what she came back with, was it? Well, we at the ICB don''t know if we''ve got a job. It''s nothing to do with us.

Well, you can apply that to the whole of arts, can''t you? Something''s going to happen, but then what are you going to do with all these people? The redundancy costs would be massive. If you produce a stable, as in they''re just taken on like GPs, they just happen to be funded through a bit of a different channel, but you provide stability and practice where that GP then stays year after year after year, and all of a sudden 30, 40 grand disappears. It''s going to be hard. I just think there''s a lot of change coming, isn''t there? Gina said that even when she was talking, Ellie, she looked a bit doughy-eyed when she said, oh, I don''t even know if we''ve got a job, you know. That bit really annoyed me. She was talking about, I was talking about how insecure... Yeah, that''s what she came back with, was it? She said, well, we at the ICB don''t know if we''ve got a job. Nothing to do with us.

I just think there''s a lot of change coming, isn''t there? Gill has said that even when she was talking, Ellie, she looked a bit doughy-eyed when she said, oh, I don''t even know if we''ve got a job, you know. That bit really annoyed me. She was talking about, I was talking about, I think I was talking about how insecure... Yeah, that everything is. That''s what she came back with, was it? She said, well, we at the ICB don''t know if we''ve got a job, so it''s nothing to do with us. It''s affecting us, but we''re not affecting them. That''s right. So don''t throw that in. Everyone kind of, there''s a small sigh in the room when she said that. Oh, really? Well, I might have been one. But that''s not right, is it, to bring that in? No. I''m on it. It''s a bad argument, isn''t it? It''s a really bad argument. Good. What else do you need to cover with me today, sir? I think I will send out those draft notes with just a cover line. Yeah, it doesn''t need a lot. Just say there''s no big change. We''ll bring your questions to the dinner in the evening.

You''re affecting us, but we''re not affecting them, so don''t throw that in. There was a small sigh in the room when she said that. Oh, really? Well, I know I had that one. But that''s not right, is it, to bring that in? No. I''m on it. It''s a bad argument, isn''t it? It''s a really bad argument. Good. What else do you need to cover with me today, sir? I think I will send out those draft accounts with just a cover line. Yeah, it doesn''t need a lot. Just say there''s no big change. We will have all the accounts, the detailed accounts. No need to do any kind of AGM-y bits. Yes. Previously, we''d have had two days. Yes. We''ve only got one day this week. Yes, that''s right. And then it''s going to take a while. It is. And we''ve got PML coming, which is going to take a while. I don''t think that''s really good. I think that''s excellent. I think it''s going to be good. It''s going to be about having less people suddenly coming. Try and see who''s coming. But I would like a GPB.

Yes, and we will have all the accounts, the detailed accounts, ready to go. ...if you''re doing any kind of AGM-y bits. Yes. Because previously, we''d have two days. Yes. We''ve only got one day this week. Yes, that''s right. And then it''s going to take a while. It is. And we''ve got PML coming, which is going to take a while. I don''t think that''s really good. I think that''s excellent. It''s going to be good. It''s going to be about having less people suddenly coming, trying to see who''s coming. But I would like a GP partner, if possible, from each... I''ll message her today and say, Am I right? Dean Dale''s not coming. Are you sending a replacement today? Yes, that''d be great. Doesn''t he have a... Oh, great. Which, if she comes back and says, No, no other partner is coming. Then I''ll have to message her back and just say... Oh, OK.

...if possible from each one. I''ll message Hayley today and say, am I right, the indel is not coming, are you sending a replacement today? Yes, that would be great. I don''t think they are though. Oh great. Which, if she comes back and says no, no other partner is coming then I''ll have to message her back and say, please can you ensure that you have kind of decision-making ability on behalf of the partnership. There''s no point having a weird day. I mean, there''s going to be a bit of that, isn''t there? But then there''s always that with partners, isn''t there? Oh, I have to ask my partners. That''s not really an issue. Just be a big turtle like me. I don''t tell them anything. Thank you.

I''ll message Hayley today and say, am I right, Lee and Dale''s not coming, are you sending a replacement today? Yes, that would be great. I don''t think they are, though. Oh, great. Which, if she comes back and says, no, no other partner is coming, I''ll have to message her back and just say, can you ensure that you have kind of decision-making on behalf of the partnership? There''s no point having a weird day. Yeah, correct. I mean, there''s going to be a bit of that, isn''t there? But then there''s always that with partners, isn''t there? Oh, I have to ask my partners. That''s not really an issue. Just be a dick turtle like me. I don''t tell them anything.

...concept oriented, it''s a stroke of the trowel, no problem at all, everyone''s said we need more GP time and we''ve facilitated it, so... I mean, Dale is very down that line, isn''t he? He''s like, I''ll replace Paul with... Well, I think as well, it''s come out of the back of the situation of Andy, you know. If it''s Sarah, Andy''s going, he''s probably taking home a big chunk of change out of that practice every year, quite rightly. And now there''s the opportunity to replace a GP with a GP and get... Most of the money paid for? Yeah, good plan, thinking of the right one, that''s the risk, isn''t it, like always? The thing that I can''t quite get my head around, whether it continues anyways, when you take on a GP under us, and they say, right, they''ve got to be qualified, say our funding carries on year after year after year, in three, four, five years from now, they''re still going to fund that same doctor... Who is no longer newly qualified? They''re going to come to a point, aren''t they, where you think they''re going to turn around and say, right...

It''s a stroke of the trowel. No problem at all. Everyone''s just said we need more GP time and we''ve facilitated it. I mean, Dal is very down that line, isn''t he? He''s like, I''ve replaced Paul with... Well, I think as well, it''s come out of the back of the situation of Andy, you know. If you see where Andy''s going, he''s probably taking home a big chunk of change out of that practice every year, quite rightly. And now there''s the opportunity to replace a GP with a GP and get... Most of the money paid, yeah. Thinking of the right one, that''s the risk, isn''t it, like always? The thing that I can''t quite get my head around, whether it continues anyways, when you take on a GP under us and they say, right, they''ve got to be qualified, say GP funding carries on year after year after year, in three, four, five years from now, they''re still going to fund that same doctor... Who is no longer newly qualified. They''re going to come to a point, aren''t they, where you think... They''ll say... Right, that GP''s come to a point...

Good plan, thinking of the right one. That''s the risk, isn''t it, like always? The thing that I can''t quite get my head around, whether it continues anyway, is when you take on a GP under arse and they say, right, they''ve got to be qualified, say a GP''s funding carries on year after year after year, in three, four, five years from now, they''re still going to fund that same doctor. Who is no longer newly qualified. They''re going to come a point, aren''t they, where you think they''re going to turn around and say, right, that GP''s come to arse. Well, you can apply that to the whole of arse, can''t you? Something''s going to happen, but then what are you going to do with all these people? The redundancy costs are being massive. I don''t know. If you produce a stable, as in they''re just taken on like GPs, they just happen to be funded through a bit of a different channel, but you provide stability and practice where that GP then stays year after year after year, and all of a sudden 30, 40 grand disappears, it''s going to be hard. It''s going to be very difficult.

Just say, please can you ensure that you have kind of decision-making ability on behalf of the partnership? Yeah, yeah, yeah, yeah, yeah. There''s no point having it in a weird way. Yeah, correct, yeah. I mean, there''s going to be a bit of that, isn''t there? But then there''s always that with partners, isn''t there? Oh, I have to ask my partners. That''s not really an issue. Or just be a dictator like me. I don''t tell them anything. But from a PCN point of view, yeah, I suppose if you''re going down a certain route and saying, right, we''re creating a new thing called the health and well-being team, then that means. But that''s what I mean. We''re not redesigning anything. We''re just kind of fine-tuning what''s already in place this next year. I don''t think we want to start ripping everything up. We''ve just got to fine-tune individuals within the current structure, I think. Yep. Yeah, sounds good.

Yeah, I suppose if you''re going down a certain route and saying right we''re creating a new thing called the health and well-being team. Then that means but we''re not that''s what I mean. We''re not we''re not we''re not redesigning anything. We''re just kind of fine-tuning what''s already placed this next year. I don''t think I Don''t think we won''t start ripping everything up. We''ve just got to fine-tune individuals within the current structure. I think yeah. Yeah I Have I have a plan on the horizon? Yes But I it''s probably too early to actually talk about it, but We''re going to a little bit with Karen leaving.'
WHERE meeting_id = '8db10bef-12aa-4eb4-a53d-d2c4ff0099de';