INSERT INTO meeting_transcripts (meeting_id, content, created_at)
VALUES (
  '8db10bef-12aa-4eb4-a53d-d2c4ff0099de',
  'Just say, please can you ensure that you have kind of decision-making ability on behalf of the partnership? Yeah, yeah, yeah, yeah, yeah. There''s no point having it in a weird way. Yeah, correct, yeah. I mean, there''s going to be a bit of that, isn''t there? But then there''s always that with partners, isn''t there? Oh, I have to ask my partners. That''s not really an issue. Or just be a dictator like me. I don''t tell them anything. 

But from a PCN point of view, yeah, I suppose if you''re going down a certain route and saying, right, we''re creating a new thing called the health and well-being team, then that means. But that''s what I mean. We''re not redesigning anything. We''re just kind of fine-tuning what''s already in place this next year. I don''t think we want to start ripping everything up. We''ve just got to fine-tune individuals within the current structure, I think. Yep. Yeah, sounds good.

Yeah, I suppose if you''re going down a certain route and saying right we''re creating a new thing called the health and well-being team. Then that means but we''re not that''s what I mean. We''re not we''re not we''re not redesigning anything. We''re just kind of fine-tuning what''s already placed this next year. I don''t think I Don''t think we won''t start ripping everything up. We''ve just got to fine-tune individuals within the current structure. I think yeah. Yeah I Have I have a plan on the horizon? Yes But I it''s probably too early to actually talk about it, but We''re going to a little bit with Karen leaving.

I''ll message Hayley today and say, am I right, Lee and Dale''s not coming, are you sending a replacement today? Yes, that would be great. I don''t think they are, though. Oh, great. Which, if she comes back and says, no, no other partner is coming, I''ll have to message her back and just say, can you ensure that you have kind of decision-making on behalf of the partnership? There''s no point having a weird day. Yeah, correct. I mean, there''s going to be a bit of that, isn''t there? But then there''s always that with partners, isn''t there? Oh, I have to ask my partners. That''s not really an issue. Just be a dick turtle like me. I don''t tell them anything.

...if possible from each one. I''ll message Hayley today and say, am I right, the indel is not coming, are you sending a replacement today? Yes, that would be great. I don''t think they are though. Oh great. Which, if she comes back and says no, no other partner is coming then I''ll have to message her back and say, please can you ensure that you have kind of decision-making ability on behalf of the partnership. There''s no point having a weird day. I mean, there''s going to be a bit of that, isn''t there? But then there''s always that with partners, isn''t there? Oh, I have to ask my partners. That''s not really an issue. Just be a big turtle like me. I don''t tell them anything.

Yes, and we will have all the accounts, the detailed accounts, ready to go. ...if you''re doing any kind of AGM-y bits. Yes. Because previously, we''d have two days. Yes. We''ve only got one day this week. Yes, that''s right. And then it''s going to take a while. It is. And we''ve got PML coming, which is going to take a while. I don''t think that''s really good. I think that''s excellent. It''s going to be good. It''s going to be about having less people suddenly coming, trying to see who''s coming. But I would like a GP partner, if possible, from each...',
  now()
);