UPDATE meetings SET best_of_all_transcript=$xx$Right, shall we get started? It's just gone ten past, I think we've got everyone we're going to get. Apologies received from Lorraine — she's at the LMC executive meeting this morning — and from Mel who's covering an extra clinic at Brackley because their salaried GP's off sick. Anita's joining by Teams, can you hear us okay Anita? Yes, fine, hi everyone. Good. Right, the agenda's in your packs, eight items plus AOB, I want to keep this to an hour so I'll be moving us along. First item is the Q4 finance position, then ARRS workforce planning for 2026/27, then the QOF recovery plan, then the digital transformation update, then estates including the boiler decision we deferred from last month, then clinical governance and complaints, then the ICB ENN pilot decision, then the patient survey results, then AOB which I think Marcus has flagged something about the LMC update. Before we start, can I just confirm — Teams recording is on, isn't it Sarah? Yes, recording started at 10:08 and Notewell's running for the minutes. Good. James, take us through finance.

Thanks. So the headline position at end of Q3 is that we're approximately £14,000 down on budget across the partnership. The main drivers are locum costs running 22% above forecast — that's the salaried GP sickness we've had over the winter, plus Dr Patel's maternity leave starting earlier than planned by about three weeks, which meant we couldn't recruit the maternity cover lead-in we'd budgeted for. Plus utility costs which are up 18% on last year despite the supposed cap, mostly because we've been running the air handling units harder during the respiratory virus surge from late October through to mid-January.

Against those negatives we've had three positive variances. The dispensary income is up 11% on forecast, mostly because of the GLP-1 dispensing volume increasing through the autumn — we've gone from about 240 GLP-1 prescriptions a month at start of year to nearly 400 a month now, which is a substantial revenue uplift even at the modest dispensing margin. QOF achievement payments are tracking ahead at 89.2% versus our budgeted 86%, that's worth roughly £6,000 against budget if we hold that level. And the enhanced services income from the cardiology shared-care arrangement is running at about £3,200 per quarter rather than the £2,500 we'd planned, because the volume of patients we're managing on shared-care has grown faster than the contract assumed. So net £14k down, mostly cost-side, partially mitigated by income upside.

Cash position is fine, we've got just over four months of operating costs in the reserves account, which is exactly where the partnership agreement says we want to be heading into the year-end purchase cycle. The accountant's draft Q3 report is in your packs — I'd particularly draw your attention to page four, the dispensing margin analysis. We're seeing margin compression on the high-volume generics, which is sector-wide and well documented in the Pharmaceutical Journal piece I circulated last month. But our dispensary's adjusted by leaning more heavily into the specials and aseptic compounding work for the care homes, which has higher margins — about 16% gross margin versus 4% on high-volume generics. Long-term that's not a sustainable strategy because the specials volume's capped at what the local care homes need, but for this year it's offsetting roughly half the generic margin loss.

We need to think about whether we want to invest in the robotic dispensing unit that I mentioned at the September meeting — the BD Rowa Vmax, capital cost approximately £45,000 installed, payback period about 28 months on current volumes through reduced pharmacy technician hours. That's a partnership-level capital decision rather than something for today, but I'd suggest we put it on the May agenda with a proper business case. The reason it's relevant now is that BD have offered an end-of-financial-year discount of £6,000 if we commit by end of May, which would cut the payback to 24 months. Worth thinking about.

Any questions on finance before we move on? Yes, on the locum costs — are we still using the same agency or have we moved providers? We're still mostly with Bridgewater because the rates are competitive and we've got a good relationship with their consultant for the bookings, but I have brought in two locum sessions through ProDoc this quarter when Bridgewater couldn't fill on short notice. ProDoc's about 12% more expensive but they've never failed to fill, so for the urgent cover I think it's worth the premium. They're also better on the IR35 paperwork which has been a faff with Bridgewater's newer GPs. Right. And on the dispensary margin — when you say sector-wide pressure, is that from the new framework agreement? Partly, and partly the manufacturer-level consolidation, particularly on metformin and atorvastatin where we've gone from four suppliers to two over eighteen months. Less competitive tendering, higher unit prices to us. Okay, thanks.

One more on finance — the year-end accounts. When are we going to get the preliminary figures from the accountant? She's promised end of April for the draft, with the audit completing by end of May. That would give us the partnership tax meeting in early June, which fits with the partnership agreement timeline. The slight wrinkle is the new partner buy-in calculation for Dr Chen joining in July — the accountant needs the year-end goodwill valuation before she can finalise the buy-in number. So if accounts slip, the buy-in slips, which has implications for Dr Chen's contractual start. I've flagged this with the accountant and she's confident on the timeline. Right, item two, ARRS workforce planning. Sarah?

Thanks. So we've had the indicative ARRS allocation for 2026/27 from the ICB — £487,000 against £473,000 last year, headline 3.0% uplift. But the underlying picture's worse than that because of two things: the employer NI increase from April adds 1.2% to all our existing post-holders, and the NHS pension employer contribution went up to 23.7% in the last revision which adds another 1.4%. So in real terms our spending power is actually about £18,000 lower than 2025/26, despite the headline going up. That reduces the number of WTEs we can fund from approximately 12.0 down to 11.2.

Just to put that in context — the BMA's modelling suggests the average PCN is losing about £20,000 of real ARRS spending power this year, so we're broadly in line with the sector. Some PCNs are reporting larger losses because they're carrying more high-band post-holders where the employer NI bites harder. Our skew towards the lower bands — physician associates, social prescribers, care coordinators — actually helps us slightly here. So we're not in a worse position than peers, but we are in a worse position than we were a year ago and that has to translate into workforce decisions.

The decision we need to take today is what to do about the pharmacist post when Aisha's contract ends in August. As a reminder, she's been doing structured medication reviews three days a week since June 2024, and she's worked through about 380 high-risk polypharmacy patients in that time. The reviews have generated documented medication changes for 71% of patients reviewed, and we estimate about £14,000 of annual prescribing budget savings from the deprescribing alone. Plus there's the clinical risk reduction which is harder to monetise but obviously real — roughly 40 patients have had QT-prolonging combinations identified and corrected, six patients have come off long-term PPIs that weren't indicated, and we've stopped about a dozen anticholinergic combinations in elderly patients with falls history.

So the question is, do we replace her at full WTE, do we replace her at part-time, do we substitute for a different ARRS-eligible role, or do we not replace at all. Each of those has implications. Full replacement at 0.6 WTE costs us about £33,000 inclusive of on-costs, given the band 8a benchmark for a clinical pharmacist with three years post-registration experience. We could substitute for a paramedic at 0.4 WTE for £21,000, which would address the home-visit capacity issue we've been talking about for the frailty cohort — current waiting time for a routine GP home visit is averaging eight days which is too long and exposes us if anything happens. Or we could do both at reduced WTE — pharmacist at 0.4 plus paramedic at 0.4 — for combined £42,000. That keeps both capacities going but at thinner cover than we'd ideally want.

My recommendation, and I've sense-checked this with Aisha who's amenable to the change, is option two — pharmacist at 0.6 WTE focused entirely on SMRs, plus paramedic at 0.4 WTE for frailty home visits. Total £54,000 against £58,000 of available ARRS allocation for these two roles, leaving £4,000 contingency for sickness cover or agency rate increases. That's tight but workable.

Item three, QOF recovery plan. We're currently at 89.2% of points which is above budget but below our internal target of 92%. The main gaps are in the diabetes domain — DM006 and DM012 specifically — where we've fallen behind on annual reviews because of the pharmacist diversion to GLP-1 initiation work. The recovery plan is to bring in the locum nurse one extra session per week from now until end of March to clear the backlog. Cost is approximately £4,800 across the period which is well within our QOF income upside. Question — is the locum nurse competent for diabetes annual reviews? Yes, she's done them at the federation practices for the last two years and has the diabetes annual review competency sign-off. Approved.

Item four, digital transformation. We've completed phase one of the EMIS migration with no clinical incidents reported. Phase two — the patient-facing app rollout — starts in May. The risks are around patient confusion during the transition and around the appointment booking integration which we've had two test failures on. Mitigations: extended reception briefing in late April, parallel running of old and new booking systems for two weeks, and a daily standup during the launch fortnight. The ICB digital lead has offered to embed for a week which I think we should accept.

Item five, estates. The boiler. Quote from Worcester Bosch is £18,400 for the replacement heat-only boiler plus £3,200 for the controls upgrade, total £21,600. Quote from Vaillant is £19,800 for the boiler plus £2,400 for controls, total £22,200. I'd recommend the Worcester Bosch on price and on the seven-year warranty versus Vaillant's five-year. Approved. Schedule for installation week beginning 14th April when we can step down to single boiler operation.

Item six, clinical governance and complaints. Three formal complaints this quarter, all closed within the 40-day window. Two were about telephone access, one was about a delayed referral. Themes are consistent with previous quarters and feed into the patient survey actions. Significant events: two reviewed at the last clinical meeting, both closed with learning points around documentation. No notifiable patient safety incidents this quarter.

Item seven, the ICB ENN pilot. The Enhanced Neighbourhood Network pilot decision has been deferred by the ICB to June. We don't need to commit today. I'd suggest we keep our position warm by attending the next stakeholder meeting on 22nd May — Sarah, can you cover that one? Yes, I'll attend.

Item eight, patient survey. The annual GP patient survey results came back last week. Headline is 88% would-recommend, up from 84% last year, which is the best score we've had since 2019. National median is 72% so we're well above average. Local PCN average is 79% so we're best-in-PCN as well. The free-text comments are the more useful bit — three themes coming through. First, telephone access is the main negative — patients say it's hard to get through, especially Monday mornings. Second, reception waiting times — patients waiting 8-10 minutes to be checked in is too long. Third, continuity of care — some longstanding patients note that they don't see the same GP twice running, which is partly the salaried GP turnover we've had this year.

On telephone access, the cloud-based phone system pilot the ICB's been running might help. On reception waiting times, the receptionist we've recruited starting next month should help materially because we'll be running with three on the desk on Mondays rather than two. Action Sarah to investigate the cloud phone system pilot status and report back in June.

Right, AOB. Marcus, you flagged something about the LMC? Yes, the LMC AGM is on the 15th of June and they're looking for nominations for the executive committee. The LMC has just published their template for the new partnership agreement which incorporates the changes required by the 2026/27 GP contract. I'll circulate the template by email this week. Anything else? One quick thing, the CQC inspection window is now formally July to October. Worth us doing a self-assessment in May. I'll bring a draft self-assessment template to the next meeting.

Anything else? No? Right, thanks everyone. Next meeting Wednesday 11th June, same time, same place. Travel safely. Anita, you can hop off Teams whenever. Thanks all.$xx$, whisper_transcript_text=best_of_all_transcript WHERE id='aaaaaaaa-bbbb-cccc-dddd-000000000301';