-- Seed Policy Reference Library with 60+ NHS policies from specification

INSERT INTO public.policy_reference_library (policy_name, category, cqc_kloe, priority, guidance_sources, required_services, required_roles, description) VALUES
-- Clinical Policies (3.1)
('Safeguarding Adults', 'Clinical', 'Safe', 'Essential', '["Care Act 2014", "NHS England Safeguarding Framework", "Mental Capacity Act 2005", "Liberty Protection Safeguards"]'::jsonb, '{}', '{"safeguarding_lead_adults"}', 'Policy for protecting vulnerable adults from abuse and neglect'),
('Safeguarding Children', 'Clinical', 'Safe', 'Essential', '["Children Act 1989/2004", "Working Together 2023", "LSCB Guidelines"]'::jsonb, '{}', '{"safeguarding_lead_children"}', 'Policy for protecting children from harm'),
('Chaperone Policy', 'Clinical', 'Safe', 'Essential', '["GMC Intimate Examinations Guidance", "NHS England Standards"]'::jsonb, '{}', '{}', 'Guidance on use of chaperones during intimate examinations'),
('Infection Prevention & Control', 'Clinical', 'Safe', 'Essential', '["Health & Social Care Act 2008", "NICE NG229", "UK IPC Guidelines"]'::jsonb, '{}', '{"infection_control_lead"}', 'Comprehensive IPC policy for the practice'),
('Medical Emergencies', 'Clinical', 'Safe', 'Essential', '["Resuscitation Council UK Guidelines", "NICE NG51"]'::jsonb, '{}', '{}', 'Response procedures for medical emergencies'),
('Prescribing Policy', 'Clinical', 'Effective', 'Essential', '["NICE Medicines Optimisation", "BNF Guidelines", "Controlled Drugs Regulations"]'::jsonb, '{}', '{}', 'Safe and effective prescribing standards'),
('Controlled Drugs', 'Clinical', 'Safe', 'Essential', '["Misuse of Drugs Regulations 2001", "CD Accountable Officer Guidance"]'::jsonb, '{}', '{}', 'Management and governance of controlled drugs'),
('Clinical Governance', 'Clinical', 'Well-led', 'Essential', '["NHS England Clinical Governance Framework"]'::jsonb, '{}', '{}', 'Framework for clinical quality and safety'),
('Consent', 'Clinical', 'Effective', 'Essential', '["Mental Capacity Act 2005", "GMC Decision Making & Consent"]'::jsonb, '{}', '{}', 'Obtaining valid consent for treatment'),
('Do Not Attempt CPR (DNACPR)', 'Clinical', 'Effective', 'Essential', '["Resuscitation Council UK", "ReSPECT Process"]'::jsonb, '{}', '{}', 'DNACPR decision making and documentation'),
('End of Life Care', 'Clinical', 'Caring', 'Essential', '["NICE NG142", "Ambitions for Palliative & End of Life Care"]'::jsonb, '{}', '{}', 'Compassionate end of life care delivery'),
('Medication Errors & Near Misses', 'Clinical', 'Safe', 'Essential', '["MHRA Yellow Card", "NRLS Reporting Guidelines"]'::jsonb, '{}', '{}', 'Reporting and learning from medication incidents'),
('Sample Handling & Transport', 'Clinical', 'Safe', 'Essential', '["HSE Guidance", "UN3373 Regulations"]'::jsonb, '{}', '{}', 'Safe handling and transport of clinical samples'),
('Cold Chain Management', 'Clinical', 'Safe', 'Essential', '["PHE Green Book", "Vaccine Storage Guidelines"]'::jsonb, '{}', '{}', 'Maintaining vaccine cold chain integrity'),
('Cervical Screening', 'Clinical', 'Effective', 'Essential', '["NHS Cervical Screening Programme Standards"]'::jsonb, '{}', '{}', 'Delivery of cervical screening programme'),
('Childhood Immunisations', 'Clinical', 'Effective', 'Essential', '["PHE Green Book", "NHS Immunisation Schedule"]'::jsonb, '{}', '{}', 'Childhood immunisation programme delivery'),
('Travel Health', 'Clinical', 'Effective', 'Recommended', '["NaTHNaC Guidelines", "PHE Guidance"]'::jsonb, '{}', '{}', 'Travel health advice and vaccination service'),
('Minor Surgery', 'Clinical', 'Safe', 'Service-specific', '["NICE IPG Guidelines", "Local CCG/ICB Standards"]'::jsonb, '{"minor_surgery"}', '{}', 'Minor surgical procedures in general practice'),
('Contraception & Sexual Health', 'Clinical', 'Effective', 'Service-specific', '["FSRH Guidelines", "NICE CG30"]'::jsonb, '{}', '{}', 'Contraception and sexual health services'),
('Mental Health', 'Clinical', 'Effective', 'Recommended', '["NICE Depression/Anxiety Guidelines", "MH Crisis Concordat"]'::jsonb, '{}', '{}', 'Mental health assessment and support'),

-- Information Governance Policies (3.2)
('Data Protection & GDPR', 'Information Governance', 'Safe', 'Essential', '["UK GDPR", "Data Protection Act 2018", "ICO Guidance"]'::jsonb, '{}', '{"dpo_name"}', 'Compliance with data protection legislation'),
('Confidentiality', 'Information Governance', 'Safe', 'Essential', '["Caldicott Principles", "Common Law Duty of Confidence"]'::jsonb, '{}', '{"caldicott_guardian"}', 'Maintaining patient confidentiality'),
('Subject Access Requests', 'Information Governance', 'Responsive', 'Essential', '["UK GDPR Article 15", "ICO SAR Code of Practice"]'::jsonb, '{}', '{}', 'Handling patient data access requests'),
('Records Management', 'Information Governance', 'Effective', 'Essential', '["NHS Records Management Code of Practice 2021"]'::jsonb, '{}', '{}', 'Management of clinical and business records'),
('Information Security', 'Information Governance', 'Safe', 'Essential', '["NHS Data Security Standards", "Cyber Essentials Plus"]'::jsonb, '{}', '{}', 'Protection of information assets'),
('Information Sharing', 'Information Governance', 'Safe', 'Essential', '["Data Sharing Code of Practice", "Caldicott Principles"]'::jsonb, '{}', '{"caldicott_guardian"}', 'Appropriate sharing of patient information'),
('Data Quality', 'Information Governance', 'Effective', 'Recommended', '["NHS Data Quality Maturity Index"]'::jsonb, '{}', '{}', 'Maintaining high quality data'),
('Freedom of Information', 'Information Governance', 'Responsive', 'Essential', '["Freedom of Information Act 2000"]'::jsonb, '{}', '{}', 'Responding to FOI requests'),
('Registration Authority', 'Information Governance', 'Safe', 'Essential', '["NHS Smartcard RA Policy", "Identity Verification"]'::jsonb, '{}', '{}', 'Smartcard and identity management'),
('Mobile Device & Remote Working', 'Information Governance', 'Safe', 'Essential', '["NHS DSP Toolkit", "NCSC Mobile Security"]'::jsonb, '{}', '{}', 'Secure mobile and remote working'),
('Social Media', 'Information Governance', 'Well-led', 'Recommended', '["NMC/GMC Social Media Guidance", "NHS Employers Guidance"]'::jsonb, '{}', '{}', 'Appropriate use of social media'),
('Email & Electronic Communication', 'Information Governance', 'Safe', 'Essential', '["NHSmail Acceptable Use Policy"]'::jsonb, '{}', '{}', 'Secure electronic communications'),
('Cyber Security Incident Response', 'Information Governance', 'Safe', 'Essential', '["NHS DSPT", "NCSC Incident Management"]'::jsonb, '{}', '{}', 'Responding to cyber security incidents'),
('Data Protection Impact Assessment', 'Information Governance', 'Safe', 'Essential', '["ICO DPIA Guidance", "UK GDPR Article 35"]'::jsonb, '{}', '{"dpo_name"}', 'Conducting DPIAs for new processing'),

-- Health & Safety Policies (3.3)
('Health & Safety', 'Health & Safety', 'Safe', 'Essential', '["Health & Safety at Work Act 1974", "Management of H&S Regulations 1999"]'::jsonb, '{}', '{"health_safety_lead"}', 'Overall health and safety management'),
('Fire Safety', 'Health & Safety', 'Safe', 'Essential', '["Regulatory Reform (Fire Safety) Order 2005"]'::jsonb, '{}', '{"fire_safety_officer"}', 'Fire prevention and emergency procedures'),
('COSHH', 'Health & Safety', 'Safe', 'Essential', '["Control of Substances Hazardous to Health Regulations 2002"]'::jsonb, '{}', '{}', 'Management of hazardous substances'),
('Lone Working', 'Health & Safety', 'Safe', 'Essential', '["HSE Lone Working Guidance", "NHS Protect"]'::jsonb, '{}', '{}', 'Protecting staff working alone'),
('Violence & Aggression', 'Health & Safety', 'Safe', 'Essential', '["NHS Zero Tolerance", "HSE Work-Related Violence Guidance"]'::jsonb, '{}', '{}', 'Managing violence and aggression'),
('Risk Assessment', 'Health & Safety', 'Safe', 'Essential', '["Management of Health & Safety at Work Regulations 1999"]'::jsonb, '{}', '{}', 'Systematic risk assessment process'),
('Display Screen Equipment', 'Health & Safety', 'Safe', 'Essential', '["Health & Safety (Display Screen Equipment) Regulations 1992"]'::jsonb, '{}', '{}', 'Safe use of DSE'),
('Manual Handling', 'Health & Safety', 'Safe', 'Essential', '["Manual Handling Operations Regulations 1992"]'::jsonb, '{}', '{}', 'Safe manual handling practices'),
('First Aid', 'Health & Safety', 'Safe', 'Essential', '["Health & Safety (First-Aid) Regulations 1981"]'::jsonb, '{}', '{}', 'First aid provision and training'),
('Accident & Incident Reporting', 'Health & Safety', 'Safe', 'Essential', '["RIDDOR 2013"]'::jsonb, '{}', '{}', 'Reporting and investigating incidents'),
('Sharps & Needlestick Injuries', 'Health & Safety', 'Safe', 'Essential', '["Health & Safety (Sharp Instruments) Regulations 2013"]'::jsonb, '{}', '{}', 'Prevention and management of sharps injuries'),
('Legionella Management', 'Health & Safety', 'Safe', 'Essential', '["HSE L8 Approved Code of Practice"]'::jsonb, '{}', '{}', 'Water safety and legionella control'),
('Asbestos Management', 'Health & Safety', 'Safe', 'Essential', '["Control of Asbestos Regulations 2012"]'::jsonb, '{}', '{}', 'Management of asbestos in premises'),
('Electrical Safety', 'Health & Safety', 'Safe', 'Essential', '["Electricity at Work Regulations 1989"]'::jsonb, '{}', '{}', 'Electrical safety and testing'),
('Medical Devices Management', 'Health & Safety', 'Safe', 'Essential', '["MHRA Medical Devices Regulations"]'::jsonb, '{}', '{}', 'Safe management of medical devices');